import { BadRequestException, Injectable } from '@nestjs/common';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

@Injectable()
export class QualityCapaService {
  private readonly db: SupabaseClient = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_KEY!);
  private fail(error: any, fallback: string): never { throw new BadRequestException(error?.message || fallback); }
  private text(value: any) { return String(value || '').trim(); }
  private number(value: any) { const parsed = Number(value || 0); return Number.isFinite(parsed) ? parsed : 0; }
  private async case(tenantId: string, id: string) { const { data, error } = await this.db.from('quality_capa_cases').select('*').eq('tenant_id', tenantId).eq('id', id).maybeSingle(); if (error || !data) this.fail(error, 'CAPA case was not found.'); return data; }

  async dashboard(tenantId: string) {
    const [{ data: cases, error: caseError }, { data: actions, error: actionError }, { data: ncrs, error: ncrError }, { data: vendors, error: vendorError }] = await Promise.all([
      this.db.from('quality_capa_cases').select('*').eq('tenant_id', tenantId).order('created_at', { ascending: false }),
      this.db.from('quality_capa_actions').select('*').eq('tenant_id', tenantId).order('due_date'),
      this.db.from('ncr').select('id,ncr_number,description,status,vendor_id,cost_impact').eq('tenant_id', tenantId).order('ncr_date', { ascending: false }),
      this.db.from('vendors').select('id,code,name').eq('tenant_id', tenantId).order('name'),
    ]);
    if (caseError) this.fail(caseError, 'Unable to load CAPA cases.'); if (actionError) this.fail(actionError, 'Unable to load CAPA actions.'); if (ncrError) this.fail(ncrError, 'Unable to load NCRs.'); if (vendorError) this.fail(vendorError, 'Unable to load suppliers.');
    const vendorMap = new Map((vendors || []).map((vendor: any) => [String(vendor.id), vendor]));
    const today = new Date().toISOString().slice(0, 10);
    const rows = (cases || []).map((capa: any) => ({ ...capa, vendor: vendorMap.get(String(capa.vendor_id)), actions: (actions || []).filter((action: any) => String(action.capa_id) === String(capa.id)), overdue: capa.due_date < today && !['EFFECTIVE','PARTIAL','INEFFECTIVE','CANCELLED'].includes(capa.status) }));
    const closed = rows.filter((row: any) => ['EFFECTIVE','PARTIAL','INEFFECTIVE'].includes(row.status));
    return { kpis: { open_capas: rows.filter((row: any) => !['EFFECTIVE','PARTIAL','INEFFECTIVE','CANCELLED'].includes(row.status)).length, overdue_actions: (actions || []).filter((action: any) => action.status === 'OPEN' && action.due_date < today).length, failure_cost: rows.reduce((sum: number, row: any) => sum + this.number(row.failure_cost), 0), recovery_pipeline: rows.reduce((sum: number, row: any) => sum + Math.max(0, this.number(row.supplier_claim_amount) - this.number(row.supplier_recovered_amount)), 0), supplier_recovered: rows.reduce((sum: number, row: any) => sum + this.number(row.supplier_recovered_amount), 0), verified_avoidance: closed.reduce((sum: number, row: any) => sum + this.number(row.realized_annual_avoidance), 0) }, cases: rows, ncrs: ncrs || [], vendors: vendors || [] };
  }

  async create(tenantId: string, userId: string, body: any) {
    const title = this.text(body.title), source = this.text(body.source).toUpperCase(), severity = this.text(body.severity).toUpperCase(), problem = this.text(body.problem_statement), containment = this.text(body.immediate_containment), due = this.text(body.due_date);
    if (!title || !problem || !containment || !due || !['INTERNAL','SUPPLIER','CUSTOMER','AUDIT','REGULATORY'].includes(source) || !['LOW','MEDIUM','HIGH','CRITICAL'].includes(severity)) this.fail(null, 'Title, source, severity, problem, containment and due date are required.');
    if (source === 'SUPPLIER' && !body.vendor_id) this.fail(null, 'A supplier is required for supplier-origin CAPA.');
    const stamp = Date.now().toString().slice(-6), capaNumber = `CAPA-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${stamp}`;
    const { data, error } = await this.db.from('quality_capa_cases').insert({ tenant_id: tenantId, capa_number: capaNumber, title, source, severity, ncr_id: body.ncr_id || null, vendor_id: body.vendor_id || null, problem_statement: problem, immediate_containment: containment, due_date: due, failure_cost: this.number(body.failure_cost), estimated_annual_avoidance: this.number(body.estimated_annual_avoidance), supplier_claim_amount: this.number(body.supplier_claim_amount), created_by: userId }).select().single();
    if (error) this.fail(error, 'Unable to create CAPA case.'); return data;
  }

  async investigate(tenantId: string, userId: string, id: string, body: any) { const capa = await this.case(tenantId, id), method = this.text(body.root_cause_method).toUpperCase(), root = this.text(body.root_cause); if (capa.status !== 'OPEN' || !root || !['5_WHY','FISHBONE','8D','FAULT_TREE','OTHER'].includes(method)) this.fail(null, 'An open CAPA requires a valid root-cause method and documented root cause.'); return this.transition(tenantId, id, 'OPEN', { status: 'INVESTIGATED', root_cause_method: method, root_cause: root, investigated_by: userId, investigated_at: new Date().toISOString() }, 'Unable to complete investigation.'); }
  async addAction(tenantId: string, userId: string, id: string, body: any) { const capa = await this.case(tenantId, id), type = this.text(body.action_type).toUpperCase(), description = this.text(body.action_description), due = this.text(body.due_date); if (!['OPEN','INVESTIGATED'].includes(capa.status) || !description || !due || !['CONTAINMENT','CORRECTIVE','PREVENTIVE','SCAR'].includes(type)) this.fail(null, 'Actions require a valid type, description and due date before submission.'); const { data, error } = await this.db.from('quality_capa_actions').insert({ tenant_id: tenantId, capa_id: id, action_type: type, action_description: description, owner_user_id: body.owner_user_id || userId, due_date: due, created_by: userId }).select().single(); if (error) this.fail(error, 'Unable to add CAPA action.'); return data; }
  async submit(tenantId: string, userId: string, id: string) { const capa = await this.case(tenantId, id); if (capa.status !== 'INVESTIGATED') this.fail(null, 'Complete root-cause investigation before submission.'); const { count } = await this.db.from('quality_capa_actions').select('id', { count: 'exact', head: true }).eq('tenant_id', tenantId).eq('capa_id', id); if (!count) this.fail(null, 'At least one corrective or preventive action is required.'); return this.transition(tenantId, id, 'INVESTIGATED', { status: 'SUBMITTED', submitted_by: userId, submitted_at: new Date().toISOString() }, 'Unable to submit CAPA.'); }
  async approve(tenantId: string, userId: string, id: string, body: any) { const capa = await this.case(tenantId, id), note = this.text(body.approval_note); if (capa.status !== 'SUBMITTED' || capa.created_by === userId || !note) this.fail(null, 'Independent approval with rationale is required.'); return this.transition(tenantId, id, 'SUBMITTED', { status: 'APPROVED', approved_by: userId, approved_at: new Date().toISOString(), approval_note: note }, 'Unable to approve CAPA.'); }
  async completeAction(tenantId: string, userId: string, actionId: string, body: any) { const evidence = this.text(body.completion_evidence); if (!evidence) this.fail(null, 'Completion evidence is required.'); const { data: action } = await this.db.from('quality_capa_actions').select('*,capa:quality_capa_cases(status)').eq('tenant_id', tenantId).eq('id', actionId).maybeSingle(); if (!action || action.status !== 'OPEN' || action.capa?.status !== 'APPROVED') this.fail(null, 'Only actions on an approved CAPA can be completed.'); const { data, error } = await this.db.from('quality_capa_actions').update({ status: 'COMPLETED', completion_evidence: evidence, completed_by: userId, completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('tenant_id', tenantId).eq('id', actionId).eq('status', 'OPEN').select().single(); if (error) this.fail(error, 'Unable to complete action.'); return data; }
  async verify(tenantId: string, userId: string, id: string, body: any) { const capa = await this.case(tenantId, id), outcome = this.text(body.outcome).toUpperCase(), result = this.text(body.effectiveness_result), evidence = this.text(body.verification_evidence), avoidance = this.number(body.realized_annual_avoidance), recovered = this.number(body.supplier_recovered_amount); if (capa.status !== 'APPROVED' || capa.created_by === userId || !['EFFECTIVE','PARTIAL','INEFFECTIVE'].includes(outcome) || !result || !evidence || avoidance < 0 || recovered < 0 || recovered > this.number(capa.supplier_claim_amount)) this.fail(null, 'Independent effectiveness outcome, evidence, and valid ROI/recovery amounts are required.'); const { data: actions } = await this.db.from('quality_capa_actions').select('status').eq('tenant_id', tenantId).eq('capa_id', id); if (!(actions || []).length || (actions || []).some((action: any) => action.status !== 'COMPLETED')) this.fail(null, 'Complete every approved action before effectiveness verification.'); return this.transition(tenantId, id, 'APPROVED', { status: outcome, effectiveness_result: result, verification_evidence: evidence, realized_annual_avoidance: avoidance, supplier_recovered_amount: recovered, verified_by: userId, verified_at: new Date().toISOString() }, 'Unable to verify CAPA effectiveness.'); }
  private async transition(tenantId: string, id: string, expected: string, values: any, fallback: string) { const { data, error } = await this.db.from('quality_capa_cases').update({ ...values, updated_at: new Date().toISOString() }).eq('tenant_id', tenantId).eq('id', id).eq('status', expected).select().maybeSingle(); if (error || !data) this.fail(error, fallback); return data; }
}
