'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Loader2, RefreshCw, ShieldCheck } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';
const field='w-full rounded-lg border border-slate-300 px-3 py-2 text-sm';
export default function Page(){
  const[p,setP]=useState<any>(null),[evidenceRows,setEvidence]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[busy,setBusy]=useState(true),[msg,setMsg]=useState('');
  const load=useCallback(async()=>{setBusy(true);try{const[a,b,c,d]=await Promise.all([apiClient.get('/uae-compliance/profile'),apiClient.get('/uae-compliance/evidence'),apiClient.get('/uae-compliance/einvoices'),apiClient.get('/sales/invoices')]);setP(a);setEvidence(b);setDocs(c);setInvoices(d);setMsg('');}catch(e:any){setMsg(e?.message||'Unable to load UAE compliance controls.');}finally{setBusy(false);}},[]);
  useEffect(()=>{load();},[load]);
  const save=(url:string,message:string)=>async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();try{await apiClient.post(url,Object.fromEntries(new FormData(e.currentTarget)));setMsg(message);load();}catch(x:any){setMsg(x?.message||'Unable to save.');}};
  const prepare=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),id=String(d.get('invoice_id')||'');if(!id)return;try{await apiClient.post(`/uae-compliance/einvoices/prepare/${id}`,{transaction_scope:d.get('transaction_scope')});setMsg('Structured readiness payload prepared and validated.');load();}catch(x:any){setMsg(x?.message||'Unable to prepare eInvoice readiness payload.');}};
  const review=async(id:string,status:string)=>{await apiClient.patch(`/uae-compliance/evidence/${id}`,{status});load();};
  return <main className="mx-auto max-w-7xl space-y-5 p-4"><header className="flex justify-between rounded-2xl bg-gradient-to-r from-[#31584A] to-[#487967] p-6 text-white"><div><div className="flex items-center gap-2 text-sm text-green-100"><ShieldCheck size={18}/>UAE statutory and eInvoicing control</div><h1 className="mt-2 text-2xl font-bold">UAE Compliance Control Centre</h1><p className="mt-1 text-sm text-green-100">PINT-AE readiness and evidence workflow. No FTA filing, Peppol transmission or tax journal is created.</p></div><button onClick={load}>{busy?<Loader2 className="animate-spin"/>:<RefreshCw/>}</button></header>{msg&&<p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{msg}</p>}
  <div className="grid gap-5 lg:grid-cols-2"><form onSubmit={save('/uae-compliance/profile','Compliance profile saved.')} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Tax and ASP readiness profile</h2><input name="trn" defaultValue={p?.trn||''} placeholder="VAT TRN" className={field}/><input name="corporate_tax_registration_number" defaultValue={p?.corporate_tax_registration_number||''} placeholder="Corporate Tax registration number" className={field}/><input name="tax_period_reference" defaultValue={p?.tax_period_reference||''} placeholder="Tax period reference" className={field}/><select name="annual_revenue_band" defaultValue={p?.annual_revenue_band||''} className={field}><option value="">Annual revenue band</option><option value="GE_50M">AED 50m or more</option><option value="LT_50M">Below AED 50m</option></select><input name="asp_name" defaultValue={p?.asp_name||''} placeholder="Accredited Service Provider" className={field}/><input name="peppol_participant_id" defaultValue={p?.peppol_participant_id||''} placeholder="Peppol participant ID" className={field}/><input name="mandatory_go_live_date" type="date" defaultValue={p?.mandatory_go_live_date||''} className={field}/><input name="record_retention_years" type="number" min="5" defaultValue={p?.record_retention_years||5} className={field}/><button className="rounded-lg bg-[#31584A] px-4 py-2 text-sm text-white">Save profile</button></form>
  <form onSubmit={prepare} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Prepare structured eInvoice evidence</h2><p className="text-sm text-slate-500">Validates a posted sales invoice and snapshots structured data with a SHA-256 evidence hash.</p><select required name="invoice_id" className={field}><option value="">Select invoice</option>{invoices.map(x=><option key={x.id} value={x.id}>{x.invoice_number}</option>)}</select><select name="transaction_scope" className={field}><option>B2B</option><option>B2G</option><option>G2G</option><option>EXCLUDED</option></select><button className="rounded-lg bg-[#31584A] px-4 py-2 text-sm text-white">Validate and prepare</button><div className="rounded bg-amber-50 p-3 text-xs text-amber-800">PDFs and email are not UAE eInvoices. ASP exchange remains disabled until a real provider contract and credentials exist.</div></form></div>
  <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">eInvoice readiness register ({docs.length})</h2>{docs.map(x=><div key={x.id} className="border-b py-3 text-sm"><div className="flex justify-between"><b>{x.source_number}</b><span>{x.status}</span></div><p className="text-xs text-slate-500">{x.payload_version} · {x.transaction_scope} · Hash {String(x.payload_hash||'').slice(0,16)}…</p>{Array.isArray(x.validation_errors)&&x.validation_errors.length>0&&<ul className="mt-1 list-disc pl-5 text-xs text-red-700">{x.validation_errors.map((v:string)=><li key={v}>{v}</li>)}</ul>}</div>)}{!docs.length&&!busy&&<p className="py-4 text-sm text-slate-500">No structured eInvoice readiness payloads.</p>}</section>
  <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Compliance evidence ({evidenceRows.length})</h2><form onSubmit={save('/uae-compliance/evidence','Evidence record created.')} className="my-3 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><select name="evidence_type" className={field}><option>VAT_INVOICE</option><option>VAT_RETURN</option><option>CORPORATE_TAX</option><option>TRANSFER_PRICING</option><option>WPS</option></select><input required name="reference_number" placeholder="Evidence reference" className={field}/><button className="rounded bg-[#31584A] px-3 py-2 text-sm text-white">Add evidence</button></form>{evidenceRows.map(x=><div key={x.id} className="flex justify-between border-b py-2 text-sm"><span><b>{x.reference_number}</b> · {x.evidence_type} · {x.status}</span><span>{x.status==='DRAFT'&&<button onClick={()=>review(x.id,'REVIEWED')} className="text-blue-700">Review</button>}{x.status==='REVIEWED'&&<button onClick={()=>review(x.id,'APPROVED')} className="text-green-700">Approve</button>}</span></div>)}</section></main>;
}
