import { BadRequestException, Injectable } from '@nestjs/common';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

@Injectable()
export class PlantMaintenanceService {
  private readonly db: SupabaseClient = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_KEY!);
  async assets(tenantId: string) { const { data, error } = await this.db.from('plant_assets').select('*').eq('tenant_id', tenantId).order('asset_code'); if (error) throw new BadRequestException(error.message); return data || []; }
  async createAsset(tenantId: string, body: any) { const asset_code = String(body.asset_code || '').trim(); const asset_name = String(body.asset_name || '').trim(); if (!asset_code || !asset_name) throw new BadRequestException('Asset code and name are required.'); const { data, error } = await this.db.from('plant_assets').insert({ tenant_id: tenantId, asset_code, asset_name, asset_type: body.asset_type || null, location_name: body.location_name || null, criticality: body.criticality || 'MEDIUM', manufacturer: body.manufacturer || null, model_number: body.model_number || null, serial_number: body.serial_number || null, commissioned_on: body.commissioned_on || null }).select().single(); if (error) throw new BadRequestException(error.code === '23505' ? 'Asset code already exists.' : error.message); return data; }
  async workOrders(tenantId: string) { const { data, error } = await this.db.from('plant_maintenance_work_orders').select('*,asset:plant_assets(asset_code,asset_name,criticality,location_name)').eq('tenant_id', tenantId).order('created_at', { ascending: false }); if (error) throw new BadRequestException(error.message); return data || []; }
  async createWorkOrder(tenantId: string, userId: string, body: any) { const asset_id = String(body.asset_id || '').trim(); if (!asset_id || !body.work_type || !body.description) throw new BadRequestException('Asset, work type and description are required.'); const { data: asset } = await this.db.from('plant_assets').select('id').eq('tenant_id', tenantId).eq('id', asset_id).maybeSingle(); if (!asset) throw new BadRequestException('Plant asset not found.'); const { count } = await this.db.from('plant_maintenance_work_orders').select('*', { count: 'exact', head: true }).eq('tenant_id', tenantId); const work_order_number = `PM-${String((count || 0) + 1).padStart(6, '0')}`; const { data, error } = await this.db.from('plant_maintenance_work_orders').insert({ tenant_id: tenantId, work_order_number, asset_id, work_type: body.work_type, priority: body.priority || 'MEDIUM', planned_date: body.planned_date || null, reported_at: body.work_type === 'BREAKDOWN' ? new Date().toISOString() : null, description: String(body.description).trim(), created_by: userId }).select().single(); if (error) throw new BadRequestException(error.message); return data; }
  async updateWorkOrder(tenantId: string, id: string, body: any) { const status = String(body.status || '').toUpperCase(); if (!['OPEN','IN_PROGRESS','COMPLETED','CANCELLED'].includes(status)) throw new BadRequestException('Invalid work-order status.'); const patch:any={status,updated_at:new Date().toISOString()}; if(status==='IN_PROGRESS')patch.started_at=new Date().toISOString(); if(status==='COMPLETED'){patch.completed_at=new Date().toISOString();patch.downtime_minutes=Math.max(0,Number(body.downtime_minutes||0));patch.resolution_note=String(body.resolution_note||'').trim()||null;} const {data,error}=await this.db.from('plant_maintenance_work_orders').update(patch).eq('tenant_id',tenantId).eq('id',id).select().maybeSingle(); if(error||!data)throw new BadRequestException(error?.message||'Work order not found.');return data; }
}
