'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, FileSearch, RefreshCw, ShieldCheck } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

export default function DocumentIntelligencePage() {
  const [documents, setDocuments] = useState<any[]>([]); const [intakes, setIntakes] = useState<any[]>([]);
  const [documentId, setDocumentId] = useState(''); const [extractedJson, setExtractedJson] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<any>(null);
  const load = useCallback(async () => { try { const [docs, rows] = await Promise.all([apiClient.get<any[]>('/documents'), apiClient.get<any[]>('/intelligence/document-intakes')]); setDocuments(Array.isArray(docs) ? docs : []); setIntakes(Array.isArray(rows) ? rows : []); } catch (e: any) { setError(e?.message || 'Unable to load document intake.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const analyse = async (event: FormEvent) => { event.preventDefault(); if (!documentId) return; setBusy(true); setError(''); try { let extracted_data: any = undefined; if (extractedJson.trim()) { try { extracted_data = JSON.parse(extractedJson); } catch { throw new Error('Reviewed extracted data must be valid JSON.'); } } const response = await apiClient.post(`/intelligence/document-intakes/${documentId}/analyse`, extracted_data ? { extracted_data } : {}); setResult(response); await load(); } catch (e: any) { setError(e?.message || 'Unable to analyse document.'); } finally { setBusy(false); } };
  const approve = async (id: string) => { setBusy(true); setError(''); try { await apiClient.patch(`/intelligence/document-intakes/${id}/approve`, {}); await load(); } catch (e: any) { setError(e?.message || 'Unable to approve document intake.'); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-7xl space-y-4 p-4 text-[#2F241B]">
    <header className="border border-[#D8C8AA] bg-[#FBF7EF] p-5"><Link href="/dashboard/command-center" className="inline-flex items-center gap-1 text-xs font-semibold text-[#80613D]"><ArrowLeft className="h-3 w-3"/>Command Center</Link><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><FileSearch className="h-6 w-6"/>Document intelligence</h1><p className="mt-1 text-sm text-[#6F5A45]">Extract, classify and three-way match documents before any native transaction is prepared.</p></div><div className="flex gap-2"><Link href="/dashboard/documents" className="border border-[#65452B] px-3 py-2 text-sm font-semibold">Upload document</Link><button onClick={load} className="inline-flex items-center gap-2 bg-[#65452B] px-3 py-2 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4"/>Refresh</button></div></div></header>
    {error && <p className="border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={analyse} className="space-y-3 border border-[#E0D2B8] bg-white p-4"><h2 className="font-bold">Analyse existing document</h2><label className="block text-xs font-semibold">Document<select value={documentId} onChange={e=>setDocumentId(e.target.value)} className="mt-1 w-full border border-[#D8C8AA] p-2 text-sm"><option value="">Select document</option>{documents.map(doc=><option key={doc.id} value={doc.id}>{doc.document_number || doc.file_name || doc.title} — {doc.document_type || 'Document'}</option>)}</select></label><label className="block text-xs font-semibold">Reviewed extracted data (optional JSON)<textarea value={extractedJson} onChange={e=>setExtractedJson(e.target.value)} rows={10} placeholder='{"invoiceNumber":"INV-1001","poNumber":"PO-2026-001","vendor":"Supplier name","totalAmount":1000}' className="mt-1 w-full border border-[#D8C8AA] p-2 font-mono text-xs"/></label><p className="text-xs text-[#6F5A45]">Existing OCR/AI fields are used automatically. JSON is only needed when extraction is unavailable or needs reviewed correction.</p><button disabled={busy || !documentId} className="w-full bg-[#65452B] p-2 text-sm font-semibold text-white">{busy ? 'Analysing…' : 'Analyse and match'}</button></form>
      <div className="border border-[#E0D2B8] bg-white p-4"><h2 className="font-bold">Latest result</h2>{result ? <><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><div className="bg-[#FBF7EF] p-3"><span className="text-xs">Type</span><b className="block">{result.intake.document_type}</b></div><div className="bg-[#FBF7EF] p-3"><span className="text-xs">Status</span><b className="block">{result.intake.status}</b></div><div className="bg-[#FBF7EF] p-3"><span className="text-xs">GRNs</span><b className="block">{result.match.grn_count}</b></div></div><div className="mt-3 text-sm"><p><b>PO:</b> {result.match.purchase_order_number || 'Not matched'}</p><p><b>Supplier:</b> {result.match.vendor?.name || 'Not matched'}</p><p><b>Three-way match:</b> {result.match.three_way_match_ready ? 'Ready for independent approval' : 'Not ready'}</p></div><div className="mt-3">{(result.exceptions || []).map((item: any)=><p key={item.code} className="border-t py-2 text-xs text-red-800"><b>{item.code}</b> — {item.message}</p>)}</div><p className="mt-3 text-xs text-[#6F5A45]">{result.control}</p></> : <p className="mt-3 text-sm text-[#6F5A45]">Select an uploaded document to create a governed matching result.</p>}</div>
    </section>
    <section className="border border-[#E0D2B8] bg-white"><div className="flex items-center justify-between p-4"><div><h2 className="font-bold">Intake queue</h2><p className="text-xs text-[#6F5A45]">Validation does not post AP, inventory or GL.</p></div><ShieldCheck className="h-5 w-5 text-[#80613D]"/></div>{intakes.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-sm"><div><b>{row.document_type}</b><p className="text-xs text-[#6F5A45]">{row.match_result?.invoice_number || row.document_id} · {row.exceptions?.length || 0} exception(s)</p></div><div className="flex items-center gap-2"><span className="border border-[#D8C8AA] px-2 py-1 text-xs font-bold">{row.status}</span>{row.status === 'VALIDATED' && <button disabled={busy} onClick={()=>approve(row.id)} className="inline-flex items-center gap-1 bg-emerald-700 px-2 py-1 text-xs font-semibold text-white"><CheckCircle2 className="h-3 w-3"/>Independent approval</button>}</div></div>)}{!intakes.length && <p className="border-t p-8 text-center text-sm text-[#6F5A45]">No document intake has been analysed.</p>}</section>
  </main>;
}
