'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Bell, CheckCheck, RefreshCw } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

type Notification = { id: string; subject: string; message_preview?: string; delivery_status: string; created_at: string; route: string; stage: string; read: boolean; metadata?: { priority_score?: number; severity?: string } };

export default function NotificationsPage() {
  const [rows, setRows] = useState<Notification[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = useCallback(async () => { setError(''); try { setRows(await apiClient.get<Notification[]>('/intelligence/notifications?limit=100')); } catch (e: any) { setError(e?.message || 'Unable to load in-app notifications.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const markRead = async (row: Notification) => { setBusy(row.id); try { await apiClient.patch(`/intelligence/notifications/${row.id}/read`, {}); await load(); } catch (e: any) { setError(e?.message || 'Unable to mark notification read.'); } finally { setBusy(''); } };
  const unread = rows.filter((row) => !row.read).length;
  return <main className="mx-auto max-w-5xl space-y-4 p-4 text-[#2F241B]"><header className="border border-[#D8C8AA] bg-[#FBF7EF] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/dashboard/command-center" className="inline-flex items-center gap-1 text-xs font-semibold text-[#80613D]"><ArrowLeft className="h-3 w-3"/>Command Center</Link><h1 className="mt-2 flex items-center gap-2 text-2xl font-bold"><Bell className="h-6 w-6"/>Decision notifications</h1><p className="mt-1 text-sm text-[#6F5A45]">Only your assigned or role-visible exception reminders and escalations. This inbox never sends external messages.</p></div><button onClick={load} className="inline-flex items-center gap-2 bg-[#65452B] px-3 py-2 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4"/>Refresh</button></div></header>{error && <p className="border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<p className="text-sm font-semibold text-[#6F5A45]">{unread} unread · {rows.length} role-visible notification(s)</p><section className="border border-[#E8DCC4] bg-white">{rows.map((row) => <article key={row.id} className={`border-b border-[#F0E7D6] p-4 last:border-0 ${row.read ? '' : 'bg-[#FFFCF6]'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-3xl"><div className="flex gap-2 text-xs font-bold"><span className={row.stage === 'ESCALATION' ? 'text-red-700' : 'text-[#80613D]'}>{row.stage}</span><span>{row.metadata?.severity || 'MEDIUM'} · priority {row.metadata?.priority_score ?? '—'}</span></div><h2 className="mt-1 font-bold">{row.subject}</h2><p className="mt-1 text-sm text-[#6F5A45]">{row.message_preview}</p><p className="mt-2 text-xs text-[#7A6555]">{new Date(row.created_at).toLocaleString()}</p></div><div className="flex gap-2"><Link href={row.route} className="border border-[#C9B894] px-2 py-1 text-xs font-semibold">Open decision</Link>{!row.read && <button disabled={busy === row.id} onClick={() => markRead(row)} className="inline-flex items-center gap-1 border border-[#C9B894] px-2 py-1 text-xs font-semibold"><CheckCheck className="h-3 w-3"/>Mark read</button>}</div></div></article>)}{!rows.length && <p className="p-10 text-center text-sm text-[#6F5A45]">No role-visible exception notifications.</p>}</section></main>;
}
