'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Play, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

type ActionRequest={id:string;tool_code:string;insight_title?:string;status:string;risk:string;created_by:string;approved_by?:string;created_at:string;native_result?:{number?:string;route?:string};failure_reason?:string};
export default function GovernedActionsPage(){
 const[rows,setRows]=useState<ActionRequest[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{setError('');try{setRows(await apiClient.get<ActionRequest[]>('/intelligence/action-requests'))}catch(e:any){setError(e?.message||'Unable to load governed actions.')}},[]);useEffect(()=>{load()},[load]);
 const act=async(id:string,action:'approve'|'reject'|'execute')=>{setBusy(id+action);setError('');try{if(action==='execute')await apiClient.post(`/intelligence/action-requests/${id}/execute`,{});else await apiClient.patch(`/intelligence/action-requests/${id}/${action}`,action==='reject'?{reason:'Rejected after independent review'}:{});await load()}catch(e:any){setError(e?.message||`Unable to ${action} action.`)}finally{setBusy('')}};
 return <main className="mx-auto max-w-7xl space-y-4 p-4 text-[#2F241B]"><header className="border border-[#D8C8AA] bg-[#FBF7EF] p-5"><Link href="/dashboard/command-center" className="inline-flex items-center gap-1 text-xs font-semibold text-[#80613D]"><ArrowLeft className="h-3 w-3"/>Command Center</Link><div className="mt-2 flex items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="h-6 w-6"/>Governed native actions</h1><p className="mt-1 text-sm text-[#6F5A45]">High-risk actions require a different approver before the existing ERP service creates anything.</p></div><button onClick={load} className="inline-flex items-center gap-2 bg-[#65452B] px-3 py-2 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4"/>Refresh</button></div></header>{error&&<p className="border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<section className="overflow-auto border border-[#E0D2B8] bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#F5EDDF] text-xs uppercase"><tr><th className="p-3">Action</th><th>Source decision</th><th>Risk</th><th>Status</th><th>Created</th><th className="p-3">Controls</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-[#EEE3D0]"><td className="p-3 font-semibold">{row.tool_code.replaceAll('_',' ')}</td><td>{row.insight_title||'—'}</td><td>{row.risk}</td><td><span className="border border-[#D8C8AA] px-2 py-1 text-xs font-bold">{row.status}</span>{row.failure_reason&&<p className="mt-1 text-xs text-red-700">{row.failure_reason}</p>}</td><td>{new Date(row.created_at).toLocaleString()}</td><td className="p-3"><div className="flex gap-1">{row.status==='PENDING_APPROVAL'&&<><button disabled={!!busy} onClick={()=>act(row.id,'approve')} className="inline-flex items-center gap-1 bg-emerald-700 px-2 py-1 text-xs font-semibold text-white"><CheckCircle2 className="h-3 w-3"/>Approve</button><button disabled={!!busy} onClick={()=>act(row.id,'reject')} className="inline-flex items-center gap-1 border border-red-300 px-2 py-1 text-xs text-red-800"><XCircle className="h-3 w-3"/>Reject</button></>}{row.status==='APPROVED'&&<button disabled={!!busy} onClick={()=>act(row.id,'execute')} className="inline-flex items-center gap-1 bg-[#65452B] px-2 py-1 text-xs font-semibold text-white"><Play className="h-3 w-3"/>Execute</button>}{row.status==='EXECUTED'&&row.native_result?.route&&<Link href={row.native_result.route} className="text-xs font-semibold text-[#65452B]">Open {row.native_result.number||'record'} →</Link>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-8 text-center text-[#6F5A45]">No governed native action requests.</td></tr>}</tbody></table></section><p className="text-xs text-[#6F5A45]">The server rechecks tenant, permission, maker-checker state and idempotency during every approval and execution.</p></main>
}
