'use client';

import { useCallback, useEffect, useState } from 'react';
import { Banknote, Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

type InvoiceItem = { id:string; invoice_number:string; due_date?:string; balance_amount:number; days_overdue:number; priority:string; customer?:{customer_name?:string}|null };
type CollectionsData = { total_outstanding:number; overdue_amount:number; items:InvoiceItem[] };
type Suggestion = { id:string; confidence_score:number; suggested_amount:number; match_reasons:string[]; bank_transaction?:{reference_number?:string}|null; open_item?:{document_number:string;party?:{party_name?:string}|null}|null };
type ControlData = { metrics:{receivables:number;payables:number;overdue_receivables:number;immediately_addressable_cash:number;dso_days:number|null;dpo_days:number|null}; suggestions:Suggestion[]; methodology:string };
const money=(value:number)=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',maximumFractionDigits:0}).format(Number(value||0));

export default function Collections(){
  const [data,setData]=useState<CollectionsData|null>(null); const [control,setControl]=useState<ControlData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [saving,setSaving]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [collections,workingCapital]=await Promise.all([apiClient.get<CollectionsData>('/collections/worklist'),apiClient.get<ControlData>('/accounting/working-capital-control')]);setData(collections);setControl(workingCapital);setError('')}catch(e:any){setError(e?.message||'Unable to load collections control')}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const action=async(id:string,status:string)=>{const notes=window.prompt('Record collection follow-up notes');if(!notes?.trim())return;let promise_to_pay_date:string|undefined;if(status==='PROMISED'){promise_to_pay_date=window.prompt('Promise-to-pay date (YYYY-MM-DD)')||undefined;if(!promise_to_pay_date)return}setSaving(id);try{await apiClient.post(`/sales/invoices/${id}/collection-action`,{collection_status:status,notes,promise_to_pay_date});await load()}catch(e:any){setError(e?.message||'Unable to save follow-up')}finally{setSaving(null)}};
  const suggest=async()=>{setSaving('suggest');setMessage('');try{const result:any=await apiClient.post('/accounting/cash-application/suggest');setMessage(`${result.generated} exact-amount allocation candidate(s) evaluated. A different finance user must apply them.`);await load()}catch(e:any){setError(e?.message||'Unable to generate suggestions')}finally{setSaving(null)}};
  const review=async(id:string,decision:'apply'|'reject')=>{const note=window.prompt(decision==='apply'?'Independent review note':'Rejection reason');if(!note?.trim())return;setSaving(id);try{await apiClient.post(`/accounting/cash-application/${id}/${decision}`,{review_note:note});setMessage(decision==='apply'?'Cash applied and open item settled from the reconciled bank line.':'Suggestion rejected with evidence.');await load()}catch(e:any){setError(e?.message||'Unable to review suggestion')}finally{setSaving(null)}};
  const m=control?.metrics;
  return <div className="mx-auto max-w-7xl space-y-5 p-2 sm:p-4">
    <section className="rounded-2xl bg-gradient-to-r from-[#38485A] to-[#5B718A] p-5 text-white sm:p-7"><div className="flex flex-wrap justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-sm text-slate-100"><Banknote size={17}/> Evidence-linked cash control</div><h1 className="text-2xl font-bold">AR/AP Working Capital Control</h1><p className="mt-2 text-sm text-slate-100">Prioritise collections and independently apply reconciled bank lines to exact open items.</p></div><div className="flex gap-2"><button onClick={suggest} disabled={!!saving} className="inline-flex h-fit items-center gap-2 rounded-lg bg-emerald-500/90 px-3 py-2 text-sm font-semibold"><Sparkles size={16}/> Generate matches</button><button onClick={load} className="h-fit rounded-lg bg-white/15 px-3 py-2 text-sm font-semibold">{loading?<Loader2 size={16} className="animate-spin"/>:<RefreshCw size={16}/>}</button></div></div></section>
    {error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
    <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Card label="Receivables" value={money(m?.receivables||data?.total_outstanding||0)}/><Card label="Overdue AR" value={money(m?.overdue_receivables||data?.overdue_amount||0)}/><Card label="Payables" value={money(m?.payables||0)}/><Card label="Addressable cash" value={money(m?.immediately_addressable_cash||0)}/><Card label="DSO" value={m?.dso_days==null?'N/A':`${m.dso_days} days`}/><Card label="DPO" value={m?.dpo_days==null?'N/A':`${m.dpo_days} days`}/></section>
    <div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800">{control?.methodology||'Working-capital metrics are calculated from finance open items.'}</div>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><h2 className="font-semibold">Bank-to-invoice suggestions</h2><p className="mt-1 text-sm text-slate-500">Only posted, reconciled bank lines with an exact outstanding amount qualify. The generator cannot approve its own suggestions.</p>{control?.suggestions.length?<div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Bank reference</th><th className="p-2">Open item</th><th className="p-2">Party</th><th className="p-2 text-right">Amount</th><th className="p-2">Evidence</th><th className="p-2"></th></tr></thead><tbody>{control.suggestions.map(x=><tr key={x.id} className="border-b"><td className="p-2 font-medium">{x.bank_transaction?.reference_number||'Bank line'}</td><td className="p-2">{x.open_item?.document_number}</td><td className="p-2">{x.open_item?.party?.party_name||'Party'}</td><td className="p-2 text-right">{money(x.suggested_amount)}</td><td className="p-2"><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-700">{x.confidence_score}%</span><span className="ml-2 text-xs text-slate-500">{x.match_reasons.join(' + ')}</span></td><td className="p-2 text-right"><button disabled={saving===x.id} onClick={()=>review(x.id,'apply')} className="mr-1 rounded border border-emerald-200 px-2 py-1 text-xs font-semibold text-emerald-700">Apply</button><button disabled={saving===x.id} onClick={()=>review(x.id,'reject')} className="rounded border border-slate-200 px-2 py-1 text-xs font-semibold text-slate-600">Reject</button></td></tr>)}</tbody></table></div>:<div className="mt-3 rounded bg-slate-50 p-5 text-sm text-slate-500">No pending exact-match bank allocations.</div>}</section>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><h2 className="font-semibold">Collection priority queue</h2>{loading?<div className="py-8 text-sm text-slate-500">Loading…</div>:data?.items.length?<div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Invoice</th><th className="p-2">Customer</th><th className="p-2 text-right">Balance</th><th className="p-2 text-right">Days overdue</th><th className="p-2">Action</th></tr></thead><tbody>{data.items.map(x=><tr key={x.id} className="border-b"><td className="p-2 font-medium">{x.invoice_number}</td><td className="p-2">{x.customer?.customer_name||'Customer'}</td><td className="p-2 text-right">{money(x.balance_amount)}</td><td className="p-2 text-right"><span className="font-semibold text-rose-700">{x.days_overdue}</span></td><td className="p-2"><button disabled={saving===x.id} onClick={()=>action(x.id,'CONTACTED')} className="mr-1 rounded border border-blue-200 px-2 py-1 text-xs font-semibold text-blue-700">Contact</button><button disabled={saving===x.id} onClick={()=>action(x.id,'PROMISED')} className="mr-1 rounded border border-emerald-200 px-2 py-1 text-xs font-semibold text-emerald-700">Promise</button><button disabled={saving===x.id} onClick={()=>action(x.id,'ESCALATED')} className="mr-2 rounded border border-rose-200 px-2 py-1 text-xs font-semibold text-rose-700">Escalate</button><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{x.priority}</span></td></tr>)}</tbody></table></div>:<div className="mt-3 rounded bg-slate-50 p-6 text-sm text-slate-500">No unpaid invoices in the worklist.</div>}</section>
  </div>;
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div>}
