'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { GitPullRequestArrow, RefreshCw } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

const field = 'w-full rounded-lg border border-slate-300 px-3 py-2 text-sm';
const money = (value: any) => new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED', maximumFractionDigits: 0 }).format(Number(value || 0));
const number = (value: any) => new Intl.NumberFormat('en-AE', { maximumFractionDigits: 1 }).format(Number(value || 0));

export default function EngineeringChanges() {
  const [data, setData] = useState<any>({ kpis: {}, changes: [], items: [], boms: [] });
  const [selected, setSelected] = useState('');
  const [busy, setBusy] = useState(true);
  const [message, setMessage] = useState('');
  const load = useCallback(async () => { setBusy(true); try { setData(await apiClient.get('/engineering-changes/dashboard')); setMessage(''); } catch (error: any) { setMessage(error?.message || 'Unable to load engineering changes.'); } finally { setBusy(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const post = (url: string, success: string) => async (event?: FormEvent<HTMLFormElement>) => { event?.preventDefault(); try { const body = event ? Object.fromEntries(new FormData(event.currentTarget)) : {}; await apiClient.post(url, body); if (event) event.currentTarget.reset(); setMessage(success); await load(); } catch (error: any) { setMessage(error?.message || 'Unable to save.'); } };
  const patch = async (url: string, body: any, success: string) => { try { await apiClient.patch(url, body); setMessage(success); await load(); } catch (error: any) { setMessage(error?.message || 'Unable to progress change.'); } };
  const approve = (id: string) => { const approval_note = prompt('Approval rationale / conditions'); if (approval_note) patch(`/engineering-changes/${id}/approve`, { approval_note }, 'Engineering change approved.'); };
  const implement = (id: string) => { const implementation_evidence = prompt('Implementation evidence reference'); if (implementation_evidence) patch(`/engineering-changes/${id}/implement`, { implementation_evidence }, 'Implementation recorded.'); };
  const verify = (id: string) => { const realized_avoidance = prompt('Verified avoided cost (AED)', '0'), verification_evidence = prompt('Independent verification evidence'); if (realized_avoidance !== null && verification_evidence) patch(`/engineering-changes/${id}/verify`, { realized_avoidance, verification_evidence }, 'Change and ROI independently verified.'); };
  const active = data.changes.find((change: any) => change.id === selected);

  return <main className="mx-auto max-w-7xl space-y-5 p-4">
    <header className="rounded-2xl bg-gradient-to-r from-[#203A43] to-[#2C5364] p-6 text-white"><div className="flex justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-cyan-100"><GitPullRequestArrow size={18}/>Engineering digital thread to verified ROI</div><h1 className="mt-2 text-2xl font-bold">Engineering Change & Obsolescence Control</h1><p className="mt-1 text-sm text-cyan-100">Assess where-used and stock exposure before approval. Released BOMs and item masters are never changed automatically.</p></div><button onClick={load} aria-label="Refresh"><RefreshCw className={busy ? 'animate-spin' : ''}/></button></div></header>
    {message && <p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><K label="Open changes" value={number(data.kpis.open_changes)}/><K label="High risk" value={number(data.kpis.high_risk)}/><K label="Stock exposure" value={money(data.kpis.inventory_exposure)}/><K label="Avoidance pipeline" value={money(data.kpis.avoidance_pipeline)}/><K label="Verified avoidance" value={money(data.kpis.verified_avoidance)}/><K label="Avg cycle" value={`${number(data.kpis.average_cycle_days)} days`}/></section>
    <div className="grid gap-5 lg:grid-cols-2">
      <form onSubmit={post('/engineering-changes', 'Engineering change created. Run impact assessment next.')} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Create ECR / ECO</h2><input required name="title" className={field} placeholder="Change title"/><div className="grid grid-cols-2 gap-2"><select name="change_type" className={field}><option>DESIGN</option><option>MATERIAL</option><option>PROCESS</option><option>SUPPLIER</option><option>QUALITY</option><option>COMPLIANCE</option><option>COST</option></select><select name="priority" className={field}><option>MEDIUM</option><option>LOW</option><option>HIGH</option><option>CRITICAL</option></select></div><select name="affected_item_id" className={field}><option value="">Affected item</option>{data.items.map((item: any) => <option key={item.id} value={item.id}>{item.code} - {item.name}</option>)}</select><select name="affected_bom_id" className={field}><option value="">Affected BOM (optional)</option>{data.boms.map((bom: any) => <option key={bom.id} value={bom.id}>{bom.item?.code || 'BOM'} v{bom.version}</option>)}</select><textarea required name="reason" className={field} placeholder="Problem / reason"/><textarea name="proposed_solution" className={field} placeholder="Proposed technical solution"/><div className="grid grid-cols-2 gap-2"><input required name="risk_score" type="number" min="1" max="25" defaultValue="5" className={field} placeholder="Risk score 1-25"/><input name="effective_date" type="date" className={field}/><input name="estimated_change_cost" type="number" min="0" step="0.01" className={field} placeholder="Change cost AED"/><input name="estimated_avoidance" type="number" min="0" step="0.01" className={field} placeholder="Expected avoided cost AED"/></div><button className="rounded bg-[#203A43] px-4 py-2 text-sm text-white">Create change</button></form>
      <form onSubmit={selected ? post(`/engineering-changes/${selected}/impacts`, 'Manual impact added.') : (event) => event.preventDefault()} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Add business impact</h2><p className="text-xs text-slate-500">Add work-order, customer, quality or regulatory impacts that cannot be inferred from stock and BOM records.</p><select required value={selected} onChange={(event) => setSelected(event.target.value)} className={field}><option value="">Select draft / assessed change</option>{data.changes.filter((change: any) => ['DRAFT','ASSESSED'].includes(change.status)).map((change: any) => <option key={change.id} value={change.id}>{change.change_number} - {change.title}</option>)}</select><select name="impact_type" className={field}><option>WORK_ORDER</option><option>SUPPLIER</option><option>CUSTOMER</option><option>QUALITY</option><option>COMPLIANCE</option><option>OTHER</option></select><input required name="reference_label" className={field} placeholder="Affected reference / obligation"/><div className="grid grid-cols-2 gap-2"><input name="quantity_at_risk" type="number" min="0" step="0.0001" className={field} placeholder="Quantity at risk"/><input name="unit_cost" type="number" min="0" step="0.0001" className={field} placeholder="Unit cost AED"/></div><select name="disposition" className={field}><option>REVIEW</option><option>USE_AS_IS</option><option>REWORK</option><option>RETURN</option><option>SCRAP</option><option>PHASE_OUT</option><option>NOT_APPLICABLE</option></select><textarea name="notes" className={field} placeholder="Impact and mitigation notes"/><button disabled={!selected} className="rounded bg-[#203A43] px-4 py-2 text-sm text-white disabled:opacity-40">Add impact</button>{active && <p className="text-xs text-slate-500">Selected exposure: {money(active.exposure_value)} across {active.impacts.length} impact records.</p>}</form>
    </div>
    <section className="rounded-xl border bg-white p-4"><div className="mb-3"><h2 className="font-semibold">Controlled change portfolio</h2><p className="text-xs text-slate-500">Automatic assessment uses live on-hand inventory and BOM where-used records.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Change</th><th className="p-2">Item / impact</th><th className="p-2 text-right">Risk</th><th className="p-2 text-right">Exposure</th><th className="p-2 text-right">ROI</th><th className="p-2">Status / action</th></tr></thead><tbody>{data.changes.map((change: any) => <tr key={change.id} className="border-b align-top"><td className="p-2"><b>{change.change_number}</b><span className="block">{change.title}</span><small className="text-slate-500">{change.change_type} · {change.priority}</small></td><td className="p-2">{change.item ? `${change.item.code} - ${change.item.name}` : 'BOM-level change'}<small className="block text-slate-500">{change.impacts.length} impacts · {change.where_used_count} BOM uses</small></td><td className={`p-2 text-right font-semibold ${change.risk_score >= 15 ? 'text-red-700' : ''}`}>{change.risk_score}/25</td><td className="p-2 text-right">{money(change.exposure_value)}</td><td className="p-2 text-right"><span className="block">Target {money(change.estimated_avoidance)}</span>{change.status === 'VERIFIED' && <b className="text-green-700">Verified {money(change.realized_avoidance)}</b>}</td><td className="p-2"><span className="mb-2 inline-block rounded bg-slate-100 px-2 py-1 text-xs font-semibold">{change.status}</span><div className="flex flex-wrap gap-1">{['DRAFT','ASSESSED'].includes(change.status) && <button onClick={() => post(`/engineering-changes/${change.id}/assess`, 'Impact assessment refreshed.')()} className="rounded border px-2 py-1 text-xs">Assess</button>}{change.status === 'ASSESSED' && <button onClick={() => patch(`/engineering-changes/${change.id}/submit`, {}, 'Submitted for independent approval.')} className="rounded border px-2 py-1 text-xs">Submit</button>}{change.status === 'SUBMITTED' && <button onClick={() => approve(change.id)} className="rounded border px-2 py-1 text-xs">Approve</button>}{change.status === 'APPROVED' && <button onClick={() => implement(change.id)} className="rounded border px-2 py-1 text-xs">Implemented</button>}{change.status === 'IMPLEMENTED' && <button onClick={() => verify(change.id)} className="rounded border px-2 py-1 text-xs">Verify ROI</button>}</div></td></tr>)}</tbody></table>{!busy && !data.changes.length && <p className="p-8 text-center text-sm text-slate-500">No engineering changes yet.</p>}</div></section>
  </main>;
}

function K({ label, value }: { label: string; value: any }) { return <div className="rounded-xl border bg-white p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-lg font-bold">{value}</div></div>; }
