'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { apiClient } from '../../../../../lib/api-client';
import { getTenantProfile } from '@/lib/profile-branding';
import { Activity, ExternalLink, RefreshCw, ShieldCheck } from 'lucide-react';

type Connection = { id: string; status: string; created_by?: string | null; configured_by?: string | null; updated_at?: string; connector_code: string };
type Event = { connection_id: string; status: string; occurred_at: string; processed_at?: string | null; event_type: string; attempt_count?: number };
export default function IntegrationHubPage() {
  const [data, setData] = useState<any>({ catalog: [], events: [] });
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState('');
  const [loadError, setLoadError] = useState('');
  const profile = getTenantProfile();
  const load = useCallback(async () => { setLoadError(''); try { setData(await apiClient.get('/integration-hub/dashboard')); } catch (error: any) { setLoadError(error?.message || 'Unable to load Integration Hub.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const events = Array.isArray(data.events) ? data.events as Event[] : [];
  const latestByConnection = useMemo(() => { const m = new Map<string, Event>(); for (const event of events.filter((row) => row.status === 'DELIVERED')) { const old = m.get(String(event.connection_id)); if (!old || String(event.processed_at || event.occurred_at) > String(old.processed_at || old.occurred_at)) m.set(String(event.connection_id), event); } return m; }, [events]);
  const save = async (code: string) => { setBusy(code); setMessage(''); try { await apiClient.post('/integration-hub/connections', { connector_code: code, status: 'TESTING', configuration: { mode: 'TEST' } }); setMessage('Test configuration saved. Use only a vault reference for any credential; secrets are never returned after save.'); await load(); } catch (error: any) { setMessage(error?.message || 'Unable to save test configuration.'); } finally { setBusy(''); } };
  const test = async (id: string) => { setBusy(id); setMessage(''); try { await apiClient.post(`/integration-hub/connections/${id}/test`, {}); setMessage('Safe test event recorded in the ledger. No external service was called.'); await load(); } catch (error: any) { setMessage(error?.message || 'Unable to record the safe test event.'); } finally { setBusy(''); } };
  const regional = data.market_profile === 'EGYPT' ? 'Egypt profile: shared connectors only.' : data.market_profile === 'UAE' ? 'UAE connector catalogue.' : data.market_profile === 'INDIA' ? 'India connector catalogue.' : 'Shared connector catalogue.';
  return <main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Features & Automation</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Integration Hub</h1><p className="mt-2 text-sm text-slate-600">{regional} Profile: {profile}. Connector status and test activity are tenant-scoped.</p></div><button onClick={() => void load()} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-slate-300 px-3 text-sm font-semibold"><RefreshCw size={15}/>Refresh</button></header>
    <section className="flex items-start gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><p>Test events are recorded locally in the connector ledger and do not deliver external messages. Connection credentials are never displayed after saving. WhatsApp has its own provider controls.</p></section>
    {loadError && <p role="alert" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{loadError}</p>}{message && <p role="status" className="rounded-lg border border-slate-200 bg-white p-3 text-sm text-slate-700">{message}</p>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(data.catalog || []).map((item: any) => { const connection = item.connection as Connection | null; const latest = connection ? latestByConnection.get(connection.id) : undefined; const connected = String(connection?.status || '').toUpperCase() === 'ACTIVE'; return <article key={item.connector_code} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{item.market_profile}</p><div className="mt-1 flex items-start justify-between gap-3"><h2 className="font-semibold text-slate-900">{item.connector_name}</h2><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${connected ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-700'}`}>{connected ? 'Connected' : connection ? connection.status : 'Not connected'}</span></div><dl className="mt-4 space-y-2 text-xs"><div className="flex justify-between gap-3"><dt className="text-slate-500">Last successful activity</dt><dd className="text-right font-medium">{latest?.status === 'DELIVERED' ? new Date(latest.processed_at || latest.occurred_at).toLocaleString() : 'None recorded'}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Configured by</dt><dd className="max-w-40 break-all text-right font-medium">{connection?.configured_by || 'Not configured'}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{item.connector_code === 'WHATSAPP' ? <Link href="/dashboard/settings/whatsapp" className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-slate-900 px-3 text-sm font-semibold text-white">Manage WhatsApp <ExternalLink size={14}/></Link> : !connection ? <button disabled={!!busy} onClick={() => void save(item.connector_code)} className="min-h-10 rounded-lg border border-slate-300 px-3 text-sm font-semibold disabled:opacity-50">Add test configuration</button> : <button disabled={!!busy || connection.status !== 'TESTING'} onClick={() => void test(connection.id)} className="min-h-10 rounded-lg border border-slate-300 px-3 text-sm font-semibold disabled:opacity-50">Record safe test event</button>}</div><p className="mt-3 text-xs text-slate-500">Connection tests are informational ledger entries; live connectivity checks are not implemented for this provider.</p></article>; })}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Activity size={17}/><h2 className="font-semibold text-slate-900">Recent connector activity</h2></div>{events.length ? <div className="mt-3 divide-y divide-slate-100">{events.map((event: Event, index: number) => <div key={`${event.connection_id}-${event.occurred_at}-${index}`} className="flex flex-col gap-1 py-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span><b>{event.event_type}</b> · {event.status}</span><span className="text-xs text-slate-500">{new Date(event.processed_at || event.occurred_at).toLocaleString()} · {event.attempt_count || 0} attempts</span></div>)}</div> : <p className="py-4 text-sm text-slate-500">No connector activity has been recorded.</p>}</section></main>;
}
