-- Add payment tracking columns to grns table
ALTER TABLE grns ADD COLUMN IF NOT EXISTS paid_amount DECIMAL(15,2) DEFAULT 0;
ALTER TABLE grns ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) DEFAULT 'UNPAID';
ALTER TABLE grns ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
ALTER TABLE grns ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(200);
ALTER TABLE grns ADD COLUMN IF NOT EXISTS payment_date DATE;
ALTER TABLE grns ADD COLUMN IF NOT EXISTS payment_notes TEXT;
ALTER TABLE grns ADD COLUMN IF NOT EXISTS tds_amount DECIMAL(15,2) DEFAULT 0;
ALTER TABLE grns ADD COLUMN IF NOT EXISTS short_payment_amount DECIMAL(15,2) DEFAULT 0;
