'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';
const field = 'w-full rounded-lg border border-slate-300 px-3 py-2 text-sm';
const money = (v: any) => new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED', maximumFractionDigits: 0 }).format(Number(v || 0));
const num = (v: any) => new Intl.NumberFormat('en-AE', { maximumFractionDigits: 1 }).format(Number(v || 0));

export default function CapaControl() {
  const [data, setData] = useState<any>({ kpis: {}, cases: [], ncrs: [], vendors: [] }), [selected, setSelected] = useState(''), [busy, setBusy] = useState(true), [message, setMessage] = useState('');
  const load = useCallback(async () => { setBusy(true); try { setData(await apiClient.get('/quality-capa/dashboard')); setMessage(''); } catch (e: any) { setMessage(e?.message || 'Unable to load CAPA control.'); } finally { setBusy(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const post = (url: string, ok: string) => async (event?: FormEvent<HTMLFormElement>) => { event?.preventDefault(); try { await apiClient.post(url, event ? Object.fromEntries(new FormData(event.currentTarget)) : {}); event?.currentTarget.reset(); setMessage(ok); await load(); } catch (e: any) { setMessage(e?.message || 'Unable to save.'); } };
  const patch = async (url: string, body: any, ok: string) => { try { await apiClient.patch(url, body); setMessage(ok); await load(); } catch (e: any) { setMessage(e?.message || 'Unable to progress CAPA.'); } };
  const investigate = (id: string) => { const root_cause_method = prompt('Method: 5_WHY, FISHBONE, 8D, FAULT_TREE or OTHER', '5_WHY'), root_cause = prompt('Documented root cause'); if (root_cause_method && root_cause) patch(`/quality-capa/${id}/investigate`, { root_cause_method, root_cause }, 'Root-cause investigation recorded.'); };
  const approve = (id: string) => { const approval_note = prompt('Independent approval rationale'); if (approval_note) patch(`/quality-capa/${id}/approve`, { approval_note }, 'CAPA approved.'); };
  const complete = (id: string) => { const completion_evidence = prompt('Action completion evidence'); if (completion_evidence) patch(`/quality-capa/actions/${id}/complete`, { completion_evidence }, 'Action completion recorded.'); };
  const verify = (c: any) => { const outcome = prompt('Outcome: EFFECTIVE, PARTIAL or INEFFECTIVE', 'EFFECTIVE'), effectiveness_result = prompt('Effectiveness result'), verification_evidence = prompt('Independent verification evidence'), realized_annual_avoidance = prompt('Verified annual avoided cost (AED)', '0'), supplier_recovered_amount = prompt(`Supplier recovered amount (max ${c.supplier_claim_amount || 0})`, '0'); if (outcome && effectiveness_result && verification_evidence && realized_annual_avoidance !== null && supplier_recovered_amount !== null) patch(`/quality-capa/${c.id}/verify`, { outcome, effectiveness_result, verification_evidence, realized_annual_avoidance, supplier_recovered_amount }, 'CAPA effectiveness and ROI verified.'); };
  const active = data.cases.find((c: any) => c.id === selected);
  return <main className="mx-auto max-w-7xl space-y-5 p-4">
    <header className="rounded-2xl bg-gradient-to-r from-[#263238] to-[#00695C] p-6 text-white"><div className="flex justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-emerald-100"><ShieldCheck size={18}/>ISO-style prevention to verified recovery</div><h1 className="mt-2 text-2xl font-bold">CAPA & Supplier Recovery Control</h1><p className="mt-1 text-sm text-emerald-100">Root cause, SCAR deadlines, evidence and independent effectiveness checks. Linked NCRs are never silently closed.</p></div><button onClick={load}><RefreshCw className={busy ? 'animate-spin' : ''}/></button></div></header>
    {message && <p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><K l="Open CAPAs" v={num(data.kpis.open_capas)}/><K l="Overdue actions" v={num(data.kpis.overdue_actions)}/><K l="Failure cost" v={money(data.kpis.failure_cost)}/><K l="Recovery pipeline" v={money(data.kpis.recovery_pipeline)}/><K l="Supplier recovered" v={money(data.kpis.supplier_recovered)}/><K l="Verified avoidance" v={money(data.kpis.verified_avoidance)}/></section>
    <div className="grid gap-5 lg:grid-cols-2">
      <form onSubmit={post('/quality-capa', 'CAPA opened. Investigate root cause next.')} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Open CAPA / SCAR</h2><input required name="title" className={field} placeholder="CAPA title"/><div className="grid grid-cols-2 gap-2"><select name="source" className={field}><option>INTERNAL</option><option>SUPPLIER</option><option>CUSTOMER</option><option>AUDIT</option><option>REGULATORY</option></select><select name="severity" className={field}><option>MEDIUM</option><option>LOW</option><option>HIGH</option><option>CRITICAL</option></select></div><select name="ncr_id" className={field}><option value="">Linked NCR (optional)</option>{data.ncrs.map((n: any) => <option key={n.id} value={n.id}>{n.ncr_number} - {n.description}</option>)}</select><select name="vendor_id" className={field}><option value="">Supplier (required for supplier source)</option>{data.vendors.map((v: any) => <option key={v.id} value={v.id}>{v.code} - {v.name}</option>)}</select><textarea required name="problem_statement" className={field} placeholder="Evidence-based problem statement"/><textarea required name="immediate_containment" className={field} placeholder="Immediate containment"/><input required name="due_date" type="date" className={field}/><div className="grid grid-cols-2 gap-2"><input name="failure_cost" type="number" min="0" step="0.01" className={field} placeholder="Failure cost AED"/><input name="estimated_annual_avoidance" type="number" min="0" step="0.01" className={field} placeholder="Annual avoidance AED"/><input name="supplier_claim_amount" type="number" min="0" step="0.01" className={field} placeholder="Supplier claim AED"/></div><button className="rounded bg-[#00695C] px-4 py-2 text-sm text-white">Open CAPA</button></form>
      <form onSubmit={selected ? post(`/quality-capa/${selected}/actions`, 'CAPA action added.') : e => e.preventDefault()} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Corrective / preventive action</h2><select required value={selected} onChange={e => setSelected(e.target.value)} className={field}><option value="">Select open / investigated CAPA</option>{data.cases.filter((c: any) => ['OPEN','INVESTIGATED'].includes(c.status)).map((c: any) => <option key={c.id} value={c.id}>{c.capa_number} - {c.title}</option>)}</select><select name="action_type" className={field}><option>CORRECTIVE</option><option>PREVENTIVE</option><option>CONTAINMENT</option><option>SCAR</option></select><textarea required name="action_description" className={field} placeholder="Specific action and expected outcome"/><input required name="due_date" type="date" className={field}/><button disabled={!selected} className="rounded bg-[#00695C] px-4 py-2 text-sm text-white disabled:opacity-40">Add action</button>{active && <p className="text-xs text-slate-500">{active.actions.length} action(s); target avoidance {money(active.estimated_annual_avoidance)}.</p>}</form>
    </div>
    <section className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">CAPA effectiveness portfolio</h2><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Case</th><th className="p-2">Source</th><th className="p-2">Actions</th><th className="p-2 text-right">Cost / recovery</th><th className="p-2 text-right">Avoidance</th><th className="p-2">Status / action</th></tr></thead><tbody>{data.cases.map((c: any) => <tr key={c.id} className="border-b align-top"><td className="p-2"><b>{c.capa_number}</b><span className="block">{c.title}</span><small className={c.overdue ? 'text-red-700' : 'text-slate-500'}>{c.severity} · due {c.due_date}{c.overdue ? ' · OVERDUE' : ''}</small></td><td className="p-2">{c.source}<small className="block text-slate-500">{c.vendor?.name || 'Internal / customer'}</small></td><td className="p-2">{c.actions.filter((a: any) => a.status === 'COMPLETED').length}/{c.actions.length} complete<div className="mt-1 space-y-1">{c.status === 'APPROVED' && c.actions.filter((a: any) => a.status === 'OPEN').map((a: any) => <button key={a.id} onClick={() => complete(a.id)} className="block rounded border px-2 py-1 text-xs">Complete {a.action_type}</button>)}</div></td><td className="p-2 text-right"><span className="block">Failure {money(c.failure_cost)}</span><small>Claim {money(c.supplier_claim_amount)} · recovered {money(c.supplier_recovered_amount)}</small></td><td className="p-2 text-right"><span className="block">Target {money(c.estimated_annual_avoidance)}</span>{['EFFECTIVE','PARTIAL','INEFFECTIVE'].includes(c.status) && <b className="text-green-700">Verified {money(c.realized_annual_avoidance)}</b>}</td><td className="p-2"><span className="mb-2 inline-block rounded bg-slate-100 px-2 py-1 text-xs font-semibold">{c.status}</span><div className="flex flex-wrap gap-1">{c.status === 'OPEN' && <button onClick={() => investigate(c.id)} className="rounded border px-2 py-1 text-xs">Investigate</button>}{c.status === 'INVESTIGATED' && <button onClick={() => patch(`/quality-capa/${c.id}/submit`, {}, 'CAPA submitted.')} className="rounded border px-2 py-1 text-xs">Submit</button>}{c.status === 'SUBMITTED' && <button onClick={() => approve(c.id)} className="rounded border px-2 py-1 text-xs">Approve</button>}{c.status === 'APPROVED' && c.actions.length > 0 && c.actions.every((a: any) => a.status === 'COMPLETED') && <button onClick={() => verify(c)} className="rounded border px-2 py-1 text-xs">Verify effectiveness</button>}</div></td></tr>)}</tbody></table>{!busy && !data.cases.length && <p className="p-8 text-center text-sm text-slate-500">No CAPA cases yet.</p>}</div></section>
  </main>;
}
function K({ l, v }: { l: string; v: any }) { return <div className="rounded-xl border bg-white p-3"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-lg font-bold">{v}</div></div>; }
