"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { apiClient } from "../../../../../lib/api-client";

type Batch = { id: string; batch_number?: string; original_filename: string; status: string; instruction: string; column_mappings: any[]; metadata: any; audit_log?:any[]; preview_checksum?: string; approved_by?: string };
type Row = { id: string; row_reference: string; sheet_name: string; source_row: number; target_entity: string; mapped_values: Record<string, any>; corrections: Record<string, any>; decision: string; validation: any[]; match_candidates: any[]; created_table?:string;created_entity_id?:string;user_decision?: string };

export default function SmartImportReviewPage() {
  const [id,setId]=useState<string|null>(null);
  const [batch,setBatch]=useState<Batch|null>(null); const [rows,setRows]=useState<Row[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=async()=>{if(!id)return;try{const data=await apiClient.get<any>(`/smart-imports/${encodeURIComponent(id)}`);setBatch(data.batch);setRows(data.rows||[]);}catch(e:any){setError(e.message||"Could not load this import.");}};
  useEffect(()=>{setId(new URLSearchParams(window.location.search).get("batch"));},[]);
  useEffect(()=>{if(id)void load();},[id]);
  const act=async(path:string,body?:any)=>{if(!id)return;setBusy(true);setError("");try{await apiClient.post(`/smart-imports/${encodeURIComponent(id)}/${path}`,body);await load();}catch(e:any){setError(e.message||"The action could not be completed.");}finally{setBusy(false);}};
  const saveCorrection=async(row:Row,field:string,value:string)=>{setBusy(true);try{await apiClient.patch(`/smart-imports/${encodeURIComponent(id!)}/corrections`,{corrections:[{rowReference:row.row_reference,values:{[field]:value}}]});await load();}catch(e:any){setError(e.message||"Correction could not be saved.");}finally{setBusy(false);}};
  const chooseMatch=async(row:Row,candidate:any)=>{setBusy(true);try{await apiClient.patch(`/smart-imports/${encodeURIComponent(id!)}/decisions`,{decisions:[{rowReference:row.row_reference,decision:"USE_EXISTING",matchId:candidate.id}]});await load();}catch(e:any){setError(e.message||"Match choice could not be saved.");}finally{setBusy(false);}};
  const saveMappings=async()=>{if(!id||!batch)return;setBusy(true);try{await apiClient.patch(`/smart-imports/${encodeURIComponent(id)}/mappings`,{mappings:batch.column_mappings});await load();}catch(e:any){setError(e.message||"Mappings could not be saved.");}finally{setBusy(false);}};
  const uploadMissing=async(file:File)=>{if(!id)return;setBusy(true);try{const form=new FormData();form.append("file",file);await apiClient.postForm(`/smart-imports/${encodeURIComponent(id)}/missing-data`,form);await load();}catch(e:any){setError(e.message||"Completed missing-data template could not be merged.");}finally{setBusy(false);}};
  const downloadMissing=async()=>{if(!id)return;setBusy(true);try{const blob=await apiClient.postBlob(`/smart-imports/${encodeURIComponent(id)}/missing-template`,{});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="smart-import-missing-data.xlsx";a.click();URL.revokeObjectURL(url);}catch(e:any){setError(e.message||"Template download failed.");}finally{setBusy(false);}};
  if(!id)return <main className="mx-auto max-w-5xl p-8">Select a Smart Import batch from Ask Mizantra.</main>;
  if(!batch)return <main className="mx-auto max-w-5xl p-8">{error||"Loading import preview…"}</main>;
  const summary=batch.metadata?.previewSummary||{};
  return <main className="mx-auto max-w-6xl space-y-6 p-6">
    <div className="flex items-start justify-between gap-4"><div><Link href="/dashboard/active-planner" className="text-sm underline">Ask Mizantra</Link><h1 className="mt-2 text-2xl font-semibold">Smart Import review</h1><p className="text-sm text-slate-600">{batch.batch_number||batch.id} · {batch.original_filename} · {batch.status}</p></div><button disabled={busy} onClick={()=>void act("cancel")} className="rounded border px-3 py-2">Cancel batch</button></div>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}
    <section className="rounded border p-4"><h2 className="font-semibold">Instruction</h2><p className="mt-1">{batch.instruction}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm md:grid-cols-4">{[["Rows",summary.rows??rows.length],["Safe new records",summary.created??0],["Need data",summary.missingData??0],["Possible matches",summary.possibleMatches??0]].map(([k,v])=><div className="rounded bg-slate-50 p-3" key={String(k)}>{k}: <b>{String(v)}</b></div>)}</div><p className="mt-3 text-sm font-medium">Nothing is imported until an authorized admin approves this exact preview.</p></section>
    <section className="rounded border p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Detected columns</h2><button disabled={busy} onClick={()=>void saveMappings()} className="rounded border px-3 py-1">Save mappings and refresh preview</button></div><div className="mt-2 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Sheet</th><th>Source column</th><th>Target</th><th>Confidence</th><th>Reason</th></tr></thead><tbody>{(batch.column_mappings||[]).map((m:any,i:number)=><tr key={`${m.sheet}-${m.sourceColumn}-${i}`} className="border-t"><td>{m.sheet}</td><td>{m.sourceColumn}</td><td><select className="max-w-64 rounded border p-1" value={m.targetEntity&&m.targetField?`${m.targetEntity}:${m.targetField}`:""} onChange={e=>{const [targetEntity,targetField]=e.target.value?e.target.value.split(":"): [null,null];setBatch({...batch,column_mappings:batch.column_mappings.map((x,j)=>j===i?{...x,targetEntity,targetField,confidence:"HIGH",reason:"Confirmed by user."}:x)});}}><option value="">Leave unmapped</option>{["SUPPLIER:name","SUPPLIER:legal_name","SUPPLIER:contact_person","SUPPLIER:email","SUPPLIER:phone","SUPPLIER:country","SUPPLIER:address","SUPPLIER:payment_terms","SUPPLIER:tax_id","ITEM:name","ITEM:code","ITEM:description","ITEM:category","ITEM:uom","ITEM:hsn_code","CUSTOMER:customer_name","CUSTOMER:customer_code","CUSTOMER:contact_person","CUSTOMER:email","CUSTOMER:phone","CUSTOMER:billing_address","CUSTOMER:shipping_address","CUSTOMER:country","CUSTOMER:credit_days","CUSTOMER:tax_treatment","BOM:parent_name","BOM:component_name","BOM:quantity"].map(x=><option key={x} value={x}>{x.replace(":"," → ")}</option>)}</select></td><td>{m.confidence}</td><td>{m.reason}</td></tr>)}</tbody></table></div></section>
    {rows.some(r=>r.decision==="MISSING_DATA")&&<div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void downloadMissing()} className="rounded border px-3 py-2">Download missing data template</button><label className="cursor-pointer rounded border px-3 py-2">Upload completed template<input type="file" accept=".xlsx,.csv" className="hidden" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadMissing(file);e.currentTarget.value="";}} /></label></div>}
    <section className="space-y-3"><h2 className="font-semibold">Row preview and results</h2>{rows.map(row=><article key={row.id} className="rounded border p-4"><div className="flex flex-wrap justify-between gap-2"><b>{row.target_entity} · {row.sheet_name} row {row.source_row}</b><span className="rounded bg-slate-100 px-2 py-1 text-sm">{row.decision}</span></div><pre className="mt-2 overflow-auto text-xs">{JSON.stringify({...row.mapped_values,...row.corrections},null,2)}</pre>{row.created_entity_id&&<p className="text-sm">ERP record: {row.created_table} · {row.created_entity_id}</p>}{row.validation?.map((v:any,i:number)=><p key={i} className="text-sm text-amber-800">{v.field}: {v.message}</p>)}{row.decision==="MISSING_DATA"&&row.validation?.filter((v:any)=>["DB_REQUIRED","SERVICE_REQUIRED"].includes(v.classification)).map((v:any)=><label key={v.field} className="mr-3 inline-flex flex-col text-sm">{v.field}<input className="rounded border px-2 py-1" onBlur={e=>{if(e.target.value)void saveCorrection(row,v.field,e.target.value);}} /></label>)}{row.decision==="POSSIBLE_MATCH"&&<select className="mt-2 rounded border p-2" defaultValue="" onChange={e=>{const candidate=row.match_candidates[Number(e.target.value)];if(candidate)void chooseMatch(row,candidate);}}><option value="">Choose an existing match…</option>{row.match_candidates?.map((m:any,i:number)=><option key={m.id||i} value={i}>{m.name||m.itemName||"Candidate"}</option>)}</select>}</article>)}</section>
    <section className="rounded border p-4"><h2 className="font-semibold">Audit history</h2><ol className="mt-2 space-y-2 text-sm">{(batch.audit_log||[]).slice().reverse().map((e:any,i:number)=><li key={`${e.event}-${i}`} className="border-t pt-2"><b>{e.event}</b> · {e.at?new Date(e.at).toLocaleString():""}</li>)}</ol></section>
    <div className="flex flex-wrap gap-3"><button disabled={busy||!rows.some(r=>r.decision==="CREATE")} onClick={()=>void act("approve")} className="rounded bg-emerald-700 px-4 py-2 text-white">Approve safe import</button><button disabled={busy||!batch.approved_by} onClick={()=>void act("import")} className="rounded bg-blue-700 px-4 py-2 text-white">Import approved records</button>{["COMPLETED","PARTIALLY_COMPLETED"].includes(batch.status)&&<button disabled={busy} onClick={()=>{if(window.confirm("Undo records created or updated by this batch when they are still unused? Records referenced by later business data will be kept."))void act("undo");}} className="rounded border border-red-300 px-4 py-2 text-red-800">Undo safe imports</button>}</div>
  </main>;
}
