'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { CheckCircle2, RefreshCw, ShieldCheck } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';
const field='w-full rounded border border-slate-200 p-2 text-sm'; const money=(v:number)=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',maximumFractionDigits:2}).format(Number(v||0));
export default function Page(){
 const[entities,setEntities]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{try{const[a,b,c]=await Promise.all([apiClient.get('/enterprise-edge/entities'),apiClient.get('/enterprise-edge/intercompany'),apiClient.get('/enterprise-edge/consolidation-runs')]);setEntities(a);setItems(b);setRuns(c);setMessage('')}catch(e:any){setMessage(e?.message||'Unable to load consolidation controls.')}},[]);useEffect(()=>{load()},[load]);
 const submit=(url:string)=>async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(url);try{await apiClient.post(url,Object.fromEntries(new FormData(e.currentTarget)));e.currentTarget.reset();setMessage('Saved for controlled group-finance review.');await load()}catch(x:any){setMessage(x?.message||'Unable to save.')}finally{setBusy('')}};
 const patch=async(url:string,body:any={})=>{setBusy(url);try{await apiClient.patch(url,body);setMessage('Control step completed.');await load()}catch(e:any){setMessage(e?.message||'Control step failed.')}finally{setBusy('')}};
 const match=async(id:string)=>{const amount=window.prompt('Counterparty-confirmed amount (AED)');if(!amount)return;const ref=window.prompt('Counterparty reference');if(!ref)return;await patch(`/enterprise-edge/intercompany/${id}/match`,{counterparty_amount:Number(amount),counterparty_reference:ref,match_note:'Counterparty balance confirmation recorded.'})};
 const open=items.filter(x=>['OPEN','DISPUTED'].includes(x.status)).length,ready=items.filter(x=>x.status==='ELIMINATION_READY').length,eliminated=items.filter(x=>x.status==='ELIMINATED').length;
 return <main className="mx-auto max-w-7xl space-y-5 p-4"><header className="rounded-2xl bg-gradient-to-r from-[#263F58] to-[#526F8C] p-6 text-white"><div className="flex justify-between gap-3"><div><div className="mb-2 flex items-center gap-2 text-sm text-blue-100"><ShieldCheck size={18}/> Group-finance evidence ledger</div><h1 className="text-2xl font-bold">Group Consolidation & Intercompany</h1><p className="mt-2 text-sm text-blue-100">Counterparty confirmation, zero-variance matching, independent approvals and immutable AED eliminations.</p></div><button onClick={load} className="h-fit rounded bg-white/15 p-2"><RefreshCw size={17}/></button></div></header>{message&&<p className="rounded bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}
 <section className="grid gap-3 sm:grid-cols-5"><Metric label="Entities" value={entities.length}/><Metric label="Open / disputed" value={open}/><Metric label="Elimination ready" value={ready}/><Metric label="Eliminated" value={eliminated}/><Metric label="Group runs" value={runs.length}/></section>
 <div className="grid gap-4 lg:grid-cols-3"><form onSubmit={submit('/enterprise-edge/entities')} className="space-y-2 rounded-xl border bg-white p-4"><b>Legal entity</b><input required name="entity_code" placeholder="Entity code" className={field}/><input required name="entity_name" placeholder="Entity name" className={field}/><input name="tax_registration_number" placeholder="UAE TRN" className={field}/><button disabled={!!busy} className="rounded bg-[#344C67] px-3 py-2 text-white">Add entity</button></form><form onSubmit={submit('/enterprise-edge/intercompany')} className="space-y-2 rounded-xl border bg-white p-4"><b>Intercompany item</b><select required name="source_entity_id" className={field}><option value="">Source entity</option>{entities.map(x=><option value={x.id} key={x.id}>{x.entity_code}</option>)}</select><select required name="target_entity_id" className={field}><option value="">Target entity</option>{entities.map(x=><option value={x.id} key={x.id}>{x.entity_code}</option>)}</select><input required name="reference_number" placeholder="Source reference" className={field}/><input required name="transaction_date" type="date" className={field}/><input required name="amount" type="number" min="0.01" step="0.01" placeholder="AED amount" className={field}/><button disabled={!!busy} className="rounded bg-[#344C67] px-3 py-2 text-white">Register item</button></form><form onSubmit={submit('/enterprise-edge/consolidation-runs')} className="space-y-2 rounded-xl border bg-white p-4"><b>Consolidation run</b><input required name="period_from" type="date" className={field}/><input required name="period_to" type="date" className={field}/><input name="reporting_currency" defaultValue="AED" className={field}/><button disabled={!!busy} className="rounded bg-[#344C67] px-3 py-2 text-white">Prepare eliminations</button></form></div>
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Intercompany matching register</h2><p className="mt-1 text-sm text-slate-500">Preparation, counterparty matching and elimination approval require separate users.</p>{items.length?<div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Reference</th><th className="p-2">Entities</th><th className="p-2 text-right">Source</th><th className="p-2 text-right">Counterparty</th><th className="p-2 text-right">Variance</th><th className="p-2">Status</th><th></th></tr></thead><tbody>{items.map(x=><tr className="border-b" key={x.id}><td className="p-2 font-semibold">{x.reference_number}</td><td className="p-2">{x.source?.entity_code} → {x.target?.entity_code}</td><td className="p-2 text-right">{money(x.amount)}</td><td className="p-2 text-right">{x.counterparty_amount==null?'—':money(x.counterparty_amount)}</td><td className={`p-2 text-right font-semibold ${Number(x.match_variance)?'text-red-700':'text-emerald-700'}`}>{x.match_variance==null?'—':money(x.match_variance)}</td><td className="p-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{x.status}</span></td><td className="p-2 text-right">{['OPEN','DISPUTED'].includes(x.status)&&<button onClick={()=>match(x.id)} className="rounded border border-blue-200 px-2 py-1 text-xs text-blue-700">Confirm match</button>}{x.status==='MATCHED'&&<button onClick={()=>patch(`/enterprise-edge/intercompany/${x.id}/approve`,{approval_note:'Independent zero-variance match approved.'})} className="rounded border border-emerald-200 px-2 py-1 text-xs text-emerald-700">Approve elimination</button>}</td></tr>)}</tbody></table></div>:<p className="py-4 text-sm text-slate-500">No intercompany items.</p>}</section>
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Consolidation and elimination ledger</h2>{runs.length?<div className="mt-3 space-y-3">{runs.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex flex-wrap justify-between gap-2"><div><b>{r.run_code}</b><p className="text-xs text-slate-500">{r.period_from} to {r.period_to} · hash {r.evidence_hash?.slice(0,12)}…</p></div><span className="h-fit rounded-full bg-blue-100 px-2 py-1 text-xs font-bold text-blue-700">{r.status}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-4"><Small label="Entities" value={r.entity_count}/><Small label="Exceptions" value={r.open_intercompany_count}/><Small label="Gross IC" value={money(r.control_totals?.gross_intercompany||0)}/><Small label="Post-elimination" value={money(r.control_totals?.post_elimination_net||0)}/></div><div className="mt-3 flex gap-2">{r.status==='DRAFT'&&<button onClick={()=>patch(`/enterprise-edge/consolidation-runs/${r.id}/validate`)} className="rounded border px-2 py-1 text-xs">Validate</button>}{r.status==='VALIDATED'&&<button onClick={()=>patch(`/enterprise-edge/consolidation-runs/${r.id}/approve`)} className="rounded border px-2 py-1 text-xs">Approve</button>}{r.status==='APPROVED'&&<button onClick={()=>patch(`/enterprise-edge/consolidation-runs/${r.id}/post`)} className="inline-flex items-center gap-1 rounded border border-emerald-200 px-2 py-1 text-xs text-emerald-700"><CheckCircle2 size={13}/> Post group elimination</button>}</div></div>)}</div>:<p className="py-4 text-sm text-slate-500">No consolidation runs.</p>}</section></main>;
}
function Metric({label,value}:{label:string,value:number}){return <div className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-bold">{value}</p></div>}function Small({label,value}:{label:string,value:any}){return <div className="rounded bg-slate-50 p-2"><div className="text-xs text-slate-500">{label}</div><div className="font-semibold">{value}</div></div>}
