import { detectPoZeroLines,detectDuplicatePoNumbers,detectPoSequenceBehind,detectPoReceiptInconsistency,detectGrnDuplicatePoItem,detectGrnQuantityInvariant,detectOrphanGrnReferences,detectItemCodeIssues,detectDrawingIssues,detectAttendanceIssues,detectNegativeVendorBalance,findingFingerprint,QA_CHECKS } from './checks';

describe('Auto QA deterministic checks',()=>{
  it('flags active PO headers with zero lines and excludes draft/cancelled',()=>{expect(detectPoZeroLines([{id:'1',po_number:'PO-1',status:'APPROVED'},{id:'2',po_number:'PO-2',status:'DRAFT'},{id:'3',po_number:'PO-3',status:'CANCELLED'}],[]).map(x=>x.entityId)).toEqual(['1']);});
  it('detects normalized duplicate PO numbers without punctuation removal',()=>{const rows=detectDuplicatePoNumbers([{id:'1',po_number:' PO-77 '},{id:'2',po_number:'po-77'},{id:'3',po_number:'PO77'}]);expect(rows).toHaveLength(2);expect(rows[0].severity).toBe('CRITICAL');});
  it('detects PO sequence lower than the implemented allocated numeric suffix',()=>{expect(detectPoSequenceBehind([{id:'1',tenant_id:'t',po_number:'PO-2026-09-012'}],[{tenant_id:'t',document_type:'PURCHASE_ORDER',last_issued_number:11}])).toHaveLength(1);});
  it('flags accepted quantities above received and allows received above accepted',()=>{expect(detectPoReceiptInconsistency([{id:'line',ordered_qty:20,received_qty:10,item_code:'X'}],[{po_item_id:'line',received_quantity:8,accepted_quantity:9}])).toHaveLength(1);expect(detectPoReceiptInconsistency([{id:'line',ordered_qty:20,received_qty:10}],[{po_item_id:'line',received_quantity:8,accepted_quantity:4}])).toHaveLength(0);});
  it('detects repeated PO item receipt rows and raises posted severity',()=>{const lines=[{id:'a',grn_id:'g',po_item_id:'p'},{id:'b',grn_id:'g',po_item_id:'p'}];expect(detectGrnDuplicatePoItem([{id:'g',status:'DRAFT'}],lines)[0].severity).toBe('HIGH');expect(detectGrnDuplicatePoItem([{id:'g',status:'COMPLETED'}],lines)[0].severity).toBe('CRITICAL');});
  it('checks GRN negative quantities and accepted plus rejected invariant',()=>{const output=detectGrnQuantityInvariant([{id:'g',grn_number:'GRN-1',status:'DRAFT'}],[{id:'l',grn_id:'g',received_quantity:10,accepted_quantity:7,rejected_quantity:4},{id:'n',grn_id:'g',received_quantity:2,accepted_quantity:-1,rejected_quantity:0}]);expect(output).toHaveLength(2);});
  it('detects missing PO line reference without mutating it',()=>{expect(detectOrphanGrnReferences([{id:'g',grn_number:'G',po_id:'missing'}],[{id:'l',grn_id:'g',po_item_id:'missing'}],[],[])).toHaveLength(1);});
  it('detects duplicate normalized item codes but does not strip punctuation',()=>{const result=detectItemCodeIssues([{id:'a',code:' X-1 ',is_active:true},{id:'b',code:'x-1',is_active:true},{id:'c',code:'X1',is_active:true}]);expect(result.filter(x=>x.checkKey==='DUPLICATE_NORMALIZED_ITEM_CODE')).toHaveLength(2);});
  it('flags active items without codes',()=>{expect(detectItemCodeIssues([{id:'a',code:' ',name:'Gear',is_active:true}])[0]).toMatchObject({checkKey:'MISSING_ITEM_CODE',severity:'HIGH'});});
  it('reports OEM completeness as informational only',()=>{expect(detectItemCodeIssues([{id:'1',code:'A',oem_name:'OEM'},{id:'2',code:'B'}]).find(x=>x.checkKey==='OEM_OPTIONAL_COMPLETENESS')).toMatchObject({severity:'INFO',autoEngineerCandidate:false,evidence:{itemsWithOem:1,itemsWithoutOem:1}});});
  it('detects duplicate drawing role for item and revision',()=>{const rows=[{id:'1',tenant_id:'t',item_id:'i',drawing_number:'D',revision_code:'R1',file_role:'2d'},{id:'2',tenant_id:'t',item_id:'i',drawing_number:'D',revision_code:'r1',file_role:'2D'}];expect(detectDrawingIssues(rows,[]).filter(x=>x.checkKey==='DUPLICATE_DRAWING_ROLE_PER_REVISION')).toHaveLength(2);});
  it('detects drawing/package identity contradictions',()=>{expect(detectDrawingIssues([{id:'d',revision_package_id:'p',drawing_number:'DR-1',revision_code:'A'}],[{id:'p',drawing_number:'DR-2',revision_code:'A'}])[0].checkKey).toBe('DRAWING_PACKAGE_REVISION_INCONSISTENCY');});
  it('detects duplicate canonical attendance rows',()=>{expect(detectAttendanceIssues([{id:'a',tenant_id:'t',employee_id:'e',attendance_date:'2026-09-30'},{id:'b',tenant_id:'t',employee_id:'e',attendance_date:'2026-09-30'}],[{id:'e'}],[]).filter(x=>x.checkKey==='DUPLICATE_CANONICAL_ATTENDANCE')).toHaveLength(2);});
  it('allows an overnight shift where checkout is on the next date',()=>{const result=detectAttendanceIssues([{id:'a',employee_id:'e',attendance_date:'2026-09-30',check_in_time:'2026-09-30T22:00:00Z',check_out_time:'2026-10-01T06:00:00Z',work_hours:8}],[{id:'e'}],[]);expect(result.filter(x=>x.checkKey==='ATTENDANCE_TIME_INCONSISTENCY')).toHaveLength(0);});
  it('flags negative work hours and missing employee references',()=>{expect(detectAttendanceIssues([{id:'a',employee_id:'missing',attendance_date:'2026-09-30',work_hours:-1}],[],[]).some(x=>x.checkKey==='ATTENDANCE_TIME_INCONSISTENCY')).toBe(true);});
  it('detects attendance punch lacking a canonical header',()=>{expect(detectAttendanceIssues([] ,[],[{id:'p',employee_id:'e',punch_at:'2026-09-30T09:00:00Z'}])[0].checkKey).toBe('ORPHAN_ATTENDANCE_PUNCH');});
  it('flags negative subcontract vendor balance',()=>{expect(detectNegativeVendorBalance([{id:'r',order_id:'o',vendor_balance_quantity:-0.01}])[0].severity).toBe('HIGH');});
  it('fingerprints are deterministic, tenant-isolated and registry declares candidate policy',()=>{expect(findingFingerprint('SAIFSEAS','t','CHECK','PO','1')).toBe(findingFingerprint('SAIFSEAS','t','CHECK','PO','1'));expect(findingFingerprint('SAIFSEAS','t1','CHECK','PO','1')).not.toBe(findingFingerprint('SAIFSEAS','t2','CHECK','PO','1'));expect(QA_CHECKS.find(c=>c.checkKey==='DUPLICATE_PO_NUMBER')?.autoEngineerCandidate).toBe(false);});
});
