import { createHash } from 'crypto';

export type QaSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';
export interface QaFindingDraft {
  checkKey: string; module: string; severity: QaSeverity; title: string; summary: string;
  evidence: Record<string, unknown>; entityType?: string; entityId?: string; entityCode?: string;
  tenantId?: string;
  autoEngineerCandidate: boolean;
}
export interface QaCheckDefinition {
  checkKey: string; module: string; severity: QaSeverity; description: string;
  profileApplicability: readonly string[]; tenantApplicability: 'TENANT' | 'PROFILE';
  autoEngineerCandidate: boolean;
}

const PROFILES = ['SAIFSEAS', 'MIZANTRA', 'ARWA'] as const;
export const QA_CHECKS: QaCheckDefinition[] = [
  ['PO_WITH_ZERO_LINES','PROCUREMENT','HIGH',true], ['DUPLICATE_PO_NUMBER','PROCUREMENT','CRITICAL',false], ['PO_SEQUENCE_BEHIND_EXISTING_MAX','PROCUREMENT','CRITICAL',false], ['PO_RECEIPT_INCONSISTENCY','PROCUREMENT','HIGH',true],
  ['GRN_DUPLICATE_PO_ITEM','GRN','HIGH',true], ['GRN_QUANTITY_INVARIANT','GRN','HIGH',true], ['ORPHAN_GRN_PO_REFERENCE','GRN','HIGH',true],
  ['DUPLICATE_NORMALIZED_ITEM_CODE','INVENTORY','HIGH',false], ['MISSING_ITEM_CODE','INVENTORY','HIGH',false], ['OEM_OPTIONAL_COMPLETENESS','INVENTORY','INFO',false],
  ['DUPLICATE_DRAWING_ROLE_PER_REVISION','DRAWINGS','HIGH',true], ['DRAWING_PACKAGE_REVISION_INCONSISTENCY','DRAWINGS','MEDIUM',false],
  ['DUPLICATE_CANONICAL_ATTENDANCE','HR','HIGH',false], ['ATTENDANCE_TIME_INCONSISTENCY','HR','HIGH',false], ['ORPHAN_ATTENDANCE_PUNCH','HR','MEDIUM',false],
  ['NEGATIVE_VENDOR_BALANCE','SUBCONTRACTING','HIGH',false], ['AUTOENGINEER_WORKER_OFFLINE','AUTOENGINEER','HIGH',true], ['AUTOENGINEER_QUEUE_STUCK','AUTOENGINEER','HIGH',true], ['INCIDENT_STUCK','AUTOENGINEER','MEDIUM',true],
  ['BUILD_PROVENANCE_MISMATCH','SYSTEM','MEDIUM',false],
].map(([checkKey,module,severity,autoEngineerCandidate]: any) => ({
  checkKey, module, severity, autoEngineerCandidate,
  description: checkKey.toLowerCase().replaceAll('_',' '),
  profileApplicability: PROFILES, tenantApplicability: 'TENANT' as const,
}));

const n = (value: unknown) => { const result = Number(value); return Number.isFinite(result) ? result : 0; };
const s = (value: unknown) => String(value ?? '').trim();
const upper = (value: unknown) => s(value).toUpperCase();
const evidence = (rows: any[], map: (row: any) => unknown) => rows.slice(0, 100).map(map);
function finding(checkKey: string, module: string, severity: QaSeverity, title: string, summary: string, row: any, entityType: string, entityCode?: string, payload: Record<string, unknown> = {}, autoEngineerCandidate = false): QaFindingDraft {
  return { checkKey, module, severity, title, summary, evidence: payload, entityType, entityId: s(row.id) || undefined, entityCode, tenantId:s(row.tenant_id)||undefined, autoEngineerCandidate };
}
const draftStatuses = new Set(['DRAFT','CANCELLED','REJECTED','VOID','DELETED']);
const normalized = (value: unknown) => s(value).toLocaleUpperCase('en-US');

export function detectPoZeroLines(orders: any[], lines: any[]): QaFindingDraft[] {
  const counts = new Map<string, number>(); for (const line of lines) counts.set(s(line.po_id), (counts.get(s(line.po_id)) || 0) + 1);
  return orders.filter((po) => !draftStatuses.has(upper(po.status)) && !(counts.get(s(po.id)) || 0)).map((po) => finding('PO_WITH_ZERO_LINES','PROCUREMENT','HIGH','Active purchase order has no lines',`Purchase order ${s(po.po_number)} is ${s(po.status)} but contains no item rows.`,po,'PURCHASE_ORDER',s(po.po_number),{poId:po.id,poNumber:s(po.po_number),status:s(po.status),supplierId:s(po.vendor_id)||null,createdAt:po.created_at||null},true));
}
export function detectDuplicatePoNumbers(orders: any[]): QaFindingDraft[] {
  const groups = new Map<string, any[]>(); for (const po of orders) { const key=`${s(po.tenant_id)}|${normalized(po.po_number)}`; if(normalized(po.po_number)){const group=groups.get(key)||[];group.push(po);groups.set(key,group);} }
  return [...groups.entries()].filter(([,rows])=>rows.length>1).flatMap(([compound,rows])=>{const key=compound.split('|').slice(1).join('|');return rows.map(po=>finding('DUPLICATE_PO_NUMBER','PROCUREMENT','CRITICAL','Duplicate purchase order number',`Normalized PO number ${key} is assigned to ${rows.length} records.`,po,'PURCHASE_ORDER',s(po.po_number),{normalizedNumber:key,recordIds:evidence(rows,r=>s(r.id)),statuses:evidence(rows,r=>s(r.status))}));});
}
export function detectPoSequenceBehind(orders: any[], sequences: any[]): QaFindingDraft[] {
  const maxByTenant=new Map<string,number>(); for(const po of orders){const match=s(po.po_number).match(/^PO-\d{4}-\d{2}-(\d+)$/i);if(match){const key=s(po.tenant_id);maxByTenant.set(key,Math.max(maxByTenant.get(key)||0,Number(match[1])));}}
  return sequences.filter(seq=>upper(seq.document_type)==='PURCHASE_ORDER'&&n(seq.last_issued_number)<(maxByTenant.get(s(seq.tenant_id))||0)).map(seq=>finding('PO_SEQUENCE_BEHIND_EXISTING_MAX','PROCUREMENT','CRITICAL','Purchase order sequence trails existing orders',`The stored counter ${n(seq.last_issued_number)} is behind the highest allocated suffix ${maxByTenant.get(s(seq.tenant_id))}.`,seq,'DOCUMENT_SEQUENCE',upper(seq.document_type),{tenantId:seq.tenant_id,documentType:seq.document_type,counter:n(seq.last_issued_number),highestExisting:maxByTenant.get(s(seq.tenant_id))||0}));
}
export function detectPoReceiptInconsistency(lines: any[], grnLines: any[], orders:any[]=[]): QaFindingDraft[] {
  const poTenant=new Map(orders.map(po=>[s(po.id),s(po.tenant_id)]));
  const totals=new Map<string,{received:number;accepted:number}>(); for(const line of grnLines){const id=s(line.po_item_id);if(!id)continue;const t=totals.get(id)||{received:0,accepted:0};t.received+=n(line.received_quantity??line.received_qty);t.accepted+=n(line.accepted_quantity??line.accepted_qty);totals.set(id,t);}
  return lines.filter(line=>{const t=totals.get(s(line.id));return t&&((t.accepted-t.received)>0.0001||(n(line.received_qty)-n(line.ordered_qty))>0.0001);}).map(line=>{const t=totals.get(s(line.id))!;return finding('PO_RECEIPT_INCONSISTENCY','PROCUREMENT','HIGH','Purchase order receipt totals are inconsistent','Derived accepted or received quantity exceeds the relevant purchase order quantity.',{...line,tenant_id:poTenant.get(s(line.po_id))},'PURCHASE_ORDER_ITEM',s(line.item_code),{poItemId:line.id,ordered:n(line.ordered_qty),storedReceived:n(line.received_qty),grnReceived:t.received,grnAccepted:t.accepted},true);});
}
export function detectGrnDuplicatePoItem(grns: any[], lines: any[]): QaFindingDraft[] {
  const groups=new Map<string,any[]>();for(const line of lines){if(!line.po_item_id)continue;const key=`${line.grn_id}|${line.po_item_id}`;const group=groups.get(key)||[];group.push(line);groups.set(key,group);}
  const grnById=new Map(grns.map(g=>[s(g.id),g]));return [...groups.entries()].filter(([,rows])=>rows.length>1).flatMap(([key,rows])=>{const grn=grnById.get(key.split('|')[0])||{};const posted=['COMPLETED','POSTED','QC_COMPLETED','APPROVED'].includes(upper(grn.status));return rows.map(line=>finding('GRN_DUPLICATE_PO_ITEM','GRN',posted?'CRITICAL':'HIGH','Repeated PO item in one goods receipt',`Multiple receipt lines in ${s(grn.grn_number)||s(grn.id)} reference one PO item.`,{...line,tenant_id:grn.tenant_id},'GRN',s(grn.grn_number),{grnId:grn.id,grnNumber:s(grn.grn_number),poItemId:line.po_item_id,lineIds:evidence(rows,r=>s(r.id)),receivedQuantities:evidence(rows,r=>n(r.received_quantity??r.received_qty)),postingState:s(grn.status)},true));});
}
export function detectGrnQuantityInvariant(grns: any[], lines: any[]): QaFindingDraft[] {
  const byId=new Map(grns.map(g=>[s(g.id),g]));return lines.filter(line=>{const r=n(line.received_quantity??line.received_qty),a=n(line.accepted_quantity??line.accepted_qty),rej=n(line.rejected_quantity??line.rejected_qty);return a<0||rej<0||a-r>0.0001||rej-r>0.0001||a+rej-r>0.0001;}).map(line=>{const g=byId.get(s(line.grn_id))||{};const posted=['COMPLETED','POSTED','QC_COMPLETED','APPROVED'].includes(upper(g.status));return finding('GRN_QUANTITY_INVARIANT','GRN',posted?'CRITICAL':'HIGH','Goods receipt quantities violate accepted quantity rules','Accepted and rejected quantities exceed the received quantity or are negative.',{...line,tenant_id:g.tenant_id},'GRN',s(g.grn_number),{grnId:g.id,grnNumber:s(g.grn_number),lineId:line.id,received:n(line.received_quantity??line.received_qty),accepted:n(line.accepted_quantity??line.accepted_qty),rejected:n(line.rejected_quantity??line.rejected_qty),status:s(g.status)},true);});
}
export function detectOrphanGrnReferences(grns:any[], lines:any[], orders:any[], poLines:any[]):QaFindingDraft[]{const poIds=new Set(orders.map(r=>s(r.id))),lineIds=new Set(poLines.map(r=>s(r.id))),grnMap=new Map(grns.map(r=>[s(r.id),r]));return lines.filter(r=>{const g=grnMap.get(s(r.grn_id));return (g?.po_id&&!poIds.has(s(g.po_id)))||(r.po_item_id&&!lineIds.has(s(r.po_item_id)));}).map(r=>{const g=grnMap.get(s(r.grn_id))||{};return finding('ORPHAN_GRN_PO_REFERENCE','GRN','HIGH','Goods receipt references a missing purchase order item','A receipt line points to a PO or PO item that is not available in this tenant.',{...r,tenant_id:g.tenant_id},'GRN',s(g.grn_number),{grnId:g.id,grnNumber:s(g.grn_number),poId:g.po_id||null,poItemId:r.po_item_id||null,lineId:r.id},true);});}
export function detectItemCodeIssues(items:any[]):QaFindingDraft[]{const groups=new Map<string,any[]>();for(const item of items){const key=`${s(item.tenant_id)}|${normalized(item.code)}`;if(normalized(item.code)){const a=groups.get(key)||[];a.push(item);groups.set(key,a);}}const dup=[...groups.entries()].filter(([,rows])=>rows.length>1).flatMap(([compound,rows])=>{const key=compound.split('|').slice(1).join('|');return rows.map(r=>finding('DUPLICATE_NORMALIZED_ITEM_CODE','INVENTORY','HIGH','Duplicate normalized item code',`The normalized item code ${key} is assigned to multiple items.`,r,'ITEM',s(r.code),{normalizedCode:key,itemIds:evidence(rows,x=>s(x.id))}));});const missing=items.filter(r=>r.is_active!==false&&!s(r.code)).map(r=>finding('MISSING_ITEM_CODE','INVENTORY','HIGH','Active item has no item code','An active inventory master record has a blank item code.',r,'ITEM',undefined,{itemId:r.id,name:s(r.name)}));const byTenant=new Map<string,any[]>();for(const item of items){const key=s(item.tenant_id);const rows=byTenant.get(key)||[];rows.push(item);byTenant.set(key,rows);}const oem=[...byTenant.entries()].filter(([,rows])=>rows.length>0).map(([tenantId,rows])=>({checkKey:'OEM_OPTIONAL_COMPLETENESS',module:'INVENTORY',severity:'INFO' as const,title:'Optional OEM data coverage',summary:'OEM is optional; this is an informational completeness statistic.',evidence:{itemsWithOem:rows.filter(r=>s(r.oem_name??r.oem)).length,itemsWithoutOem:rows.filter(r=>!s(r.oem_name??r.oem)).length,total:rows.length},tenantId:tenantId||undefined,autoEngineerCandidate:false}));return [...dup,...missing,...oem];}
export function detectDrawingIssues(drawings:any[],packages:any[]):QaFindingDraft[]{const groups=new Map<string,any[]>();for(const d of drawings){const key=[d.tenant_id,d.item_id,normalized(d.drawing_number),normalized(d.revision_code??d.version),normalized(d.file_role)].join('|');const a=groups.get(key)||[];a.push(d);groups.set(key,a);}const duplicate=[...groups.entries()].filter(([,rows])=>rows.length>1).flatMap(([,rows])=>rows.map(d=>finding('DUPLICATE_DRAWING_ROLE_PER_REVISION','DRAWINGS','HIGH','Duplicate drawing role within a revision','The same item/revision has multiple drawing files with the same role.',d,'ITEM_DRAWING',s(d.drawing_number),{drawingIds:evidence(rows,r=>s(r.id)),itemId:d.item_id,drawingNumber:s(d.drawing_number),revision:s(d.revision_code??d.version),fileRole:s(d.file_role)})));const pkgMap=new Map(packages.map(p=>[s(p.id),p]));const inconsistent=drawings.filter(d=>{const p=pkgMap.get(s(d.revision_package_id));return p&&(normalized(p.drawing_number)!==normalized(d.drawing_number)||normalized(p.revision_code)!==normalized(d.revision_code));}).map(d=>finding('DRAWING_PACKAGE_REVISION_INCONSISTENCY','DRAWINGS','HIGH','Drawing differs from its revision package identity','Drawing number or revision does not match its linked package.',d,'ITEM_DRAWING',s(d.drawing_number),{drawingId:d.id,packageId:d.revision_package_id,drawingNumber:s(d.drawing_number),revision:s(d.revision_code),packageDrawingNumber:s(pkgMap.get(s(d.revision_package_id))?.drawing_number),packageRevision:s(pkgMap.get(s(d.revision_package_id))?.revision_code)}));return [...duplicate,...inconsistent];}
export function detectAttendanceIssues(rows:any[], employees:any[],punches:any[]):QaFindingDraft[]{const groups=new Map<string,any[]>();for(const r of rows){const key=[r.tenant_id,r.employee_id,r.attendance_date].join('|');const a=groups.get(key)||[];a.push(r);groups.set(key,a);}const duplicates=[...groups.values()].filter(g=>g.length>1).flatMap(g=>g.map(r=>finding('DUPLICATE_CANONICAL_ATTENDANCE','HR','HIGH','Duplicate daily attendance record','More than one canonical attendance row exists for an employee and day.',r,'ATTENDANCE',s(r.attendance_date),{attendanceIds:evidence(g,x=>s(x.id)),employeeId:r.employee_id,date:r.attendance_date})));const employeeIds=new Set(employees.map(e=>s(e.id)));const times=rows.filter(r=>n(r.work_hours)<0||(!employeeIds.has(s(r.employee_id)))||(()=>{if(!r.check_in_time||!r.check_out_time)return false;const a=Date.parse(r.check_in_time),b=Date.parse(r.check_out_time);if(!Number.isFinite(a)||!Number.isFinite(b))return false;return new Date(a).toDateString()===new Date(b).toDateString()&&b<a;})()).map(r=>finding('ATTENDANCE_TIME_INCONSISTENCY','HR','HIGH','Attendance time or employee reference is inconsistent','Worked hours are negative, checkout precedes same-day check-in, or employee reference is missing.',r,'ATTENDANCE',s(r.attendance_date),{attendanceId:r.id,employeeId:r.employee_id,date:r.attendance_date,checkIn:r.check_in_time||null,checkOut:r.check_out_time||null,workHours:r.work_hours??null,missingEmployee:!employeeIds.has(s(r.employee_id))}));const headers=new Set(rows.map(r=>[s(r.employee_id),s(r.attendance_date)].join('|')));const orphans=punches.filter(p=>!headers.has([s(p.employee_id),s(p.punch_at).slice(0,10)].join('|'))).map(p=>finding('ORPHAN_ATTENDANCE_PUNCH','HR','MEDIUM','Attendance punch has no daily header','A punch does not match an attendance row for the same employee and date.',p,'ATTENDANCE_PUNCH',s(p.punch_at).slice(0,10),{punchId:p.id,employeeId:p.employee_id,punchAt:p.punch_at}));return [...duplicates,...times,...orphans];}
export function detectNegativeVendorBalance(rows:any[]):QaFindingDraft[]{return rows.filter(r=>n(r.vendor_balance_quantity)<0).map(r=>finding('NEGATIVE_VENDOR_BALANCE','SUBCONTRACTING','HIGH','Subcontract vendor-held input balance is negative','The reconciled vendor balance is below zero.',r,'SUBCONTRACT_RECONCILIATION',s(r.order_id),{orderId:r.order_id,vendorBalance:n(r.vendor_balance_quantity),status:s(r.status)}));}
export function findingFingerprint(profile:string,tenantId:string|null,checkKey:string,entityType?:string,entityId?:string,stableKey?:string):string{return createHash('sha256').update([profile,tenantId||'PROFILE',checkKey,entityType||'',entityId||stableKey||''].join('|')).digest('hex');}
