'use client';

import { useEffect, useState } from 'react';
import { apiClient } from '../../../../../lib/api-client';
import { getTenantProfile } from '@/lib/profile-branding';
import { Activity, RefreshCw, ShieldCheck } from 'lucide-react';

type Provenance = { version?: string; profile?: string; built_at?: string; status?: string; reason?: string };
type WebProvenance = { version?: string; profile?: string; built_at?: string; buildId?: string; status?: string };
export default function ReleaseInfoPage() {
  const [data, setData] = useState<Provenance | null>(null);
  const [web, setWeb] = useState<WebProvenance | null>(null);
  const [modes, setModes] = useState<Record<string, unknown> | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'unavailable'>('loading');
  const load = async () => { setState('loading'); const [apiResult, webResult, modeResult] = await Promise.allSettled([apiClient.get<Provenance>('/build-provenance'), fetch('/build-id', { cache: 'no-store' }).then((response) => response.ok ? response.json() : Promise.reject(new Error('Web provenance unavailable'))), apiClient.get<any>('/active-planner/unified/configuration')]); setData(apiResult.status === 'fulfilled' ? apiResult.value : null); setWeb(webResult.status === 'fulfilled' ? webResult.value : null); setModes(modeResult.status === 'fulfilled' && modeResult.value?.modes && typeof modeResult.value.modes === 'object' ? modeResult.value.modes : null); setState(apiResult.status === 'fulfilled' && webResult.status === 'fulfilled' ? 'ready' : 'unavailable'); };
  useEffect(() => { void load(); }, []);
  const profile = getTenantProfile();
  return <main className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">System & Governance</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Build & Release Information</h1><p className="mt-2 text-sm text-slate-600">Safe deployment provenance for support. This view contains no credentials or connection strings.</p></header><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-xl bg-slate-100 p-2.5"><ShieldCheck className="h-5 w-5"/></span><div><h2 className="font-semibold text-slate-900">Application build</h2><p className="text-sm text-slate-500">Profile from shared branding configuration</p></div></div><button onClick={() => void load()} aria-label="Refresh build information" className="rounded-lg border border-slate-300 p-2"><RefreshCw size={17}/></button></div><dl className="grid gap-3 sm:grid-cols-2">{[['Application Profile', profile], ['API Git SHA', data?.version || 'Unavailable'], ['API Build Timestamp', data?.built_at ? new Date(data.built_at).toLocaleString() : 'Unavailable'], ['Web Git SHA', web?.version || 'Unavailable'], ['Web Build Timestamp', web?.built_at ? new Date(web.built_at).toLocaleString() : 'Unavailable'], ['Web build ID', web?.buildId || 'Unavailable'], ['Environment', process.env.NODE_ENV || 'Unknown'], ['API/Web health', state === 'ready' ? 'API and web provenance available' : state === 'loading' ? 'Checking build provenance' : 'One or more provenance endpoints unavailable'], ['Database project reference', 'Not exposed in this support view'], ['Feature modes', modes ? JSON.stringify(modes) : 'Capability mode endpoint unavailable']].map(([label,value]) => <div key={label} className="rounded-xl border border-slate-200 p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-2 break-all text-sm font-semibold text-slate-900">{value}</dd></div>)}</dl>{state === 'unavailable' && <p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><Activity className="mr-2 inline h-4 w-4"/>An API or web provenance endpoint did not return build metadata.</p>}</section></main>;
}
