'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { apiClient } from '../../../../../lib/api-client';
import { AlertTriangle, CheckCircle2, DatabaseZap, Fingerprint, ShieldCheck } from 'lucide-react';

const field='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
const examples:any={CUSTOMER:{customer_code:'QA-CUST-001',customer_name:'QA Dubai Customer LLC',country:'UAE',credit_days:30},SUPPLIER:{code:'QA-SUP-001',name:'QA UAE Supplier LLC',country:'UAE',payment_terms:'NET_30'},ITEM:{code:'QA-ITEM-001',name:'QA Controlled Item',uom:'EA',standard_cost:100},BANK_ACCOUNT:{account_id:'GL account UUID',bank_name:'QA UAE Bank',account_number_masked:'****1234',currency_code:'AED'},TAX_CODE:{tax_code:'QA-VAT5',tax_name:'QA UAE VAT 5%',tax_type:'VAT',rate:5},GL_ACCOUNT:{account_code:'QA-1999',account_name:'QA Governance Clearing',account_type:'ASSET',currency_code:'AED'}};

export default function MasterDataGovernancePage(){
 const [dashboard,setDashboard]=useState<any>({totals:{},requests:[]}),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[type,setType]=useState('GL_ACCOUNT'),[operation,setOperation]=useState('CREATE'),[targetId,setTargetId]=useState(''),[payload,setPayload]=useState(JSON.stringify(examples.GL_ACCOUNT,null,2));
 useEffect(()=>{try{const saved=sessionStorage.getItem('master-data-governance-prefill');if(!saved)return;sessionStorage.removeItem('master-data-governance-prefill');const prefill=JSON.parse(saved);if(examples[prefill.entity_type])setType(prefill.entity_type);if(['CREATE','UPDATE','DEACTIVATE'].includes(prefill.operation))setOperation(prefill.operation);if(typeof prefill.target_id==='string')setTargetId(prefill.target_id);if(prefill.proposed_data&&typeof prefill.proposed_data==='object')setPayload(JSON.stringify(prefill.proposed_data,null,2));setMessage('The blocked change was carried here. Review it, add a business reason, then prepare the request.')}catch{}},[]);
 const load=useCallback(async()=>{try{setDashboard(await apiClient.get('/master-data-governance/dashboard'));setMessage('')}catch(e:any){setMessage(e?.message||'Unable to load master-data governance.')}},[]);useEffect(()=>{load()},[load]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy('create');try{const f=new FormData(e.currentTarget);await apiClient.post('/master-data-governance/requests',{entity_type:type,operation,target_id:String(f.get('target_id')||'').trim()||null,proposed_data:JSON.parse(payload),idempotency_key:String(f.get('idempotency_key')||'').trim()||null,note:String(f.get('note')||'').trim()});setMessage('Governed change request prepared.');await load()}catch(e:any){setMessage(e?.message||'Unable to prepare request.')}finally{setBusy('')}};
 const act=async(id:string,action:string)=>{setBusy(id+action);try{await apiClient.patch(`/master-data-governance/requests/${id}/${action}`,{note:`${action} through master-data governance workbench`});setMessage(`Request ${action} completed.`);await load()}catch(e:any){setMessage(e?.message||`Unable to ${action} request.`)}finally{setBusy('')}};
 const changeType=(v:string)=>{setType(v);setPayload(JSON.stringify(examples[v],null,2))};const t=dashboard.totals||{};
 return <main className="space-y-5 p-6"><header><p className="text-xs font-bold uppercase tracking-widest text-[#8B6F47]">Enterprise controls</p><h1 className="text-2xl font-bold text-[#344C67]">Master Data Governance</h1><p className="text-sm text-slate-600">One controlled path for customer, supplier, item, bank, tax and chart-of-accounts changes.</p></header>
 {message&&<div className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
 <div className={`rounded-lg border px-4 py-3 text-sm font-semibold ${dashboard.enforcement?.enabled?'border-emerald-300 bg-emerald-50 text-emerald-800':'border-amber-300 bg-amber-50 text-amber-800'}`}>Enforcement: {dashboard.enforcement?.enabled?'ON — direct master writes are blocked':'OFF — governance is advisory'}</div>
 <section className={`rounded-xl border p-4 ${dashboard.sla?.summary?.escalated?'border-red-300 bg-red-50':'border-slate-200 bg-white'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold text-[#344C67]">Approval SLA control</h2><p className="text-sm text-slate-600">{dashboard.sla?.summary?.due_soon||0} due soon · {dashboard.sla?.summary?.overdue||0} overdue · {dashboard.sla?.summary?.escalated||0} escalated</p></div><button type="button" onClick={async()=>{setBusy('sla');try{await apiClient.post('/master-data-governance/sla/evaluate',{});setMessage('SLA reminders and escalations evaluated and recorded.');await load()}catch(e:any){setMessage(e?.message||'Unable to evaluate SLA.')}finally{setBusy('')}}} disabled={!!busy} className="rounded border px-3 py-2 text-sm font-semibold">Evaluate SLA now</button></div>{(dashboard.sla?.signals||[]).filter((x:any)=>x.state!=='ON_TRACK').slice(0,5).map((x:any)=><p key={x.request_id} className="mt-2 text-xs text-slate-700"><b>{x.request_number}</b> · {x.stage} · {x.state.replace('_',' ')} · due {new Date(x.due_at).toLocaleString()}</p>)}</section>
 <section className="rounded-xl border border-[#d9c9aa] bg-[#fffdf8] p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold text-[#344C67]">My governance worklist</h2><p className="text-sm text-slate-600">{dashboard.workflow?.actionable_count||0} item(s) need your action. Independent maker–checker separation is enforced.</p></div><span className="rounded-full bg-[#344C67] px-3 py-1 text-xs font-bold text-white">{dashboard.workflow?.configured?'Finance roles configured':'Role setup pending'}</span></div><div className="mt-4 grid gap-3 md:grid-cols-4">{[['prepare','Prepare','submit'],['review','Review','review'],['approve','Approve','approve'],['post','Post','apply']].map(([key,label,action])=>{const items=dashboard.workflow?.worklist?.[key]||[];return <div key={key} className="rounded-lg border bg-white p-3"><div className="flex items-center justify-between"><b className="text-sm text-[#344C67]">{label}</b><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold">{items.length}</span></div>{items.slice(0,3).map((r:any)=><div key={r.id} className="mt-2 border-t pt-2 text-xs"><b>{r.request_number}</b><p className="text-slate-500">{r.entity_type} · risk {r.risk_score}/100</p><button disabled={!!busy} onClick={()=>act(r.id,action)} type="button" className="mt-1 rounded border border-[#8B6F47] px-2 py-1 font-semibold text-[#344C67]">{action==='apply'?'Apply':'Mark '+label.toLowerCase()}</button></div>)}{!items.length&&<p className="mt-2 text-xs text-slate-500">Nothing waiting.</p>}</div>})}</div>{!dashboard.workflow?.configured&&<p className="mt-3 text-xs text-amber-800">Until Finance assigns Journal Preparer, Reviewer, Approver and Poster roles, the existing independent-user rule remains active. Configure roles from Accounts to lock each stage to nominated users.</p>}</section>
 <section className="grid gap-3 sm:grid-cols-6">{[['Requests',t.all||0,DatabaseZap],['Pending',t.pending||0,ShieldCheck],['High risk',t.high_risk||0,AlertTriangle],['Duplicates',t.duplicates_flagged||0,Fingerprint],['Blocked bypasses',t.bypass_attempts||0,ShieldCheck],['Applied',t.applied||0,CheckCircle2]].map(([label,value,Icon]:any)=><div key={label} className="rounded-xl border bg-white p-4"><Icon size={18} className="text-[#8B6F47]"/><p className="mt-2 text-2xl font-bold text-[#344C67]">{value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</section>
 <form onSubmit={create} className="grid gap-4 rounded-xl border bg-white p-5 lg:grid-cols-2"><div className="space-y-3"><h2 className="font-semibold text-[#344C67]">Prepare controlled change</h2><div className="grid gap-2 sm:grid-cols-2"><select value={type} onChange={e=>changeType(e.target.value)} className={field}>{Object.keys(examples).map(x=><option key={x}>{x}</option>)}</select><select value={operation} onChange={e=>setOperation(e.target.value)} className={field}><option>CREATE</option><option>UPDATE</option><option>DEACTIVATE</option></select></div>{operation!=='CREATE'&&<input required name="target_id" value={targetId} onChange={e=>setTargetId(e.target.value)} placeholder="Target record UUID" className={field}/>}<input name="idempotency_key" placeholder="External/idempotency reference (optional)" className={field}/><input name="note" placeholder="Business reason" className={field}/><p className="text-xs text-slate-500">Exact and fuzzy duplicates, downstream references and sensitive-field risk are evaluated before submission.</p></div><div><label className="text-xs font-semibold text-slate-600">Proposed fields (JSON)</label><textarea value={payload} onChange={e=>setPayload(e.target.value)} rows={9} className={`${field} mt-1 font-mono`}/><button disabled={!!busy} className="mt-2 rounded-lg bg-[#344C67] px-4 py-2 text-sm font-semibold text-white">Prepare request</button></div></form>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold text-[#344C67]">Governance ledger</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-2">Request</th><th className="p-2">Master / change</th><th className="p-2">Risk</th><th className="p-2">Evidence</th><th className="p-2">Status / action</th></tr></thead><tbody>{(dashboard.requests||[]).map((r:any)=><tr key={r.id} className="border-b align-top"><td className="p-2"><b>{r.request_number}</b><p className="text-xs text-slate-500">{new Date(r.created_at).toLocaleString()}</p></td><td className="p-2">{r.entity_type} · {r.operation}<p className="text-xs text-slate-500">{r.impact_analysis?.total_references||0} references · {(r.duplicate_findings||[]).length} matches</p></td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${r.risk_score>=70?'bg-red-100 text-red-700':r.risk_score>=40?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{r.risk_score}/100</span></td><td className="p-2 font-mono text-xs">{r.evidence_hash?.slice(0,12)}…</td><td className="p-2"><b className="text-xs">{r.status}</b><div className="mt-2 flex flex-wrap gap-1">{r.status==='DRAFT'&&<button onClick={()=>act(r.id,'submit')} type="button" className="rounded border px-2 py-1 text-xs">Submit</button>}{r.status==='SUBMITTED'&&<button onClick={()=>act(r.id,'review')} type="button" className="rounded border px-2 py-1 text-xs">Review</button>}{r.status==='REVIEWED'&&<button onClick={()=>act(r.id,'approve')} type="button" className="rounded border px-2 py-1 text-xs">Approve</button>}{r.status==='APPROVED'&&<button onClick={()=>act(r.id,'apply')} type="button" className="rounded border border-emerald-300 px-2 py-1 text-xs text-emerald-700">Apply</button>}{['SUBMITTED','REVIEWED','APPROVED'].includes(r.status)&&<button onClick={()=>act(r.id,'reject')} type="button" className="rounded border border-red-200 px-2 py-1 text-xs text-red-600">Reject</button>}</div></td></tr>)}</tbody></table>{!(dashboard.requests||[]).length&&<p className="py-8 text-center text-sm text-slate-500">No governed changes yet.</p>}</div></section></main>;
}
