'use client';

import { useCallback, useEffect, useState } from 'react';
import { BarChart3, CheckCircle2, Loader2, RefreshCw } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

type MarginLine = { item_id: string; item_code?: string | null; item_name: string; quantity: number; revenue: number; standard_cost: number; gross_margin: number; gross_margin_percent: number };
type Summary = { revenue: number; standard_cost: number; gross_margin: number; gross_margin_percent: number; lines: MarginLine[]; disclaimer: string };
type Fifo = { total_cogs: number; event_count: number; events: Array<{ id: string; reference_number?: string | null; quantity: number; unit_cost: number; total_cost: number; event_at: string; items?: { code?: string; name?: string } | null }>; disclaimer: string };
type FifoCoverage = { receipt_event_count: number; receipt_quantity: number; receipt_cost: number; issue_event_count: number; issue_quantity: number; issue_cost: number; disclaimer: string };
type CostEvent = { id: string; event_type: string; reference_number?: string | null; quantity: number; unit_cost: number; total_cost: number; event_at: string; items?: { code?: string; name?: string } | null; posting?: { status: string; journal?: { journal_number: string; status: string } | null } | null };
type ValuationRun = { id: string; run_code: string; period_start: string; period_end: string; status: string; opening_value: number; receipt_value: number; issue_value: number; closing_value: number; movement_variance: number; event_count: number; exception_count: number; evidence_hash: string };
const money = (value: number) => new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED', maximumFractionDigits: 2 }).format(Number(value || 0));

export default function CostingPage() {
  const [data, setData] = useState<Summary | null>(null); const [fifo, setFifo] = useState<Fifo | null>(null); const [coverage, setCoverage] = useState<FifoCoverage | null>(null); const [events, setEvents] = useState<CostEvent[]>([]); const [runs, setRuns] = useState<ValuationRun[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [drafting, setDrafting] = useState<string | null>(null); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [margin, fifoEvents, fifoCoverage, inventoryEvents, valuationRuns] = await Promise.all([apiClient.get<Summary>('/costing/standard-margin'), apiClient.get<Fifo>('/costing/fifo-cogs'), apiClient.get<FifoCoverage>('/costing/fifo-coverage'), apiClient.get<CostEvent[]>('/costing/inventory-events'), apiClient.get<ValuationRun[]>('/costing/valuation-runs')]); setData(margin); setFifo(fifoEvents); setCoverage(fifoCoverage); setEvents(inventoryEvents); setRuns(valuationRuns); } catch (err: any) { setError(err?.message || 'Unable to load cost and margin data.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const draft = async (id: string) => { setDrafting(id); setMessage(''); setError(''); try { const result: any = await apiClient.post(`/costing/fifo-cogs/${id}/draft`); setMessage(result?.status === 'SKIPPED' ? result.reason : result?.idempotent ? 'Existing COGS draft found.' : 'COGS draft created for finance review.'); } catch (err: any) { setError(err?.message || 'Unable to create COGS draft.'); } finally { setDrafting(null); } };
  const draftEvent = async (id: string) => { setDrafting(id); setMessage(''); setError(''); try { const result: any = await apiClient.post(`/costing/events/${id}/draft`); setMessage(result?.status === 'SKIPPED' ? result.reason : result?.idempotent ? 'Existing valuation journal found.' : 'Valuation draft created for finance review.'); await load(); } catch (err: any) { setError(err?.message || 'Unable to create valuation draft.'); } finally { setDrafting(null); } };
  const createRun = async () => { const today = new Date().toISOString().slice(0, 10); setLoading(true); try { await apiClient.post('/costing/valuation-runs', { run_code: `INV-${today}-${Date.now()}`, period_start: `${today.slice(0, 8)}01`, period_end: today }); setMessage('FIFO valuation snapshot created with SHA-256 evidence.'); await load(); } catch (err: any) { setError(err?.message || 'Unable to create valuation snapshot.'); setLoading(false); } };
  const certify = async (id: string) => { setLoading(true); try { await apiClient.post(`/costing/valuation-runs/${id}/certify`, { certification_note: 'Finance independently verified FIFO evidence and ledger movement reconciliation.' }); setMessage('Inventory valuation independently certified.'); await load(); } catch (err: any) { setError(err?.message || 'Unable to certify valuation.'); setLoading(false); } };
  return <div className="mx-auto max-w-7xl space-y-5 p-2 sm:p-4">
    <section className="rounded-2xl bg-gradient-to-r from-[#613535] to-[#99534C] p-5 text-white shadow-lg sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-rose-100"><BarChart3 size={18} /> Explainable profitability</div><h1 className="text-2xl font-bold sm:text-3xl">Cost & Margin Control</h1><p className="mt-2 max-w-2xl text-sm text-rose-50">Billed revenue compared with the approved standard cost of each item.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-lg bg-white/15 px-3 py-2 text-sm font-semibold hover:bg-white/25 disabled:opacity-60">{loading ? <Loader2 size={16} className="animate-spin" /> : <RefreshCw size={16} />} Refresh</button></div></section>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {message && <div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-700">{message}</div>}
    <section className="grid gap-3 sm:grid-cols-5"><Metric label="Billed revenue" value={money(data?.revenue || 0)} /><Metric label="Standard cost" value={money(data?.standard_cost || 0)} /><Metric label="Gross margin" value={money(data?.gross_margin || 0)} /><Metric label="Margin rate" value={`${Number(data?.gross_margin_percent || 0).toFixed(1)}%`} /><Metric label="FIFO COGS evidence" value={money(fifo?.total_cogs || 0)} /></section>
    <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{data?.disclaimer || 'This standard-cost view does not post or replace actual COGS.'}</div>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-900">FIFO evidence coverage</h2><p className="mt-1 text-sm text-slate-500">A reconciliation indicator for new receipt and dispatch evidence; it is not a GL valuation.</p><div className="mt-3 grid gap-3 sm:grid-cols-4"><Metric label="Receipt events" value={String(coverage?.receipt_event_count || 0)} /><Metric label="Receipt cost evidence" value={money(coverage?.receipt_cost || 0)} /><Metric label="Issue events" value={String(coverage?.issue_event_count || 0)} /><Metric label="Issue cost evidence" value={money(coverage?.issue_cost || 0)} /></div><p className="mt-3 text-xs text-slate-500">{coverage?.disclaimer}</p></section>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Inventory-to-ledger control</h2><p className="mt-1 text-sm text-slate-500">Every receipt and issue must have a posted, source-linked journal before finance certification.</p></div><button onClick={createRun} disabled={loading} className="rounded-lg bg-[#613535] px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Create month snapshot</button></div>{events.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="px-2 py-3">Reference</th><th className="px-2 py-3">Movement</th><th className="px-2 py-3 text-right">Value</th><th className="px-2 py-3">Ledger control</th><th></th></tr></thead><tbody>{events.slice(0, 20).map((event) => <tr key={event.id} className="border-b border-slate-100"><td className="px-2 py-3 font-medium">{event.reference_number || 'No reference'}</td><td className="px-2 py-3">{event.event_type.replaceAll('_', ' ')}</td><td className="px-2 py-3 text-right">{money(event.total_cost)}</td><td className="px-2 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${event.posting?.journal?.status === 'POSTED' ? 'bg-emerald-100 text-emerald-700' : event.posting ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700'}`}>{event.posting?.journal?.status || 'MISSING'}</span></td><td className="px-2 py-3 text-right">{event.posting ? <span className="text-xs text-slate-500">{event.posting.journal?.journal_number}</span> : <button onClick={() => draftEvent(event.id)} disabled={drafting === event.id} className="rounded border border-blue-200 px-2 py-1 text-xs font-semibold text-blue-700">Create draft</button>}</td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-lg bg-slate-50 p-5 text-sm text-slate-500">No valuation events recorded.</div>}</section>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-900">Period valuation certificates</h2><p className="mt-1 text-sm text-slate-500">Immutable FIFO snapshots with independent finance sign-off and tamper-evident evidence hashes.</p>{runs.length ? <div className="mt-4 space-y-3">{runs.map((run) => <div key={run.id} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold text-slate-900">{run.run_code}</div><div className="text-xs text-slate-500">{run.period_start} to {run.period_end} · {run.event_count} events · hash {run.evidence_hash.slice(0, 12)}…</div></div><span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${run.status === 'CERTIFIED' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{run.status}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-5"><Metric label="Opening" value={money(run.opening_value)} /><Metric label="Receipts" value={money(run.receipt_value)} /><Metric label="Issues / COGS" value={money(run.issue_value)} /><Metric label="Closing" value={money(run.closing_value)} /><Metric label="Variance" value={money(run.movement_variance)} /></div>{run.status === 'DRAFT' && <button onClick={() => certify(run.id)} disabled={run.exception_count > 0 || Math.abs(run.movement_variance) > 0.005} className="mt-3 inline-flex items-center gap-2 rounded border border-emerald-200 px-3 py-2 text-xs font-semibold text-emerald-700 disabled:cursor-not-allowed disabled:opacity-40"><CheckCircle2 size={14} /> Certify ({run.exception_count} exceptions)</button>}</div>)}</div> : <div className="mt-4 rounded-lg bg-slate-50 p-5 text-sm text-slate-500">Create the first monthly valuation snapshot after all source journals are posted.</div>}</section>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-900">Billed item margin</h2><p className="mt-1 text-sm text-slate-500">Lowest margin items appear first, making leakage visible for commercial and finance review.</p>{loading ? <Loading /> : data?.lines.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-2 py-3">Item</th><th className="px-2 py-3 text-right">Qty</th><th className="px-2 py-3 text-right">Revenue</th><th className="px-2 py-3 text-right">Std. cost</th><th className="px-2 py-3 text-right">Margin</th><th className="px-2 py-3 text-right">Rate</th></tr></thead><tbody>{data.lines.map((line) => <tr key={line.item_id} className="border-b border-slate-100 last:border-0"><td className="px-2 py-3"><div className="font-medium text-slate-900">{line.item_name}</div><div className="text-xs text-slate-500">{line.item_code || 'No code'}</div></td><td className="px-2 py-3 text-right">{line.quantity}</td><td className="px-2 py-3 text-right">{money(line.revenue)}</td><td className="px-2 py-3 text-right">{money(line.standard_cost)}</td><td className={`px-2 py-3 text-right font-semibold ${line.gross_margin < 0 ? 'text-red-700' : 'text-emerald-700'}`}>{money(line.gross_margin)}</td><td className={`px-2 py-3 text-right font-semibold ${line.gross_margin_percent < 0 ? 'text-red-700' : 'text-emerald-700'}`}>{line.gross_margin_percent.toFixed(1)}%</td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-lg bg-slate-50 p-6 text-sm text-slate-500">No active billed item lines are available for this tenant yet.</div>}</section>
    <section className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-900">FIFO COGS evidence register</h2><p className="mt-1 text-sm text-slate-500">New PGIs capture their consumed layer cost here. Finance must still approve a ledger mapping before any draft journal is created.</p>{loading ? <Loading /> : fifo?.events.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-2 py-3">Dispatch</th><th className="px-2 py-3">Item</th><th className="px-2 py-3 text-right">Qty</th><th className="px-2 py-3 text-right">FIFO unit cost</th><th className="px-2 py-3 text-right">Cost</th><th></th></tr></thead><tbody>{fifo.events.slice(0, 20).map((event) => <tr key={event.id} className="border-b border-slate-100 last:border-0"><td className="px-2 py-3 font-medium">{event.reference_number || '—'}</td><td className="px-2 py-3">{event.items?.name || event.items?.code || 'Item'}</td><td className="px-2 py-3 text-right">{event.quantity}</td><td className="px-2 py-3 text-right">{money(event.unit_cost)}</td><td className="px-2 py-3 text-right font-semibold">{money(event.total_cost)}</td><td className="px-2 py-3 text-right"><button onClick={() => draft(event.id)} disabled={drafting === event.id} className="rounded border border-blue-200 px-2 py-1 text-xs font-semibold text-blue-700 hover:bg-blue-50 disabled:opacity-50">{drafting === event.id ? 'Creating…' : 'Create draft'}</button></td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-lg bg-slate-50 p-6 text-sm text-slate-500">No FIFO cost events yet. Create a new test dispatch to begin the evidence register.</div>}</section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#E8DCC4] bg-white p-4 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-xl font-bold text-slate-900">{value}</div></div>; }
function Loading() { return <div className="flex items-center gap-2 py-8 text-sm text-slate-500"><Loader2 size={16} className="animate-spin" /> Loading billed margin…</div>; }
