import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { IntelligenceService } from './intelligence.service';
import { GovernedToolRegistryService } from './governed-tool-registry.service';

@Injectable()
export class AgentOrchestrationService {
  private readonly db:SupabaseClient=createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_KEY!);
  constructor(private readonly intelligence:IntelligenceService,private readonly tools:GovernedToolRegistryService){}
  private admin(user:any){const roles=[user?.role,...(Array.isArray(user?.roles)?user.roles:[])].map((x:any)=>String(typeof x==='string'?x:x?.role?.name||x?.name||'').toUpperCase().replace(/[\s-]+/g,'_'));if(!roles.some((x:string)=>['SUPER_ADMIN','ADMIN','ADMINISTRATOR'].includes(x)))throw new ForbiddenException('Only an administrator may configure or approve an agent policy.');return String(user?.userId||user?.id||'')}
  async dashboard(tenantId:string){const[policies,runs,proposals]=await Promise.all([this.db.from('mizantra_agent_policies').select('*').eq('tenant_id',tenantId).order('created_at',{ascending:false}),this.db.from('mizantra_agent_runs').select('*').eq('tenant_id',tenantId).order('started_at',{ascending:false}).limit(50),this.db.from('mizantra_agent_proposals').select('*').eq('tenant_id',tenantId).eq('status','WAITING_HUMAN').order('created_at',{ascending:false}).limit(100)]);if(policies.error||runs.error||proposals.error)throw new BadRequestException((policies.error||runs.error||proposals.error)?.message);return{policies:policies.data||[],runs:runs.data||[],proposals:proposals.data||[],safety:{execution_mode:'PROPOSE_ONLY',external_delivery:false,native_actions_require_governed_action_request:true}}}
  async createPolicy(tenantId:string,user:any,body:any){const userId=this.admin(user),name=String(body.policy_name||'').trim(),type=String(body.agent_type||'').toUpperCase(),codes=Array.isArray(body.allowed_tool_codes)?body.allowed_tool_codes.map((x:any)=>String(x).toUpperCase()):[];if(!name||name.length>120||!['OPERATIONS','COLLECTIONS','SUPPLIER','CUSTOMER'].includes(type)||!codes.length)throw new BadRequestException('Policy name, supported agent type and allowed tools are required.');for(const code of codes)this.tools.require(code);const maximum=Math.min(Math.max(Number(body.maximum_proposals)||5,1),20);const{data,error}=await this.db.from('mizantra_agent_policies').insert({tenant_id:tenantId,policy_name:name,agent_type:type,mode:'PROPOSE_ONLY',allowed_tool_codes:Array.from(new Set(codes)),maximum_proposals:maximum,status:'DRAFT',created_by:userId}).select().single();if(error)throw new BadRequestException(error.message);return data}
  async approvePolicy(tenantId:string,user:any,id:string){const userId=this.admin(user),{data:row}=await this.db.from('mizantra_agent_policies').select('*').eq('tenant_id',tenantId).eq('id',id).maybeSingle();if(!row||row.status!=='DRAFT')throw new BadRequestException('Draft agent policy not found.');if(row.created_by===userId)throw new ForbiddenException('Maker-checker control prevents self-approval of an agent policy.');const{data,error}=await this.db.from('mizantra_agent_policies').update({status:'APPROVED',approved_by:userId,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id).eq('status','DRAFT').select().single();if(error)throw new BadRequestException(error.message);return data}
  async run(tenantId:string,user:any,id:string){const userId=String(user.userId||user.id),{data:policy}=await this.db.from('mizantra_agent_policies').select('*').eq('tenant_id',tenantId).eq('id',id).eq('status','APPROVED').maybeSingle();if(!policy)throw new BadRequestException('Approved agent policy not found.');const center=await this.intelligence.commandCenter(tenantId,user),patterns:any={OPERATIONS:/production|inventory|quality|machine|grn/i,COLLECTIONS:/collection|customer|invoice|cash/i,SUPPLIER:/supplier|purchase|vendor|grn/i,CUSTOMER:/customer|sales|delivery|invoice/i},matches=(center.decision_inbox||[]).filter((x:any)=>patterns[policy.agent_type].test(`${x.domain} ${x.title}`)).slice(0,policy.maximum_proposals);const{data:run,error}=await this.db.from('mizantra_agent_runs').insert({tenant_id:tenantId,policy_id:id,status:'RUNNING',evidence_snapshot:{generated_at:center.generated_at,health:center.operating_health,decision_ids:matches.map((x:any)=>x.id)},started_by:userId}).select().single();if(error)throw new BadRequestException(error.message);const tool=policy.allowed_tool_codes[0],rows=matches.map((x:any)=>({tenant_id:tenantId,run_id:run.id,insight_id:x.id,tool_code:tool,title:x.title,rationale:x.recommended_action,evidence:{priority_score:x.priority_score,severity:x.severity,impact:x.impact,route:x.route},status:'WAITING_HUMAN',external_delivery_performed:false}));if(rows.length){const{error:proposalError}=await this.db.from('mizantra_agent_proposals').insert(rows);if(proposalError)throw new BadRequestException(proposalError.message)}await this.db.from('mizantra_agent_runs').update({status:'COMPLETED',proposal_count:rows.length,completed_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',run.id);return{run_id:run.id,proposal_count:rows.length,mode:'PROPOSE_ONLY',external_delivery_performed:false,note:'Every proposal waits for a human. Transactional tools still require a separate governed maker-checker request.'}}
}
