import { ForbiddenException } from "@nestjs/common";
import { BrainDiagnosticEvidence } from "./brain.service";
import { DataDoctorService, dataDoctorIntent } from "./data-doctor.service";

describe("Data Doctor Brain integration", () => {
  const user = { tenantId: "tenant", userId: "actor", role: "ADMIN" };
  const context = { profile: "MIZANTRA", tenant_id: "tenant", current_user_id: "actor", current_user_role: "ADMIN", entity_type: "item", entity_id: "item", document_number: "ITEM-1", module: "ITEM", current_route: "/dashboard/inventory/items", locale: "en" };
  let service: DataDoctorService;
  let evidence: BrainDiagnosticEvidence;
  let brain: { withDiagnosticEvidence: jest.Mock; configuration: jest.Mock };
  let audit: jest.Mock;
  const previousEnv = { ...process.env };
  beforeEach(() => {
    process.env.MIZANTRA_DATA_DOCTOR_ENABLED = "true";
    evidence = { context, nodes: [{ type: "item", row: { id: "item", code: "ITEM-1" }, depth: 0 }], edges: [], canRead: () => true, read: jest.fn().mockResolvedValue([]), receipt: jest.fn(), expand: jest.fn() };
    brain = { withDiagnosticEvidence: jest.fn(async (actor, envelope, inspect) => { if (actor.tenantId !== envelope.tenant_id) throw new ForbiddenException("forged tenant"); return inspect(evidence); }), configuration: jest.fn(() => ({ profile: "MIZANTRA", tenant_id: "tenant" })) };
    service = new DataDoctorService(brain as any); audit = jest.fn(); (service as any).logger = { log: audit };
  });
  afterAll(() => { process.env = previousEnv; });
  const ask = (message: string, envelope: any = context) => service.interpret(user, { message, brain_context: envelope });
  const diagnosed = async (message: string, envelope: any = context) => {
    const result = await ask(message, envelope);
    if (!result) throw new Error("Expected a handled diagnostic request");
    return result;
  };
  it.each(["diagnose this", "why is this wrong", "check this for problems", "reconcile this", "why doesn't this match", "find data issues", "Does the stock of this item reconcile?", "Check this Smart Import batch"])("recognizes diagnostic intent: %s", text => { expect(dataDoctorIntent(text)).toBe(true); });
  it.each(["Who supplies this item?", "Which PR did this come from?", "Why is this still open?", "Show the purchase history of this item"])("leaves normal Brain analytics alone: %s", async text => { expect(await ask(text)).toBeNull(); expect(brain.withDiagnosticEvidence).not.toHaveBeenCalled(); });
  it("uses validated item context without requiring the code again", async () => { const result = await diagnosed("Why is the stock wrong?"); expect(result.intent_type).toBe("DATA_DOCTOR"); expect(brain.withDiagnosticEvidence).toHaveBeenCalledWith(user, context, expect.any(Function)); expect(result.brain_context?.document_number).toBe("ITEM-1"); });
  it("asks for missing context without querying", async () => { expect((await diagnosed("diagnose this", null)).questions).toEqual(["Which record should I diagnose?"]); expect(brain.withDiagnosticEvidence).not.toHaveBeenCalled(); });
  it("blocks cross-tenant context", async () => { await expect(ask("diagnose this", { ...context, tenant_id: "other" })).rejects.toThrow("forged tenant"); });
  it("does not read unauthorized diagnostic datasets", async () => { evidence.canRead = () => false; const result = await diagnosed("diagnose this"); expect(evidence.read).not.toHaveBeenCalled(); expect(result.diagnoses.some((issue: any) => issue.confidence === "INSUFFICIENT_EVIDENCE")).toBe(true); });
  it("returns read-only non-executable results and no mutation methods", async () => { const result = await diagnosed("diagnose this"); expect(result.safety).toEqual({ read_only: true, executable: false }); expect(result.execution_enabled).toBe(false); expect(Object.keys(service).some(key => /database|supabase|orders|inventory|hrService/i.test(key))).toBe(false); });
  it("does not create software incidents for data corrections", async () => { evidence.context = { ...context, entity_type: "purchase_order" }; evidence.nodes = [{ type: "purchase_order", row: { id: "po", po_number: "PO-1" }, depth: 0 }]; evidence.receipt = jest.fn().mockResolvedValue({ open_po: false, remaining_qty: 0 }); const result = await diagnosed("diagnose this PO"); expect(result.diagnoses.find(issue => issue.diagnosis_key === "PO_ZERO_LINES")?.classification).toBe("DATA_CORRECTION_REQUIRED"); expect(result).not.toHaveProperty("support_incident"); });
  it("reuses Brain authoritative PO receipt calculation", async () => { evidence.context = { ...context, entity_type: "purchase_order" }; evidence.nodes = [{ type: "purchase_order", row: { id: "po", po_number: "PO-1" }, depth: 0 }]; evidence.receipt = jest.fn().mockResolvedValue({ open_po: true, remaining_qty: 2, receipt_status: "PARTIALLY_RECEIVED", secret_price: 999 }); const result = await diagnosed("diagnose this PO"); expect(evidence.receipt).toHaveBeenCalledWith("po"); expect(result.evidence.find(entry => entry.claim === "PO_RECEIPT_STATE")?.values).toMatchObject({ open_po: true, remaining_qty: 2, receipt_status: "PARTIALLY_RECEIVED" }); expect(JSON.stringify(result.evidence)).not.toContain("secret_price"); expect(result.evidence.find(entry => entry.claim === "DIAGNOSTIC_COVERAGE")?.values).toMatchObject({ dataset_counts: { poLines: 0 } }); });
  it("expands AutoQA through the same Brain graph using the recorded GRN reference", async () => { evidence.context = { ...context, entity_type: "autoqa_finding" }; evidence.nodes = [{ type: "autoqa_finding", row: { id: "finding", entity_type: "GRN", entity_id: "line", evidence: { grnId: "grn" }, check_key: "GRN_DUPLICATE_PO_ITEM" }, depth: 0 }]; evidence.expand = jest.fn().mockResolvedValue({ context: { ...context, entity_type: "grn" }, nodes: [{ type: "grn", row: { id: "grn" }, depth: 0 }, { type: "grn_item", row: { id: "a", grn_id: "grn", po_item_id: "p" }, depth: 1 }, { type: "grn_item", row: { id: "b", grn_id: "grn", po_item_id: "p" }, depth: 1 }], edges: [] }); const result = await diagnosed("Diagnose this"); expect(evidence.expand).toHaveBeenCalledWith("grn", "grn"); expect(result.diagnoses.some((issue: any) => issue.diagnosis_key === "GRN_DUPLICATE_PO_ITEM")).toBe(true); });
  it("does not expose unavailable cross-tenant QA targets", async () => { evidence.context = { ...context, entity_type: "autoqa_finding" }; evidence.nodes = [{ type: "autoqa_finding", row: { id: "finding", entity_type: "GRN", entity_id: "foreign" }, depth: 0 }]; evidence.expand = jest.fn().mockRejectedValue(new ForbiddenException()); const result = await diagnosed("Diagnose this"); expect(result.diagnoses.some((issue: any) => issue.diagnosis_key === "AUTO_QA_TARGET_UNAVAILABLE")).toBe(true); });
  it("audits identifiers, rules and counts without prompt or record payload", async () => { await ask("diagnose this secret-prompt"); const log = audit.mock.calls[0][0]; expect(log).not.toContain("secret-prompt"); expect(JSON.parse(log)).toMatchObject({ tenant: "tenant", user: "actor", event: "DATA_DOCTOR_DIAGNOSTIC" }); });
  it("restricts health to current tenant admin metadata", async () => { await ask("diagnose this"); expect(service.health(user)).toMatchObject({ recent_diagnostics: 1, execution_enabled: false }); expect(() => service.health({ ...user, role: "VIEWER" })).toThrow("Admin authorization"); brain.configuration.mockReturnValue({ profile: "MIZANTRA", tenant_id: "other" }); expect(service.health(user).recent_diagnostics).toBe(0); });
  it("fails closed when the feature is off", async () => { process.env.MIZANTRA_DATA_DOCTOR_ENABLED = "false"; expect((await diagnosed("diagnose this")).message).toContain("not enabled"); expect(brain.withDiagnosticEvidence).not.toHaveBeenCalled(); });
  it("requires the explicit manual software-fix action", async () => { await expect(service.prepareFix(user, { brain_context: context })).rejects.toThrow("explicit"); expect(brain.withDiagnosticEvidence).not.toHaveBeenCalled(); });
  it("rejects a forged software classification and rechecks data issues", async () => { await expect(service.prepareFix(user, { action: "PREPARE_FIX_WITH_AUTOENGINEER", brain_context: context, diagnosis_key: "ITEM_REQUIRED_VALUES", classification: "SOFTWARE_DEFECT_CANDIDATE", evidence: { forged: true } })).rejects.toThrow("freshly confirmed"); });
  it("prepares only a freshly recomputed confirmed software contradiction", async () => { evidence.context = { ...context, entity_type: "purchase_order" }; evidence.nodes = [{ type: "purchase_order", row: { id: "po", po_number: "PO-1" }, depth: 0 }]; evidence.receipt = jest.fn().mockResolvedValue({ open_po: true, remaining_qty: 0, receipt_status: "FULLY_RECEIVED" }); const result = await service.prepareFix(user, { action: "PREPARE_FIX_WITH_AUTOENGINEER", brain_context: context, diagnosis_key: "PO_OPEN_STATE" }); expect(result.diagnosis.evidence.fact).toEqual({ open_po: true, remaining_qty: 0, receipt_status: "FULLY_RECEIVED" }); expect(evidence.receipt).toHaveBeenCalledTimes(1); });
});