import { BrainContext } from "./brain.service";
import { sanitizeSupportText } from "../support-autofix/support-store.service";
import { INVENTORY_CATEGORIES, normalizeInventoryCategory } from "../inventory/utils/inventory-category";
import { payrollRunCalculationChecksum } from "../hr/payroll-control.domain";

type Row = Record<string, any>;
export type DoctorModule = "INVENTORY" | "PO" | "GRN" | "ITEM" | "DRAWING" | "ATTENDANCE" | "PAYROLL" | "SMART_IMPORT" | "AUTO_QA";
export type DoctorConfidence = "CONFIRMED" | "LIKELY" | "POSSIBLE" | "INSUFFICIENT_EVIDENCE";
export type DoctorSnapshot = { context: BrainContext; root: Row; datasets: Record<string, Row[] | undefined>; receipt?: Row; related_entities: Row[] };
export type Diagnosis = {
  diagnosis_key: string; severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
  module: DoctorModule; entity: Row; title: string; explanation: string;
  evidence: { fact: Row; inference: string | null; unknown: string[] };
  expected_state: unknown; actual_state: unknown; likely_cause: string | null;
  recommended_action: string; confidence: DoctorConfidence; related_entities: Row[];
  classification: "DATA_CORRECTION_REQUIRED" | "SOFTWARE_DEFECT_CANDIDATE" | "NO_ISSUE" | "REVIEW_REQUIRED";
};
type RuleIssue = { fact: Row; expected: unknown; actual: unknown; explanation?: string; confidence?: DoctorConfidence; severity?: Diagnosis["severity"]; software?: boolean; ok?: boolean };
type DoctorRule = { key: string; module: DoctorModule; datasets: string[]; title: string; action: string; evaluate: (snapshot: DoctorSnapshot) => RuleIssue[] };
const text = (value: unknown) => String(value ?? "").trim();
const normalized = (value: unknown) => text(value).normalize("NFKC").toLocaleUpperCase("en-US");
const number = (value: unknown): number | null => value == null || value === "" || !Number.isFinite(Number(value)) ? null : Number(value);
const rows = (snapshot: DoctorSnapshot, key: string) => snapshot.datasets[key] || [];
const exceeds = (left: unknown, right: unknown) => number(left) !== null && number(right) !== null && Number(left) > Number(right) + 0.0001;
const problem = (fact: Row, expected: unknown, actual: unknown, extra: Partial<RuleIssue> = {}): RuleIssue => ({ fact, expected, actual, ...extra });
const group = (records: Row[], key: (row: Row) => string) => {
  const groups = new Map<string, Row[]>();
  for (const record of records) { const identity = key(record); const members = groups.get(identity) || []; members.push(record); groups.set(identity, members); }
  return [...groups.values()];
};
const define = (key: string, module: DoctorModule, datasets: string[], title: string, action: string, evaluate: DoctorRule["evaluate"]): DoctorRule => ({ key, module, datasets, title, action, evaluate });

export function movementReconciliation(snapshot: DoctorSnapshot) {
  const movements = rows(snapshot, "movements");
  const balances = rows(snapshot, "stock");
  const totals = new Map<string, number>();
  const openings = new Set<string>();
  const unknown: string[] = [];
  const ordered = [...movements].sort((left, right) => text(left.movement_date).localeCompare(text(right.movement_date)));
  for (const movement of ordered) {
    const quantity = number(movement.quantity);
    const from = text(movement.from_warehouse_id), to = text(movement.to_warehouse_id);
    if (quantity === null || quantity < 0 || (!from && !to) || !text(movement.movement_type)) { unknown.push(text(movement.id)); continue; }
    if (/^OPENING(?:_STOCK|_BALANCE)?$/.test(normalized(movement.movement_type)) && to && !totals.has(to)) openings.add(to);
    if (from) totals.set(from, (totals.get(from) || 0) - quantity);
    if (to) totals.set(to, (totals.get(to) || 0) + quantity);
  }
  const recorded = new Map<string, number>();
  for (const balance of balances) {
    const quantity = number(balance.quantity);
    if (quantity === null || !balance.warehouse_id) { unknown.push(text(balance.id)); continue; }
    const warehouse = text(balance.warehouse_id);
    recorded.set(warehouse, (recorded.get(warehouse) || 0) + quantity);
  }
  const warehouses = new Set([...totals.keys(), ...recorded.keys()]);
  const complete = !!warehouses.size && !unknown.length && [...warehouses].every(warehouse => openings.has(warehouse));
  const comparisons = [...warehouses].map(warehouse => ({ warehouse_id: warehouse, expected: totals.get(warehouse) || 0, recorded: recorded.get(warehouse) || 0, difference: (recorded.get(warehouse) || 0) - (totals.get(warehouse) || 0) }));
  return { complete, comparisons, unknown, opening_warehouses: [...openings], movement_count: movements.length };
}

export const DATA_DOCTOR_RULES: DoctorRule[] = [
  define("INVENTORY_RECONCILIATION", "INVENTORY", ["stock", "movements"], "Movement-derived stock reconciliation", "Review the movement history and opening baseline through controlled stock procedures; do not adjust stock from this diagnosis.", snapshot => {
    const result = movementReconciliation(snapshot);
    if (!result.complete) return [problem({ movement_count: result.movement_count, opening_warehouses: result.opening_warehouses }, "Complete opening and directional movement history for every warehouse", "Opening baseline or supported movement history is incomplete", { confidence: "INSUFFICIENT_EVIDENCE", severity: "INFO", explanation: "Stock cannot be reconciled conclusively without recorded opening quantities and complete movement history." })];
    const mismatches = result.comparisons.filter(value => Math.abs(value.difference) > 0.0001);
    return mismatches.length ? mismatches.map(value => problem(value, value.expected, value.recorded, { explanation: `Recorded stock differs from movement-derived stock by ${value.difference}.` })) : [problem({ warehouses: result.comparisons }, "Movement-derived stock", "Recorded stock equals movement-derived stock", { ok: true, severity: "INFO", explanation: "Stock reconciles correctly." })];
  }),
  define("INVENTORY_NEGATIVE_BALANCE", "INVENTORY", ["stock"], "Negative recorded stock", "Review the recorded stock and authorized movement history.", snapshot => rows(snapshot, "stock").filter(value => number(value.quantity) !== null && Number(value.quantity) < 0).map(value => problem({ stock_id: value.id, warehouse_id: value.warehouse_id, quantity: value.quantity }, "Non-negative physical balance", value.quantity))),
  define("INVENTORY_RESERVATION", "INVENTORY", ["stock"], "Reservations exceed physical stock", "Review reservations in their originating controlled workflow.", snapshot => rows(snapshot, "stock").filter(value => exceeds(value.reserved_quantity, value.quantity)).map(value => problem({ stock_id: value.id, reserved: value.reserved_quantity, quantity: value.quantity }, "Reservations no greater than physical stock", value.reserved_quantity))),
  define("INVENTORY_AVAILABLE_BALANCE", "INVENTORY", ["stock"], "Available balance differs from physical less reserved stock", "Review the balance derivation before any controlled correction.", snapshot => rows(snapshot, "stock").filter(value => [value.quantity, value.reserved_quantity, value.available_quantity].every(amount => number(amount) !== null) && Math.abs(Number(value.quantity) - Number(value.reserved_quantity) - Number(value.available_quantity)) > 0.0001).map(value => problem({ stock_id: value.id, quantity: value.quantity, reserved: value.reserved_quantity, available: value.available_quantity }, Number(value.quantity) - Number(value.reserved_quantity), value.available_quantity))),
  define("INVENTORY_MOVEMENT_DIRECTION", "INVENTORY", ["movements"], "Movement has no recorded warehouse direction", "Inspect the originating movement; historical quantity cannot be reconstructed from this row alone.", snapshot => rows(snapshot, "movements").filter(value => !value.from_warehouse_id && !value.to_warehouse_id).map(value => problem({ movement_id: value.id, movement_type: value.movement_type }, "Recorded source or destination warehouse", "Neither warehouse recorded", { confidence: "INSUFFICIENT_EVIDENCE", severity: "INFO" }))),
  define("INVENTORY_MOVEMENT_QUANTITY", "INVENTORY", ["movements"], "Movement quantity cannot be interpreted safely", "Review the movement quantity and its sign convention.", snapshot => rows(snapshot, "movements").filter(value => number(value.quantity) === null || Number(value.quantity) < 0).map(value => problem({ movement_id: value.id, quantity: value.quantity }, "Finite directional quantity", value.quantity, { confidence: "POSSIBLE", severity: "MEDIUM" }))),
  define("PO_ZERO_LINES", "PO", ["poLines"], "Purchase order has no lines", "Review the purchase order in its controlled workflow.", snapshot => rows(snapshot, "poLines").length ? [] : [problem({ po_id: snapshot.root.id, status: snapshot.root.status, line_count: 0 }, "At least one order line", 0)]),
  define("PO_DUPLICATE_NUMBER", "PO", ["matchingOrders"], "Duplicate normalized PO number", "Review the allocation and audit trail; do not renumber orders automatically.", snapshot => {
    const matches = rows(snapshot, "matchingOrders").filter(value => normalized(value.po_number) === normalized(snapshot.root.po_number));
    return matches.length > 1 ? [problem({ po_ids: matches.map(value => value.id), number: snapshot.root.po_number }, "One normalized PO number", matches.length, { severity: "CRITICAL" })] : [];
  }),
  define("PO_SUPPLIER_REFERENCE", "PO", ["vendors"], "Supplier reference is missing or unavailable", "Review the supplier association in the authorized purchase workflow.", snapshot => !snapshot.root.vendor_id || !rows(snapshot, "vendors").some(value => value.id === snapshot.root.vendor_id) ? [problem({ po_id: snapshot.root.id, supplier_id: snapshot.root.vendor_id || null }, "Supplier available in this authorized tenant", "No available supplier reference", { confidence: snapshot.root.vendor_id ? "INSUFFICIENT_EVIDENCE" : "CONFIRMED" })] : []),
  define("PO_ORIGIN_REFERENCE", "PO", ["requisitions"], "Recorded originating PR is unavailable", "Review the recorded originating PR link; direct POs without a PR are not assumed invalid.", snapshot => snapshot.root.pr_id && !rows(snapshot, "requisitions").some(value => value.id === snapshot.root.pr_id) ? [problem({ po_id: snapshot.root.id, pr_id: snapshot.root.pr_id }, "Recorded originating PR accessible in this tenant", "PR unavailable", { confidence: "INSUFFICIENT_EVIDENCE", severity: "MEDIUM" })] : []),
  define("PO_LINE_ITEM_REFERENCE", "PO", ["poLines", "items"], "Order line item reference is unavailable", "Review the line and its authorized item master reference.", snapshot => rows(snapshot, "poLines").filter(value => value.item_id && !rows(snapshot, "items").some(item => item.id === value.item_id)).map(value => problem({ line_id: value.id, item_id: value.item_id }, "Accessible referenced item", "Item unavailable", { confidence: "INSUFFICIENT_EVIDENCE" }))),
  define("PO_ACCEPTED_EXCEEDS_RECEIVED", "PO", ["grnLines"], "Accepted receipt quantity exceeds received quantity", "Review the source receipt and QC evidence without changing quantities.", snapshot => rows(snapshot, "grnLines").filter(value => exceeds(value.accepted_qty, value.received_qty)).map(value => problem({ grn_line_id: value.id, accepted: value.accepted_qty, received: value.received_qty }, "Accepted quantity no greater than received", value.accepted_qty))),
  define("PO_OVER_RECEIPT", "PO", ["poLines", "grnLines"], "Recorded receipts exceed the ordered quantity", "Review the configured over-delivery policy and source receipts before deciding whether correction is needed.", snapshot => rows(snapshot, "poLines").flatMap(line => { const received = rows(snapshot, "grnLines").filter(value => value.po_item_id === line.id).reduce((total, value) => total + (number(value.received_qty) || 0), 0); return exceeds(received, line.ordered_qty) ? [problem({ po_line_id: line.id, ordered: line.ordered_qty, received }, "Receipt within authorized over-delivery policy", received, { confidence: "POSSIBLE", severity: "MEDIUM" })] : []; })),
  define("PO_NEGATIVE_OPEN", "PO", [], "Authoritative remaining quantity is negative", "Prepare a software fix only after reviewing this deterministic calculation contradiction.", snapshot => snapshot.receipt && number(snapshot.receipt.remaining_qty) !== null && Number(snapshot.receipt.remaining_qty) < 0 ? [problem({ remaining_qty: snapshot.receipt.remaining_qty }, "Non-negative authoritative remaining quantity", snapshot.receipt.remaining_qty, { software: true })] : []),
  define("PO_OPEN_STATE", "PO", [], "Authoritative open-order evidence is internally inconsistent", "Review the calculation and prepare an authorized software fix if the contradiction is reproduced.", snapshot => snapshot.receipt?.open_po === true && ((number(snapshot.receipt.remaining_qty) !== null && Number(snapshot.receipt.remaining_qty) <= 0) || snapshot.receipt.receipt_status === "FULLY_RECEIVED") ? [problem({ open_po: snapshot.receipt.open_po, remaining_qty: snapshot.receipt.remaining_qty, receipt_status: snapshot.receipt.receipt_status }, "Open PO has remaining quantity and is not fully received", "Conflicting authoritative receipt fields", { software: true })] : []),
  define("PO_ITEM_INFORMATION", "PO", ["poLines"], "Order line lacks item identification", "Review item identification before downstream processing.", snapshot => rows(snapshot, "poLines").filter(value => !text(value.item_code) && !value.item_id).map(value => problem({ line_id: value.id }, "Item reference or explicit item code", "Both missing"))),
  define("GRN_DUPLICATE_PO_ITEM", "GRN", ["grnLines"], "Repeated PO item within the receipt", "Review the repeated lines before posting or use the controlled correction process if already posted.", snapshot => group(rows(snapshot, "grnLines").filter(value => value.po_item_id), value => text(value.po_item_id)).filter(members => members.length > 1).map(members => problem({ po_item_id: members[0].po_item_id, line_ids: members.map(value => value.id), line_count: members.length }, "One receipt line per PO item", members.length))),
  define("GRN_ORPHAN_PO_ITEM", "GRN", ["grnLines", "poLines"], "Receipt line references an unavailable PO line", "Review the receipt relationship in the authorized tenant.", snapshot => rows(snapshot, "grnLines").filter(value => !value.po_item_id || !rows(snapshot, "poLines").some(line => line.id === value.po_item_id)).map(value => problem({ grn_line_id: value.id, po_item_id: value.po_item_id || null }, "Valid PO item relationship", "No available matching PO line", { confidence: value.po_item_id ? "INSUFFICIENT_EVIDENCE" : "CONFIRMED" }))),
  define("GRN_ACCEPTED_EXCEEDS_RECEIVED", "GRN", ["grnLines"], "Accepted quantity exceeds physical receipt", "Review receipt quantities and QC evidence.", snapshot => rows(snapshot, "grnLines").filter(value => exceeds(value.accepted_qty, value.received_qty)).map(value => problem({ line_id: value.id, accepted: value.accepted_qty, received: value.received_qty }, value.received_qty, value.accepted_qty))),
  define("GRN_REJECTED_EXCEEDS_RECEIVED", "GRN", ["grnLines"], "Rejected quantity exceeds physical receipt", "Review receipt quantities and QC evidence.", snapshot => rows(snapshot, "grnLines").filter(value => exceeds(value.rejected_qty, value.received_qty)).map(value => problem({ line_id: value.id, rejected: value.rejected_qty, received: value.received_qty }, value.received_qty, value.rejected_qty))),
  define("GRN_QC_QUANTITY_SUM", "GRN", ["grnLines"], "Accepted plus rejected quantity exceeds receipt", "Review the recorded QC split; unclassified pending QC quantities are not assumed invalid.", snapshot => rows(snapshot, "grnLines").filter(value => [value.accepted_qty, value.rejected_qty, value.received_qty].every(amount => number(amount) !== null) && exceeds(Number(value.accepted_qty) + Number(value.rejected_qty), value.received_qty)).map(value => problem({ line_id: value.id, accepted: value.accepted_qty, rejected: value.rejected_qty, received: value.received_qty }, value.received_qty, Number(value.accepted_qty) + Number(value.rejected_qty)))),
  define("GRN_NEGATIVE_QUANTITY", "GRN", ["grnLines"], "Receipt or QC quantity is negative", "Review the source receipt; reversal documents must use their configured workflow.", snapshot => rows(snapshot, "grnLines").filter(value => [value.received_qty, value.accepted_qty, value.rejected_qty].some(amount => number(amount) !== null && Number(amount) < 0)).map(value => problem({ line_id: value.id, received: value.received_qty, accepted: value.accepted_qty, rejected: value.rejected_qty }, "Non-negative receipt quantities", "Negative recorded quantity"))),
  define("GRN_PO_QUANTITY", "GRN", ["grnLines", "poLines"], "Receipt quantity exceeds its PO line", "Review cumulative receipt quantities and authorized over-delivery tolerance.", snapshot => rows(snapshot, "grnLines").flatMap(value => { const line = rows(snapshot, "poLines").find(candidate => candidate.id === value.po_item_id); return line && exceeds(value.received_qty, line.ordered_qty) ? [problem({ grn_line_id: value.id, po_line_id: line.id, received: value.received_qty, ordered: line.ordered_qty }, "Authorized ordered quantity and tolerance", value.received_qty, { confidence: "POSSIBLE", severity: "MEDIUM" })] : []; })),
  define("GRN_ITEM_RELATIONSHIP", "GRN", ["poLines", "items"], "Receipt PO line lacks a valid item relationship", "Review the PO line master relationship before processing the receipt.", snapshot => rows(snapshot, "poLines").filter(value => !value.item_id && !text(value.item_code)).map(value => problem({ po_line_id: value.id }, "Item reference or explicit item code", "Neither is recorded"))),
  define("GRN_PENDING_QC_MOVEMENT", "GRN", ["grnLines", "movements"], "Stock movement exists while QC is pending", "Verify that pending-QC stock is held in the appropriate QC location; posting alone does not prove invalid stock.", snapshot => rows(snapshot, "movements").length && rows(snapshot, "grnLines").some(value => normalized(value.qc_status) === "PENDING") ? [problem({ movement_ids: rows(snapshot, "movements").map(value => value.id), pending_line_ids: rows(snapshot, "grnLines").filter(value => normalized(value.qc_status) === "PENDING").map(value => value.id) }, "Required QC and warehouse controls honored", "Recorded movements with pending QC", { confidence: "POSSIBLE", severity: "MEDIUM" })] : []),
  define("ITEM_DUPLICATE_CODE", "ITEM", ["matchingItems"], "Duplicate normalized item code", "Review the masters and references; do not merge or rename automatically.", snapshot => { const matches = rows(snapshot, "matchingItems").filter(value => normalized(value.code) === normalized(snapshot.root.code)); return text(snapshot.root.code) && matches.length > 1 ? [problem({ item_ids: matches.map(value => value.id), code: snapshot.root.code }, "One normalized item code", matches.length)] : []; }),
  define("ITEM_REQUIRED_VALUES", "ITEM", ["itemDetails"], "Mandatory item identity is incomplete", "Complete mandatory master fields through authorized review.", snapshot => rows(snapshot, "itemDetails").flatMap(value => ["code", "name", "uom"].filter(field => !text(value[field])).map(field => problem({ item_id: value.id, field }, `Recorded ${field}`, "Missing")))),
  define("ITEM_CLASSIFICATION", "ITEM", ["itemDetails"], "Item category is outside configured classifications", "Review item classification against the configured inventory model.", snapshot => rows(snapshot, "itemDetails").filter(value => !text(value.category) || (!INVENTORY_CATEGORIES.includes(normalized(value.category) as any) && normalizeInventoryCategory(value.category, "RAW_MATERIAL") === "RAW_MATERIAL" && !["RAW_MATERIALS", "PACKING", "PACKING_MATERIAL"].includes(normalized(value.category)))).map(value => problem({ item_id: value.id, category: value.category }, "Supported configured item category", value.category, { confidence: "POSSIBLE", severity: "LOW" }))),
  define("ITEM_DIMENSIONS", "ITEM", ["dimensions"], "Recorded dimensional attributes are invalid", "Review only the supplied dimensions and unit in the configured dimensional workflow.", snapshot => rows(snapshot, "dimensions").flatMap(value => { const invalid = ["length", "width", "thickness"].filter(field => value[field] != null && (number(value[field]) === null || Number(value[field]) <= 0)); const hasDimensions = [value.length, value.width, value.thickness].some(amount => amount != null); return invalid.length || (hasDimensions && !text(value.dimension_uom)) ? [problem({ item_id: value.id, invalid_fields: invalid, dimension_uom: value.dimension_uom || null }, "Positive supplied dimensions with recorded dimensional unit", "Supplied dimensional values or unit are inconsistent")] : []; })),
  define("ITEM_OEM_IDENTITY", "ITEM", ["matchingOem"], "OEM identity is shared by distinct item codes", "Review whether these masters intentionally represent the same OEM component; do not merge automatically.", snapshot => { const matches = rows(snapshot, "matchingOem"); return matches.length > 1 && new Set(matches.map(value => normalized(value.code))).size > 1 ? [problem({ item_ids: matches.map(value => value.id) }, "Reviewed OEM/master identity", "Multiple item codes share the recorded OEM identity", { confidence: "POSSIBLE", severity: "LOW" })] : []; }),
  define("ITEM_SUPPLIER_REFERENCE", "ITEM", ["links", "vendors"], "Active supplier association is unavailable", "Review the active association and supplier record in this tenant.", snapshot => rows(snapshot, "links").filter(value => value.is_active !== false && !rows(snapshot, "vendors").some(vendor => vendor.id === value.vendor_id)).map(value => problem({ association_id: value.id, supplier_id: value.vendor_id }, "Authorized supplier for active association", "Supplier unavailable", { confidence: "INSUFFICIENT_EVIDENCE", severity: "MEDIUM" }))),
  define("DRAWING_DUPLICATE_ROLE", "DRAWING", ["drawings"], "Duplicate drawing role in the same revision", "Review the revision package; preserve files until controlled review.", snapshot => group(rows(snapshot, "drawings"), value => [value.item_id, normalized(value.drawing_number), normalized(value.revision_code ?? value.version), normalized(value.file_role)].join("|")).filter(members => members.length > 1).map(members => problem({ drawing_ids: members.map(value => value.id), drawing_number: members[0].drawing_number, revision: members[0].revision_code, role: members[0].file_role }, "One file per configured revision role", members.length))),
  define("DRAWING_PACKAGE_IDENTITY", "DRAWING", ["drawings", "packages"], "Drawing revision differs from its package", "Review drawing number and revision package identity.", snapshot => rows(snapshot, "drawings").flatMap(value => { const revision = rows(snapshot, "packages").find(candidate => candidate.id === value.revision_package_id); return revision && (normalized(revision.drawing_number) !== normalized(value.drawing_number) || normalized(revision.revision_code) !== normalized(value.revision_code)) ? [problem({ drawing_id: value.id, package_id: revision.id }, { drawing_number: revision.drawing_number, revision: revision.revision_code }, { drawing_number: value.drawing_number, revision: value.revision_code })] : []; })),
  define("DRAWING_ITEM_IDENTITY", "DRAWING", ["drawings", "packages"], "Drawing is linked to another package item", "Review the package/item relationship; do not relink automatically.", snapshot => rows(snapshot, "drawings").flatMap(value => { const revision = rows(snapshot, "packages").find(candidate => candidate.id === value.revision_package_id); return revision?.owner_item_id && revision.owner_item_id !== value.item_id ? [problem({ drawing_id: value.id, package_id: revision.id }, revision.owner_item_id, value.item_id)] : []; })),
  define("DRAWING_CONFLICTING_REVISION", "DRAWING", ["packages"], "Multiple packages share one revision identity", "Review the owner, drawing number and revision identity without deleting history.", snapshot => group(rows(snapshot, "packages"), value => [value.owner_item_id, normalized(value.drawing_number), normalized(value.revision_code)].join("|")).filter(members => members.length > 1).map(members => problem({ package_ids: members.map(value => value.id) }, "One package per owner/drawing/revision identity", members.length))),
  define("DRAWING_MISSING_ROLE", "DRAWING", ["drawings"], "Drawing role identity is missing", "Review the configured role for this revision; no unconfigured optional file is required.", snapshot => rows(snapshot, "drawings").filter(value => !text(value.file_role)).map(value => problem({ drawing_id: value.id, drawing_number: value.drawing_number, revision: value.revision_code }, "Recorded revision file role", "Role missing", { confidence: "POSSIBLE", severity: "LOW" }))),
  define("ATTENDANCE_DUPLICATE", "ATTENDANCE", ["attendance"], "Duplicate canonical daily attendance", "Review canonical records through the controlled attendance process.", snapshot => group(rows(snapshot, "attendance"), value => `${value.employee_id}|${value.attendance_date}`).filter(members => members.length > 1).map(members => problem({ attendance_ids: members.map(value => value.id), employee_id: members[0].employee_id, date: members[0].attendance_date }, "One canonical daily record", members.length))),
  define("ATTENDANCE_TIME_ORDER", "ATTENDANCE", ["attendance"], "Checkout precedes check-in", "Review timestamps and the configured overnight-shift policy.", snapshot => rows(snapshot, "attendance").filter(value => { const start = Date.parse(value.check_in_time), end = Date.parse(value.check_out_time); return Number.isFinite(start) && Number.isFinite(end) && end < start; }).map(value => problem({ attendance_id: value.id, check_in: value.check_in_time, check_out: value.check_out_time }, "Checkout timestamp after check-in, including the next day for overnight shifts", "Checkout timestamp is earlier"))),
  define("ATTENDANCE_NEGATIVE_HOURS", "ATTENDANCE", ["attendance"], "Negative recorded working duration", "Review canonical duration and source punches before payroll processing.", snapshot => rows(snapshot, "attendance").filter(value => number(value.work_hours) !== null && Number(value.work_hours) < 0).map(value => problem({ attendance_id: value.id, work_hours: value.work_hours }, "Non-negative duration", value.work_hours))),
  define("ATTENDANCE_ORPHAN_PUNCH", "ATTENDANCE", ["attendance", "punches"], "Punch has no available canonical attendance record", "Review the explicit attendance link; do not infer an absent physical check-in from a date boundary.", snapshot => rows(snapshot, "punches").filter(value => !value.attendance_id || !rows(snapshot, "attendance").some(record => record.id === value.attendance_id)).map(value => problem({ punch_id: value.id, attendance_id: value.attendance_id || null }, "Accessible canonical attendance link", "No matching record in the inspected window", { confidence: "INSUFFICIENT_EVIDENCE", severity: "MEDIUM" }))),
  define("ATTENDANCE_PUNCH_TIME", "ATTENDANCE", ["attendance", "punches"], "Canonical timestamp differs from its linked punch", "Review punch selection, rounding and attendance policy; payroll effect is not established.", snapshot => rows(snapshot, "punches").flatMap(value => { const record = rows(snapshot, "attendance").find(candidate => candidate.id === value.attendance_id); const canonical = normalized(value.punch_type) === "IN" ? record?.check_in_time : normalized(value.punch_type) === "OUT" ? record?.check_out_time : null; return canonical && Number.isFinite(Date.parse(value.punch_at)) && Number.isFinite(Date.parse(canonical)) && Math.abs(Date.parse(value.punch_at) - Date.parse(canonical)) > 60_000 ? [problem({ punch_id: value.id, attendance_id: record!.id, canonical, punch_at: value.punch_at }, "Canonical policy-consistent punch selection", "Timestamps differ by more than one minute", { confidence: "POSSIBLE", severity: "LOW" })] : []; })),
  define("PAYROLL_EMPLOYEE_NO_SALARY", "PAYROLL", ["salaryComponents"], "Payslip employee has no effective salary component evidence", "Review the effective salary structure and source version before relying on the payslip.", snapshot => { const month = String(rows(snapshot, "period")[0]?.payroll_month || snapshot.root.salary_month || ""); const start = `${month.slice(0, 7)}-01`; const end = month.length === 7 ? new Date(Date.UTC(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0)).toISOString().slice(0, 10) : month; const applicable = rows(snapshot, "salaryComponents").some(value => (!value.effective_from || String(value.effective_from) <= end) && (!value.effective_to || String(value.effective_to) >= start)); return applicable ? [] : [problem({ employee_id: snapshot.root.employee_id, payslip_id: snapshot.root.id, period: month }, "At least one salary component effective during the payroll month", "No applicable salary component evidence is available", { confidence: "INSUFFICIENT_EVIDENCE", severity: "HIGH" })]; }),
  define("OVERLAPPING_SALARY_PERIOD", "PAYROLL", ["salaryComponents"], "Overlapping salary component effective periods", "Review the authoritative effective dates; do not choose a version automatically.", snapshot => group(rows(snapshot, "salaryComponents").filter(value => value.effective_from), value => [value.employee_id, normalized(value.component_type), normalized(value.component_name)].join("|")).flatMap(members => { const overlaps: RuleIssue[] = []; for (let i = 0; i < members.length; i++) for (let j = i + 1; j < members.length; j++) if (String(members[i].effective_from) <= String(members[j].effective_to || "9999-12-31") && String(members[j].effective_from) <= String(members[i].effective_to || "9999-12-31")) overlaps.push(problem({ component_ids: [members[i].id, members[j].id], employee_id: members[i].employee_id }, "Non-overlapping effective salary periods", "Recorded periods overlap")); return overlaps; })),
  define("OVERLAPPING_COMPONENT_PERIOD", "PAYROLL", ["salaryComponents"], "Component versions overlap in effective time", "Review component identity and effective dates through the controlled salary workflow.", snapshot => group(rows(snapshot, "salaryComponents").filter(value => value.effective_from), value => [value.employee_id, normalized(value.component_type), normalized(value.component_name)].join("|")).flatMap(members => { const overlaps: RuleIssue[] = []; for (let i = 0; i < members.length; i++) for (let j = i + 1; j < members.length; j++) if (String(members[i].effective_from) <= String(members[j].effective_to || "9999-12-31") && String(members[j].effective_from) <= String(members[i].effective_to || "9999-12-31")) overlaps.push(problem({ component_ids: [members[i].id, members[j].id] }, "One applicable component version per effective date", "Recorded component periods overlap")); return overlaps; })),
  define("INVALID_NEGATIVE_COMPONENT", "PAYROLL", ["salaryComponents"], "Negative salary component amount", "Review the source component and configured payroll treatment.", snapshot => rows(snapshot, "salaryComponents").filter(value => number(value.amount) !== null && Number(value.amount) < 0).map(value => problem({ component_id: value.id, employee_id: value.employee_id }, "Non-negative component amount", value.amount))),
  define("PAYROLL_LINE_WITHOUT_SOURCE", "PAYROLL", [], "Payroll calculation line has no source evidence", "Review the stored calculation snapshot; do not reconstruct missing historical inputs.", snapshot => (Array.isArray(snapshot.root.payroll_breakdown?.calculation_lines) ? snapshot.root.payroll_breakdown.calculation_lines : []).flatMap((line: Row, index: number) => !line.source || !Object.keys(line.source).length ? [problem({ payslip_id: snapshot.root.id, line_index: index, label: line.label }, "Recorded line source", "No source evidence", { confidence: "INSUFFICIENT_EVIDENCE" })] : [])),
  define("PAYROLL_TOTAL_MISMATCH", "PAYROLL", [], "Payroll calculation totals do not reconcile", "Review source lines and the stored totals; this diagnosis does not repair the payslip.", snapshot => { const b = snapshot.root.payroll_breakdown || {}; const lines = Array.isArray(b.calculation_lines) ? b.calculation_lines : []; const earning = lines.filter((line: Row) => line.kind === "EARNING").reduce((sum: number, line: Row) => sum + (number(line.amount) || 0), 0); const salaryGross = lines.filter((line: Row) => line.kind === "EARNING" && line.source?.salary_component_id).reduce((sum: number, line: Row) => sum + (number(line.amount) || 0), 0); const deduction = lines.filter((line: Row) => line.kind === "DEDUCTION").reduce((sum: number, line: Row) => sum + (number(line.amount) || 0), 0); const net = Math.max(0, Math.round((earning - deduction) * 100) / 100); return lines.length && (Math.abs(salaryGross - Number(b.totals?.gross ?? snapshot.root.gross_salary)) > 0.01 || Math.abs(deduction - Number(b.totals?.deductions ?? snapshot.root.total_deductions)) > 0.01 || Math.abs(net - Number(b.totals?.net ?? snapshot.root.net_salary)) > 0.01) ? [problem({ payslip_id: snapshot.root.id, line_earnings: earning, salary_component_earnings: salaryGross, line_deductions: deduction, line_net: net }, { gross: snapshot.root.gross_salary, deductions: snapshot.root.total_deductions, net: snapshot.root.net_salary }, b.totals || {}, { severity: "HIGH" })] : []; }),
  define("PAYSLIP_TOTAL_MISMATCH", "PAYROLL", [], "Payslip columns differ from stored calculation totals", "Review the stored payslip and calculation snapshot before correction.", snapshot => { const b = snapshot.root.payroll_breakdown?.totals; return b && (Math.abs(Number(snapshot.root.gross_salary) - Number(b.gross)) > 0.01 || Math.abs(Number(snapshot.root.total_deductions) - Number(b.deductions)) > 0.01 || Math.abs(Number(snapshot.root.net_salary) - Number(b.net)) > 0.01) ? [problem({ payslip_id: snapshot.root.id }, { gross: b.gross, deductions: b.deductions, net: b.net }, { gross: snapshot.root.gross_salary, deductions: snapshot.root.total_deductions, net: snapshot.root.net_salary })] : []; }),
  define("PAYROLL_VERSION_LINK_INVALID", "PAYROLL", ["monthSlips"], "Payslip version link does not point to the preceding employee period version", "Review the immutable version chain and preserve both documents.", snapshot => rows(snapshot, "monthSlips").filter(value => value.supersedes_payslip_id && !rows(snapshot, "monthSlips").some(prior => prior.id === value.supersedes_payslip_id && prior.employee_id === value.employee_id && prior.salary_month === value.salary_month && Number(prior.version || 1) < Number(value.version || 1))).map(value => problem({ payslip_id: value.id, version: value.version, supersedes_payslip_id: value.supersedes_payslip_id }, "Earlier payslip version for same employee and month", "Link is missing or crosses the version scope"))),
  define("CORRECTION_SOURCE_VERSION_MISSING", "PAYROLL", ["corrections"], "Correction has no valid source payroll version", "Review correction links and original payroll control history.", snapshot => rows(snapshot, "corrections").filter(value => !value.source_control_id || !value.source_version || !Number(value.source_version)).map(value => problem({ correction_id: value.id, month: value.payroll_month }, "Existing approved or paid source control version", "Source version link is missing"))),
  define("DIFFERENTIAL_MISMATCH", "PAYROLL", ["differences"], "Stored correction differential does not equal corrected minus posted", "Review the recorded differential; no recovery or payment is triggered.", snapshot => rows(snapshot, "differences").filter(value => Math.abs(Number(value.difference) - (Number(value.corrected_amount) - Number(value.posted_amount))) > 0.01).map(value => problem({ correction_id: value.correction_id, employee_id: value.employee_id }, Number(value.corrected_amount) - Number(value.posted_amount), value.difference))),
  define("MAKER_CHECKER_VIOLATION", "PAYROLL", ["corrections", "checker"], "Correction maker and approver are the same person", "Review approval actor identity and the tenant maker/checker policy.", snapshot => rows(snapshot, "checker").some(value => value.enabled === true) ? rows(snapshot, "corrections").filter(value => value.opened_by && value.approved_by && value.opened_by === value.approved_by).map(value => problem({ correction_id: value.id, actor_id: value.opened_by }, "Distinct maker and approver when policy is enabled", "Same actor opened and approved correction", { severity: "HIGH" })) : []),
  define("PAID_VERSION_MUTATED", "PAYROLL", ["controls", "runSlips"], "Finalized payroll checksum differs from reconstructed calculation evidence", "Preserve the finalized source and open a correction version; investigate the altered evidence. This diagnosis does not repair payroll.", snapshot => { const control = rows(snapshot, "controls").find(value => ["APPROVED", "PAID"].includes(String(value.stage)) && String(value.payroll_run_id) === String(snapshot.root.payroll_run_id)); if (!control) return []; const runSlips = rows(snapshot, "runSlips"); if (!control.calculation_checksum || !control.input_checksum || !runSlips.length) return [problem({ control_id: control.id, version: control.version, payslip_id: snapshot.root.id }, "Finalized checksum and complete run payslip evidence", "Checksum or run evidence is unavailable", { severity: "HIGH", confidence: "INSUFFICIENT_EVIDENCE" })]; const currentChecksum = payrollRunCalculationChecksum({ tenant_id: String(snapshot.root.tenant_id), month: String(snapshot.root.salary_month), control_id: String(control.id), version: Number(control.version || 1), input_checksum: String(control.input_checksum), run_id: String(snapshot.root.payroll_run_id), slips: runSlips }); return currentChecksum !== control.calculation_checksum ? [problem({ control_id: control.id, version: control.version, payslip_id: snapshot.root.id, stored_checksum: control.calculation_checksum, reconstructed_checksum: currentChecksum, payslip_count: runSlips.length }, control.calculation_checksum, currentChecksum, { severity: "CRITICAL", confidence: "CONFIRMED" })] : []; }),
  define("MULTIPLE_CURRENT_PAYSLIP_VERSIONS", "PAYROLL", ["monthSlips"], "More than one current payslip exists for this employee and month", "Review version flags and keep the historical documents accessible.", snapshot => { const current = rows(snapshot, "monthSlips").filter(value => value.is_current === true); return current.length > 1 ? [problem({ payslip_ids: current.map(value => value.id), employee_id: snapshot.root.employee_id, month: snapshot.root.salary_month }, "At most one current version", current.length)] : []; }),
  define("RULE_VERSION_MISSING", "PAYROLL", ["payrollRules"], "Calculation references a missing payroll rule version", "Review the recorded rule reference and applicable effective dated rule history.", snapshot => { const lines = Array.isArray(snapshot.root.payroll_breakdown?.calculation_lines) ? snapshot.root.payroll_breakdown.calculation_lines : []; const ids = new Set(rows(snapshot, "payrollRules").map(value => String(value.id))); return lines.flatMap((line: Row) => line.source?.rule_source === "TENANT" && line.source?.rule_version_id && !ids.has(String(line.source.rule_version_id)) ? [problem({ payslip_id: snapshot.root.id, rule_version_id: line.source.rule_version_id, label: line.label }, "Accessible referenced rule version", "Referenced rule version missing", { confidence: "INSUFFICIENT_EVIDENCE" })] : []); }),
  define("IMPORT_BLOCKED_ROWS", "SMART_IMPORT", ["importRows"], "Import rows require controlled review", "Resolve the recorded validation issues and obtain required approval before importing.", snapshot => rows(snapshot, "importRows").filter(value => ["BLOCKED", "MISSING_DATA", "INVALID", "PENDING_BOM_MAPPING", "TRANSACTION_IMPORT_REQUIRES_SPECIALIZED_IMPORTER"].includes(value.decision)).map(value => problem({ row_reference: value.row_reference, decision: value.decision, validation: (Array.isArray(value.validation) ? value.validation : []).map((issue: Row) => ({ field: sanitizeSupportText(issue.field, 80), classification: issue.classification, message: sanitizeSupportText(issue.message, 250) })) }, "Validated safe master-data row", value.decision))),
  define("IMPORT_REQUIRED_DB_FIELDS", "SMART_IMPORT", ["importRows"], "Required database values are missing", "Supply source-approved values; do not invent business defaults.", snapshot => rows(snapshot, "importRows").filter(value => Array.isArray(value.validation) && value.validation.some((issue: Row) => issue?.classification === "DB_REQUIRED")).map(value => problem({ row_reference: value.row_reference, fields: value.validation.filter((issue: Row) => issue?.classification === "DB_REQUIRED").map((issue: Row) => sanitizeSupportText(issue.field, 80)) }, "Required database fields supplied explicitly", "Recorded required fields are unresolved"))),
  define("IMPORT_DUPLICATE_MATCH", "SMART_IMPORT", ["importRows"], "Master match is ambiguous", "Choose the correct existing master through mapping review.", snapshot => rows(snapshot, "importRows").filter(value => value.decision === "POSSIBLE_MATCH").map(value => problem({ row_reference: value.row_reference, candidate_count: Array.isArray(value.match_candidates) ? value.match_candidates.length : 0 }, "One approved master match", "Mapping or master candidates require review"))),
  define("IMPORT_PARENT_DEPENDENCY", "SMART_IMPORT", ["importRows"], "Relationship depends on a blocked parent", "Resolve or exactly match the parent record before approving its relationship.", snapshot => rows(snapshot, "importRows").flatMap(value => { const blocked = (Array.isArray(value.depends_on) ? value.depends_on : []).filter((reference: string) => rows(snapshot, "importRows").some(parent => parent.row_reference === reference && !["CREATE", "USE_EXISTING", "ALREADY_IMPORTED"].includes(parent.decision))); return blocked.length ? [problem({ row_reference: value.row_reference, blocked_parent_references: blocked }, "Approved available parent records", "Recorded parent dependencies are blocked")] : []; })),
  define("IMPORT_APPROVAL_INVALIDATED", "SMART_IMPORT", ["batchDetails"], "Approved import preview differs from the current preview", "Review the current mapping/file preview and obtain fresh approval; do not reuse stale approval.", snapshot => rows(snapshot, "batchDetails").filter(value => value.approved_preview_checksum && value.preview_checksum && value.approved_preview_checksum !== value.preview_checksum).map(value => problem({ batch_id: value.id, checksums_equal: false }, "Approved checksum matches current preview", "Checksums differ"))),
  define("IMPORT_SERVICE_DEFAULT", "SMART_IMPORT", ["importRows"], "Import cannot safely supply a required service value", "Supply an explicit approved source value or use the specialized importer; do not invent defaults.", snapshot => rows(snapshot, "importRows").filter(value => Array.isArray(value.validation) && value.validation.some((issue: Row) => issue.classification === "SERVICE_REQUIRED")).map(value => problem({ row_reference: value.row_reference, fields: value.validation.filter((issue: Row) => issue.classification === "SERVICE_REQUIRED").map((issue: Row) => sanitizeSupportText(issue.field, 80)) }, "Explicit service-required values", "Required source values are missing"))),
  define("AUTO_QA_FINDING_STATE", "AUTO_QA", [], "Recorded AutoQA finding context", "Review the expanded live evidence; this diagnosis does not create another finding.", snapshot => [problem({ check_key: snapshot.root.check_key, status: snapshot.root.status, target_type: snapshot.root.entity_type || null }, "Finding supported by current authorized evidence", snapshot.root.status, { severity: "INFO", confidence: "POSSIBLE", explanation: sanitizeSupportText(snapshot.root.summary, 600) || "Recorded finding requires live evidence expansion." })]),
  define("AUTO_QA_TARGET_UNAVAILABLE", "AUTO_QA", ["qaTarget"], "AutoQA target cannot be expanded", "Open an authorized source entity or review the recorded finding reference.", snapshot => rows(snapshot, "qaTarget").length ? [] : [problem({ check_key: snapshot.root.check_key }, "Authorized supported live target", "Target unavailable or unsupported", { confidence: "INSUFFICIENT_EVIDENCE", severity: "INFO" })]),
];

export function evaluateDoctor(snapshot: DoctorSnapshot, modules: DoctorModule[]) {
  const diagnoses: Diagnosis[] = [];
  const executed: string[] = [];
  const unavailable = new Set<string>();
  for (const rule of DATA_DOCTOR_RULES.filter(value => modules.includes(value.module))) {
    const missing = rule.datasets.filter(key => snapshot.datasets[key] === undefined);
    if (missing.length) { missing.forEach(key => unavailable.add(key)); continue; }
    executed.push(rule.key);
    for (const issue of rule.evaluate(snapshot)) {
      const confidence = issue.confidence || "CONFIRMED";
      diagnoses.push({ diagnosis_key: rule.key, severity: issue.severity || "HIGH", module: rule.module,
        entity: { entity_type: snapshot.context.entity_type, entity_id: snapshot.context.entity_id, document_number: snapshot.context.document_number },
        title: rule.title, explanation: issue.explanation || rule.title + ".",
        evidence: { fact: issue.fact, inference: confidence === "POSSIBLE" || confidence === "LIKELY" ? "Policy or causal interpretation requires additional review." : null, unknown: confidence === "INSUFFICIENT_EVIDENCE" ? ["Complete authorized evidence is unavailable."] : ["Actor intent and historical cause are not established."] },
        expected_state: issue.expected, actual_state: issue.actual, likely_cause: confidence === "CONFIRMED" && !issue.ok ? rule.title : null,
        recommended_action: issue.ok ? "No correction is recommended for this check." : rule.action, confidence, related_entities: snapshot.related_entities,
        classification: issue.ok ? "NO_ISSUE" : issue.software ? "SOFTWARE_DEFECT_CANDIDATE" : ["POSSIBLE", "LIKELY", "INSUFFICIENT_EVIDENCE"].includes(confidence) ? "REVIEW_REQUIRED" : "DATA_CORRECTION_REQUIRED",
      });
    }
  }
  if (unavailable.size) diagnoses.push({ diagnosis_key: "EVIDENCE_UNAVAILABLE", severity: "INFO", module: modules[0], entity: { entity_type: snapshot.context.entity_type, entity_id: snapshot.context.entity_id }, title: "Some diagnostic evidence is unavailable", explanation: "These checks could not run because of permissions, schema availability or bounded query limits.", evidence: { fact: { unavailable_datasets: [...unavailable] }, inference: null, unknown: ["The skipped checks are not evidence of a clean record."] }, expected_state: "Complete authorized evidence", actual_state: "Incomplete evidence", likely_cause: null, recommended_action: "Open a narrower authorized context or review schema availability.", confidence: "INSUFFICIENT_EVIDENCE", related_entities: [], classification: "REVIEW_REQUIRED" });
  return { diagnoses, rules_executed: executed };
}
