import { DATA_DOCTOR_RULES, DoctorSnapshot, evaluateDoctor } from "./data-doctor.rules";

const snapshot = (datasets: DoctorSnapshot["datasets"] = {}, root: Record<string, any> = {}): DoctorSnapshot => ({ context: { profile: "MIZANTRA", tenant_id: "tenant", current_user_id: "user", current_user_role: "ADMIN", current_route: "/dashboard", module: "ITEM", entity_type: "item", entity_id: "item", document_number: "ITEM-1", locale: "en" }, root: { id: "item", ...root }, datasets, related_entities: [] });
const keys = (value: DoctorSnapshot, module: Parameters<typeof evaluateDoctor>[1][number]) => evaluateDoctor(value, [module]).diagnoses.map(issue => issue.diagnosis_key);
describe("Data Doctor pure read-only rules", () => {
  it("registers at least thirty distinct useful rules", () => { expect(DATA_DOCTOR_RULES.length).toBeGreaterThanOrEqual(30); expect(new Set(DATA_DOCTOR_RULES.map(rule => rule.key)).size).toBe(DATA_DOCTOR_RULES.length); });
  it("reconciles stock from an explicit opening and directional movements", () => {
    const result = evaluateDoctor(snapshot({ stock: [{ warehouse_id: "wh", quantity: 12 }], movements: [{ id: "opening", movement_type: "OPENING", quantity: 10, to_warehouse_id: "wh", movement_date: "2026-01-01" }, { id: "receipt", movement_type: "GRN", quantity: 2, to_warehouse_id: "wh", movement_date: "2026-01-02" }] }), ["INVENTORY"]);
    expect(result.diagnoses.find(issue => issue.diagnosis_key === "INVENTORY_RECONCILIATION")).toMatchObject({ confidence: "CONFIRMED", classification: "NO_ISSUE", explanation: "Stock reconciles correctly." });
  });
  it("detects movement-derived stock mismatch", () => {
    const result = evaluateDoctor(snapshot({ stock: [{ warehouse_id: "wh", quantity: 8 }], movements: [{ id: "opening", movement_type: "OPENING", quantity: 10, to_warehouse_id: "wh" }] }), ["INVENTORY"]);
    expect(result.diagnoses[0]).toMatchObject({ actual_state: 8, expected_state: 10 });
  });
  it("does not fabricate a zero opening balance", () => { expect(evaluateDoctor(snapshot({ stock: [{ warehouse_id: "wh", quantity: 8 }], movements: [] }), ["INVENTORY"]).diagnoses[0].confidence).toBe("INSUFFICIENT_EVIDENCE"); });
  it("detects zero-line PO", () => { expect(keys(snapshot({ poLines: [] }), "PO")).toContain("PO_ZERO_LINES"); });
  it("detects PO accepted greater than received", () => { expect(keys(snapshot({ grnLines: [{ accepted_qty: 4, received_qty: 3 }] }), "PO")).toContain("PO_ACCEPTED_EXCEEDS_RECEIVED"); });
  it("uses authoritative open receipt evidence rather than inventing status rules", () => { const value = snapshot(); value.receipt = { open_po: true, remaining_qty: 4, receipt_status: "PARTIALLY_RECEIVED" }; expect(keys(value, "PO")).not.toContain("PO_OPEN_STATE"); });
  it("detects contradictory authoritative open state", () => { const value = snapshot(); value.receipt = { open_po: true, remaining_qty: 0, receipt_status: "FULLY_RECEIVED" }; expect(keys(value, "PO")).toContain("PO_OPEN_STATE"); });
  it("detects duplicate GRN PO item", () => { expect(keys(snapshot({ grnLines: [{ id: "a", po_item_id: "line" }, { id: "b", po_item_id: "line" }] }), "GRN")).toContain("GRN_DUPLICATE_PO_ITEM"); });
  it("reports an unavailable GRN reference without asserting inaccessible history", () => { expect(keys(snapshot({ grnLines: [{ id: "a", po_item_id: "missing" }], poLines: [] }), "GRN")).toContain("GRN_ORPHAN_PO_ITEM"); });
  it("detects GRN quantity mismatch as policy-dependent", () => { const result = evaluateDoctor(snapshot({ grnLines: [{ po_item_id: "line", received_qty: 4 }], poLines: [{ id: "line", ordered_qty: 3 }] }), ["GRN"]); expect(result.diagnoses.find(issue => issue.diagnosis_key === "GRN_PO_QUANTITY")?.confidence).toBe("POSSIBLE"); });
  it("detects normalized duplicate item codes", () => { expect(keys(snapshot({ matchingItems: [{ id: "a", code: " item-1 " }, { id: "b", code: "ITEM-1" }] }, { code: "ITEM-1" }), "ITEM")).toContain("ITEM_DUPLICATE_CODE"); });
  it("detects mandatory item values but not optional OEM emptiness", () => { const result = evaluateDoctor(snapshot({ itemDetails: [{ id: "item", code: "ITEM-1", name: "Item", uom: "", oem_name: null }] }), ["ITEM"]); expect(result.diagnoses.find(issue => issue.diagnosis_key === "ITEM_REQUIRED_VALUES")?.evidence.fact.field).toBe("uom"); expect(result.diagnoses.some(issue => issue.title.includes("OEM"))).toBe(false); });
  it("detects drawing revision inconsistency", () => { expect(keys(snapshot({ drawings: [{ id: "drawing", revision_package_id: "package", revision_code: "A", drawing_number: "D" }], packages: [{ id: "package", revision_code: "B", drawing_number: "D" }] }), "DRAWING")).toContain("DRAWING_PACKAGE_IDENTITY"); });
  it("detects duplicate drawing roles in the same revision", () => { expect(keys(snapshot({ drawings: [{ id: "a", item_id: "item", drawing_number: "D", revision_code: "A", file_role: "PRIMARY" }, { id: "b", item_id: "item", drawing_number: "D", revision_code: "A", file_role: "PRIMARY" }] }), "DRAWING")).toContain("DRAWING_DUPLICATE_ROLE"); });
  it("detects duplicate attendance", () => { expect(keys(snapshot({ attendance: [{ id: "a", employee_id: "e", attendance_date: "2026-01-01" }, { id: "b", employee_id: "e", attendance_date: "2026-01-01" }] }), "ATTENDANCE")).toContain("ATTENDANCE_DUPLICATE"); });
  it("does not falsely flag an overnight shift", () => { expect(keys(snapshot({ attendance: [{ employee_id: "e", check_in_time: "2026-01-01T22:00:00Z", check_out_time: "2026-01-02T06:00:00Z", work_hours: 8 }] }), "ATTENDANCE")).not.toContain("ATTENDANCE_TIME_ORDER"); });
  it("uses attendance_id instead of punch date to identify overnight linkage", () => { expect(keys(snapshot({ attendance: [{ id: "a", attendance_date: "2026-01-01" }], punches: [{ id: "p", attendance_id: "a", punch_at: "2026-01-02T06:00:00Z" }] }), "ATTENDANCE")).not.toContain("ATTENDANCE_ORPHAN_PUNCH"); });
  it("detects orphan attendance punches", () => { expect(keys(snapshot({ attendance: [], punches: [{ id: "p", attendance_id: "missing" }] }), "ATTENDANCE")).toContain("ATTENDANCE_ORPHAN_PUNCH"); });
  it("explains blocked Smart Import rows using stored validation", () => { const result = evaluateDoctor(snapshot({ importRows: [{ row_reference: "Sheet:2", decision: "BLOCKED", validation: [{ field: "uom", classification: "DB_REQUIRED", message: "A unit is required" }] }] }), ["SMART_IMPORT"]); expect(result.diagnoses.find(issue => issue.diagnosis_key === "IMPORT_BLOCKED_ROWS")?.evidence.fact.validation[0].message).toBe("A unit is required"); });
  it("explains ambiguous master matches", () => { expect(keys(snapshot({ importRows: [{ row_reference: "Sheet:2", decision: "POSSIBLE_MATCH", match_candidates: [{ id: "a" }, { id: "b" }] }] }), "SMART_IMPORT")).toContain("IMPORT_DUPLICATE_MATCH"); });
  it("detects stale import approval", () => { expect(keys(snapshot({ batchDetails: [{ id: "batch", approved_preview_checksum: "old", preview_checksum: "new" }] }), "SMART_IMPORT")).toContain("IMPORT_APPROVAL_INVALIDATED"); });
  it("expands AutoQA status without creating a finding", () => { expect(keys(snapshot({ qaTarget: [] }, { check_key: "GRN_DUPLICATE_PO_ITEM", status: "OPEN" }), "AUTO_QA")).toContain("AUTO_QA_TARGET_UNAVAILABLE"); });
  it("separates confirmed facts from possible policy interpretation", () => { const result = evaluateDoctor(snapshot({ grnLines: [{ received_qty: 3, accepted_qty: 4, po_item_id: "line" }], poLines: [{ id: "line", ordered_qty: 2 }] }), ["GRN"]); expect(result.diagnoses.find(issue => issue.diagnosis_key === "GRN_ACCEPTED_EXCEEDS_RECEIVED")?.confidence).toBe("CONFIRMED"); expect(result.diagnoses.find(issue => issue.diagnosis_key === "GRN_PO_QUANTITY")?.likely_cause).toBeNull(); });
  it("does not present skipped permissions or schema checks as clean", () => { const result = evaluateDoctor(snapshot(), ["ITEM"]); expect(result.rules_executed).toHaveLength(0); expect(result.diagnoses[0].confidence).toBe("INSUFFICIENT_EVIDENCE"); });
  it("does not classify data contradictions as software defects", () => { const result = evaluateDoctor(snapshot({ grnLines: [{ received_qty: 1, accepted_qty: 2 }] }), ["GRN"]); expect(result.diagnoses.find(issue => issue.diagnosis_key === "GRN_ACCEPTED_EXCEEDS_RECEIVED")?.classification).toBe("DATA_CORRECTION_REQUIRED"); });
  it("does not mutate the supplied snapshot", () => { const value = snapshot({ grnLines: [{ received_qty: 1, accepted_qty: 2 }] }); const before = JSON.stringify(value); evaluateDoctor(value, ["GRN"]); expect(JSON.stringify(value)).toBe(before); });
  it("does not reinterpret a missing remaining quantity as a software defect", () => { const value = snapshot(); value.receipt = { open_po: true, remaining_qty: null }; expect(keys(value, "PO")).not.toContain("PO_OPEN_STATE"); });
  it("compares canonical attendance with the recorded IN and OUT punch vocabulary", () => { expect(keys(snapshot({ attendance: [{ id: "a", check_in_time: "2026-10-02T08:00:00Z" }], punches: [{ id: "p", attendance_id: "a", punch_type: "IN", punch_at: "2026-10-02T08:05:00Z" }] }), "ATTENDANCE")).toContain("ATTENDANCE_PUNCH_TIME"); });
  it("handles malformed optional import validation without fabricating required fields", () => { expect(keys(snapshot({ importRows: [{ decision: "BLOCKED", validation: {} }] }), "SMART_IMPORT")).not.toContain("IMPORT_REQUIRED_DB_FIELDS"); });
});