import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

type Dataset = 'CUSTOMERS'|'SUPPLIERS'|'ITEMS'|'BOMS'|'OPENING_BALANCES'|'INVENTORY'|'CHART_OF_ACCOUNTS'|'PURCHASE_HISTORY'|'SALES_HISTORY';
const CONFIG: Record<Dataset, { required: string[]; aliases: Record<string,string[]>; duplicate: string; table?: string; column?: string }> = {
  CUSTOMERS:{required:['customer_code','customer_name'],aliases:{customer_code:['code','customer code','customer_id'],customer_name:['name','customer name'],tax_number:['trn','gstin','vat number']},duplicate:'customer_code',table:'customers',column:'customer_code'},
  SUPPLIERS:{required:['vendor_code','vendor_name'],aliases:{vendor_code:['code','supplier code','vendor code'],vendor_name:['name','supplier name','vendor name'],tax_number:['trn','gstin','vat number']},duplicate:'vendor_code',table:'vendors',column:'vendor_code'},
  ITEMS:{required:['item_code','item_name','uom'],aliases:{item_code:['code','sku','item code'],item_name:['name','description','item name'],uom:['unit','unit of measure']},duplicate:'item_code',table:'items',column:'item_code'},
  BOMS:{required:['parent_item_code','component_item_code','quantity'],aliases:{parent_item_code:['parent','finished item'],component_item_code:['component','raw material'],quantity:['qty','component qty']},duplicate:'component_item_code'},
  OPENING_BALANCES:{required:['account_code','debit','credit'],aliases:{account_code:['ledger','account'],debit:['dr'],credit:['cr']},duplicate:'account_code'},
  INVENTORY:{required:['item_code','warehouse_code','quantity'],aliases:{item_code:['item','sku'],warehouse_code:['warehouse','location'],quantity:['qty','stock']},duplicate:'item_code'},
  CHART_OF_ACCOUNTS:{required:['account_code','account_name','account_type'],aliases:{account_code:['code','ledger code'],account_name:['name','ledger name'],account_type:['type','classification']},duplicate:'account_code',table:'accounting_accounts',column:'account_code'},
  PURCHASE_HISTORY:{required:['document_number','vendor_code','document_date','amount'],aliases:{document_number:['po number','invoice number'],vendor_code:['supplier','vendor'],document_date:['date'],amount:['total','value']},duplicate:'document_number'},
  SALES_HISTORY:{required:['document_number','customer_code','document_date','amount'],aliases:{document_number:['order number','invoice number'],customer_code:['customer'],document_date:['date'],amount:['total','value']},duplicate:'document_number'},
};

@Injectable()
export class OnboardingIntelligenceService {
  private readonly db: SupabaseClient = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_KEY!);
  private key(value:any){return String(value||'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ')}
  private text(value:any){return String(value??'').trim()}
  private approver(user:any){const roles=[user?.role,...(Array.isArray(user?.roles)?user.roles:[])].map((x:any)=>String(typeof x==='string'?x:x?.role?.name||x?.name||'').toUpperCase().replace(/[\s-]+/g,'_'));if(!roles.some((x:string)=>['SUPER_ADMIN','ADMIN','ADMINISTRATOR','FINANCE_MANAGER'].includes(x)))throw new ForbiddenException('Administrator or Finance Manager approval is required for onboarding data.');return String(user?.userId||user?.id||'')}

  async analyse(tenantId:string,userId:string,body:any){
    const dataset=String(body.dataset_type||'').toUpperCase() as Dataset, rows=Array.isArray(body.rows)?body.rows:[];
    if(!CONFIG[dataset])throw new BadRequestException('Unsupported onboarding dataset type.');
    if(!rows.length||rows.length>5000)throw new BadRequestException('Provide 1 to 5,000 rows per onboarding batch.');
    if(rows.some((row:any)=>!row||typeof row!=='object'||Array.isArray(row)))throw new BadRequestException('Every onboarding row must be an object.');
    const cfg=CONFIG[dataset],headers:string[]=Array.from(new Set<string>(rows.flatMap((row:any)=>Object.keys(row))));const mapping:Record<string,string>={};
    for(const target of [...cfg.required,...Object.keys(cfg.aliases)]){const candidates=[target,...(cfg.aliases[target]||[])].map(x=>this.key(x));const source=headers.find(header=>candidates.includes(this.key(header)));if(source)mapping[target]=source;}
    const values=rows.map((row:any)=>this.text(row[mapping[cfg.duplicate]])).filter(Boolean);let existing=new Set<string>();
    if(cfg.table&&cfg.column&&values.length){const{data}=await this.db.from(cfg.table).select(cfg.column).eq('tenant_id',tenantId).in(cfg.column,Array.from(new Set(values)).slice(0,1000));existing=new Set((data||[]).map((x:any)=>this.text(x[cfg.column!]).toUpperCase()));}
    const seen=new Set<string>();const staged:Array<{tenant_id:string;row_number:number;source_data:any;normalized_data:Record<string,any>;disposition:string;issues:any[];duplicate_key:string|null}>=rows.map((row:any,index:number)=>{const normalized:Record<string,any>={};for(const[target,source]of Object.entries(mapping))normalized[target]=row[source];const issues:any[]=[];for(const required of cfg.required)if(normalized[required]==null||this.text(normalized[required])==='')issues.push({code:'MISSING_REQUIRED',field:required});const duplicate=this.text(normalized[cfg.duplicate]).toUpperCase();if(duplicate&&(seen.has(duplicate)||existing.has(duplicate)))issues.push({code:existing.has(duplicate)?'DUPLICATE_EXISTING':'DUPLICATE_FILE',field:cfg.duplicate,value:duplicate});if(duplicate)seen.add(duplicate);const tax=this.text(normalized.tax_number);if(tax&&!/^([0-9]{15}|[0-9A-Z]{15})$/.test(tax.toUpperCase()))issues.push({code:'INVALID_TAX_NUMBER',field:'tax_number'});if(normalized.uom&&!/^[A-Za-z0-9 ./%_-]{1,20}$/.test(this.text(normalized.uom)))issues.push({code:'INVALID_UOM',field:'uom'});return{tenant_id:tenantId,row_number:index+1,source_data:row,normalized_data:normalized,disposition:issues.length?'REVIEW_REQUIRED':'AUTO_ACCEPTED',issues,duplicate_key:duplicate||null};});
    const accepted=staged.filter((x:any)=>x.disposition==='AUTO_ACCEPTED').length,review=staged.length-accepted,summary={total:staged.length,auto_accepted:accepted,review_required:review,acceptance_rate_pct:Number((accepted/staged.length*100).toFixed(1))};
    const{data:batch,error}=await this.db.from('mizantra_onboarding_batches').insert({tenant_id:tenantId,dataset_type:dataset,source_name:this.text(body.source_name)||null,status:review?'REVIEW_REQUIRED':'ANALYSED',inferred_mapping:mapping,summary,created_by:userId}).select().single();if(error)throw new BadRequestException(error.message);
    const{error:rowError}=await this.db.from('mizantra_onboarding_rows').insert(staged.map((x:any)=>({...x,batch_id:batch.id})));if(rowError)throw new BadRequestException(rowError.message);
    return{batch,summary,inferred_mapping:mapping,exceptions:staged.filter((x:any)=>x.issues.length).slice(0,200),note:'Only exceptions require human review. Accepted rows remain staged until independent approval and native import.'};
  }
  async list(tenantId:string){const{data,error}=await this.db.from('mizantra_onboarding_batches').select('*').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(100);if(error)throw new BadRequestException(error.message);return data||[]}
  async detail(tenantId:string,id:string){const[{data:batch,error},{data:rows,error:rowError}]=await Promise.all([this.db.from('mizantra_onboarding_batches').select('*').eq('tenant_id',tenantId).eq('id',id).maybeSingle(),this.db.from('mizantra_onboarding_rows').select('*').eq('tenant_id',tenantId).eq('batch_id',id).order('row_number').limit(5000)]);if(error||rowError||!batch)throw new BadRequestException(error?.message||rowError?.message||'Onboarding batch not found.');return{batch,rows:rows||[]}}
  async approve(tenantId:string,user:any,id:string){const userId=this.approver(user),{data:batch}=await this.db.from('mizantra_onboarding_batches').select('*').eq('tenant_id',tenantId).eq('id',id).maybeSingle();if(!batch)throw new BadRequestException('Onboarding batch not found.');if(batch.created_by===userId)throw new ForbiddenException('Maker-checker control prevents self-approval of onboarding data.');if(!['ANALYSED','REVIEW_REQUIRED'].includes(batch.status))throw new BadRequestException('Only an analysed batch can be approved.');const{count}=await this.db.from('mizantra_onboarding_rows').select('id',{count:'exact',head:true}).eq('tenant_id',tenantId).eq('batch_id',id).eq('disposition','REVIEW_REQUIRED');if(count)throw new BadRequestException(`${count} onboarding exception(s) must be resolved before approval.`);const{data,error}=await this.db.from('mizantra_onboarding_batches').update({status:'APPROVED',approved_by:userId,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id).select().single();if(error)throw new BadRequestException(error.message);return{batch:data,next_step:'Run the existing native module importer with the approved normalized dataset. No master or financial record was silently created.'}}
}
