import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { SalesService } from '../sales/services/sales.service';
import { VendorsService } from '../purchase/services/vendors.service';
import { ItemsService } from '../items/services/items.service';
import { BomService } from '../bom/services/bom.service';
import { AccountingService } from '../accounting/accounting.service';
import { InventoryService } from '../inventory/services/inventory.service';

type Dataset = 'CUSTOMERS'|'SUPPLIERS'|'ITEMS'|'BOMS'|'OPENING_BALANCES'|'INVENTORY'|'CHART_OF_ACCOUNTS'|'PURCHASE_HISTORY'|'SALES_HISTORY';
const CONFIG: Record<Dataset, { required: string[]; aliases: Record<string,string[]>; duplicate: string; table?: string; column?: string }> = {
  CUSTOMERS:{required:['customer_code','customer_name'],aliases:{customer_code:['code','customer code','customer_id'],customer_name:['name','customer name'],tax_number:['trn','gstin','vat number']},duplicate:'customer_code',table:'customers',column:'customer_code'},
  SUPPLIERS:{required:['vendor_code','vendor_name'],aliases:{vendor_code:['code','supplier code','vendor code'],vendor_name:['name','supplier name','vendor name'],tax_number:['trn','gstin','vat number']},duplicate:'vendor_code',table:'vendors',column:'code'},
  ITEMS:{required:['item_code','item_name','uom','category','hsn_code'],aliases:{item_code:['code','sku','item code'],item_name:['name','description','item name'],uom:['unit','unit of measure'],category:['item category','inventory category'],hsn_code:['hsn','hs code']},duplicate:'item_code',table:'items',column:'code'},
  BOMS:{required:['parent_item_code','component_item_code','quantity'],aliases:{parent_item_code:['parent','finished item'],component_item_code:['component','raw material'],quantity:['qty','component qty']},duplicate:'component_item_code'},
  OPENING_BALANCES:{required:['account_code','debit','credit','as_of_date'],aliases:{account_code:['ledger','account'],debit:['dr'],credit:['cr'],as_of_date:['date','opening date']},duplicate:'account_code'},
  INVENTORY:{required:['item_code','warehouse_code','quantity'],aliases:{item_code:['item','sku'],warehouse_code:['warehouse','location'],quantity:['qty','stock']},duplicate:'item_code'},
  CHART_OF_ACCOUNTS:{required:['account_code','account_name','account_type'],aliases:{account_code:['code','ledger code'],account_name:['name','ledger name'],account_type:['type','classification']},duplicate:'account_code',table:'accounting_accounts',column:'account_code'},
  PURCHASE_HISTORY:{required:['document_number','vendor_code','document_date','amount'],aliases:{document_number:['po number','invoice number'],vendor_code:['supplier','vendor'],document_date:['date'],amount:['total','value']},duplicate:'document_number'},
  SALES_HISTORY:{required:['document_number','customer_code','document_date','amount'],aliases:{document_number:['order number','invoice number'],customer_code:['customer'],document_date:['date'],amount:['total','value']},duplicate:'document_number'},
};

@Injectable()
export class OnboardingIntelligenceService {
  private readonly db: SupabaseClient = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_KEY!);
  constructor(private readonly sales:SalesService,private readonly vendors:VendorsService,private readonly items:ItemsService,private readonly boms:BomService,private readonly accounting:AccountingService,private readonly inventory:InventoryService){}
  private key(value:any){return String(value||'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ')}
  private text(value:any){return String(value??'').trim()}
  private approver(user:any){const roles=[user?.role,...(Array.isArray(user?.roles)?user.roles:[])].map((x:any)=>String(typeof x==='string'?x:x?.role?.name||x?.name||'').toUpperCase().replace(/[\s-]+/g,'_'));if(!roles.some((x:string)=>['SUPER_ADMIN','ADMIN','ADMINISTRATOR','FINANCE_MANAGER'].includes(x)))throw new ForbiddenException('Administrator or Finance Manager approval is required for onboarding data.');return String(user?.userId||user?.id||'')}

  async analyse(tenantId:string,userId:string,body:any){
    const dataset=String(body.dataset_type||'').toUpperCase() as Dataset, rows=Array.isArray(body.rows)?body.rows:[];
    if(!CONFIG[dataset])throw new BadRequestException('Unsupported onboarding dataset type.');
    if(!rows.length||rows.length>5000)throw new BadRequestException('Provide 1 to 5,000 rows per onboarding batch.');
    if(rows.some((row:any)=>!row||typeof row!=='object'||Array.isArray(row)))throw new BadRequestException('Every onboarding row must be an object.');
    const cfg=CONFIG[dataset],headers:string[]=Array.from(new Set<string>(rows.flatMap((row:any)=>Object.keys(row))));const mapping:Record<string,string>={};
    for(const target of [...cfg.required,...Object.keys(cfg.aliases)]){const candidates=[target,...(cfg.aliases[target]||[])].map(x=>this.key(x));const source=headers.find(header=>candidates.includes(this.key(header)));if(source)mapping[target]=source;}
    const values=rows.map((row:any)=>this.text(row[mapping[cfg.duplicate]])).filter(Boolean);let existing=new Set<string>();
    if(cfg.table&&cfg.column&&values.length){const{data}=await this.db.from(cfg.table).select(cfg.column).eq('tenant_id',tenantId).in(cfg.column,Array.from(new Set(values)).slice(0,1000));existing=new Set((data||[]).map((x:any)=>this.text(x[cfg.column!]).toUpperCase()));}
    const seen=new Set<string>();const staged:Array<{tenant_id:string;row_number:number;source_data:any;normalized_data:Record<string,any>;disposition:string;issues:any[];duplicate_key:string|null}>=rows.map((row:any,index:number)=>{const normalized:Record<string,any>={};for(const[target,source]of Object.entries(mapping))normalized[target]=row[source];const issues:any[]=[];for(const required of cfg.required)if(normalized[required]==null||this.text(normalized[required])==='')issues.push({code:'MISSING_REQUIRED',field:required});const duplicate=this.text(normalized[cfg.duplicate]).toUpperCase();if(duplicate&&(seen.has(duplicate)||existing.has(duplicate)))issues.push({code:existing.has(duplicate)?'DUPLICATE_EXISTING':'DUPLICATE_FILE',field:cfg.duplicate,value:duplicate});if(duplicate)seen.add(duplicate);const tax=this.text(normalized.tax_number);if(tax&&!/^([0-9]{15}|[0-9A-Z]{15})$/.test(tax.toUpperCase()))issues.push({code:'INVALID_TAX_NUMBER',field:'tax_number'});if(normalized.uom&&!/^[A-Za-z0-9 ./%_-]{1,20}$/.test(this.text(normalized.uom)))issues.push({code:'INVALID_UOM',field:'uom'});return{tenant_id:tenantId,row_number:index+1,source_data:row,normalized_data:normalized,disposition:issues.length?'REVIEW_REQUIRED':'AUTO_ACCEPTED',issues,duplicate_key:duplicate||null};});
    const accepted=staged.filter((x:any)=>x.disposition==='AUTO_ACCEPTED').length,review=staged.length-accepted,summary={total:staged.length,auto_accepted:accepted,review_required:review,acceptance_rate_pct:Number((accepted/staged.length*100).toFixed(1))};
    const{data:batch,error}=await this.db.from('mizantra_onboarding_batches').insert({tenant_id:tenantId,dataset_type:dataset,source_name:this.text(body.source_name)||null,status:review?'REVIEW_REQUIRED':'ANALYSED',inferred_mapping:mapping,summary,created_by:userId}).select().single();if(error)throw new BadRequestException(error.message);
    const{error:rowError}=await this.db.from('mizantra_onboarding_rows').insert(staged.map((x:any)=>({...x,batch_id:batch.id})));if(rowError)throw new BadRequestException(rowError.message);
    return{batch,summary,inferred_mapping:mapping,exceptions:staged.filter((x:any)=>x.issues.length).slice(0,200),note:'Only exceptions require human review. Accepted rows remain staged until independent approval and native import.'};
  }
  async list(tenantId:string){const{data,error}=await this.db.from('mizantra_onboarding_batches').select('*').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(100);if(error)throw new BadRequestException(error.message);return data||[]}
  async detail(tenantId:string,id:string){const[{data:batch,error},{data:rows,error:rowError}]=await Promise.all([this.db.from('mizantra_onboarding_batches').select('*').eq('tenant_id',tenantId).eq('id',id).maybeSingle(),this.db.from('mizantra_onboarding_rows').select('*').eq('tenant_id',tenantId).eq('batch_id',id).order('row_number').limit(5000)]);if(error||rowError||!batch)throw new BadRequestException(error?.message||rowError?.message||'Onboarding batch not found.');return{batch,rows:rows||[]}}
  async approve(tenantId:string,user:any,id:string){const userId=this.approver(user),{data:batch}=await this.db.from('mizantra_onboarding_batches').select('*').eq('tenant_id',tenantId).eq('id',id).maybeSingle();if(!batch)throw new BadRequestException('Onboarding batch not found.');if(batch.created_by===userId)throw new ForbiddenException('Maker-checker control prevents self-approval of onboarding data.');if(!['ANALYSED','REVIEW_REQUIRED'].includes(batch.status))throw new BadRequestException('Only an analysed batch can be approved.');const{count}=await this.db.from('mizantra_onboarding_rows').select('id',{count:'exact',head:true}).eq('tenant_id',tenantId).eq('batch_id',id).eq('disposition','REVIEW_REQUIRED');if(count)throw new BadRequestException(`${count} onboarding exception(s) must be resolved before approval.`);const{data,error}=await this.db.from('mizantra_onboarding_batches').update({status:'APPROVED',approved_by:userId,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id).select().single();if(error)throw new BadRequestException(error.message);return{batch:data,next_step:'Run the existing native module importer with the approved normalized dataset. No master or financial record was silently created.'}}

  async apply(tenantId:string,user:any,id:string){
    const userId=this.approver(user),detail=await this.detail(tenantId,id),batch=detail.batch,rows=(detail.rows||[]).filter((row:any)=>row.disposition==='AUTO_ACCEPTED');
    if(batch.status==='APPLIED')return{batch,reused:true,result:batch.application_result};
    if(batch.status!=='APPROVED')throw new BadRequestException('Only an independently approved onboarding batch can be applied.');
    if(!rows.length)throw new BadRequestException('The approved batch has no accepted rows to apply.');
    const req:any={user:{...user,tenantId,userId}};const created:any[]=[];
    const normalized=(row:any)=>row.normalized_data||{};
    try{
      if(batch.dataset_type==='CUSTOMERS')for(const row of rows){const x=normalized(row),record=await this.sales.createCustomer(req,{customer_name:x.customer_name,gst_number:x.tax_number,customer_type:x.customer_type||'REGULAR',country:x.country,credit_limit:x.credit_limit,credit_days:x.credit_days});created.push({row_id:row.id,native_id:record.id,native_type:'CUSTOMER'});}
      else if(batch.dataset_type==='SUPPLIERS')for(const row of rows){const x=normalized(row),record=await this.vendors.create(tenantId,userId,{code:x.vendor_code,name:x.vendor_name,tax_id:x.tax_number,category:x.category||'MATERIAL',email:x.email,phone:x.phone,address:x.address});created.push({row_id:row.id,native_id:record.id,native_type:'SUPPLIER'});}
      else if(batch.dataset_type==='ITEMS')for(const row of rows){const x=normalized(row),record=await this.items.create(tenantId,userId,{code:x.item_code,name:x.item_name,uom:x.uom,category:x.category,hsn_code:x.hsn_code,description:x.description,reorder_level:x.reorder_level,standard_cost:x.standard_cost,item_type:x.item_type||x.category});created.push({row_id:row.id,native_id:record.id,native_type:'ITEM'});}
      else if(batch.dataset_type==='CHART_OF_ACCOUNTS')for(const row of rows){const x=normalized(row),record=await this.accounting.createAccount(tenantId,userId,{account_code:x.account_code,account_name:x.account_name,account_type:x.account_type,account_subtype:x.account_subtype,currency_code:x.currency_code});created.push({row_id:row.id,native_id:record.id,native_type:'ACCOUNT'});}
      else if(batch.dataset_type==='BOMS'){
        const groups=new Map<string,any[]>();for(const row of rows){const x=normalized(row),key=this.text(x.parent_item_code).toUpperCase(),list=groups.get(key)||[];list.push({...x,row_id:row.id});groups.set(key,list)}
        const codes=Array.from(new Set(rows.flatMap((row:any)=>[normalized(row).parent_item_code,normalized(row).component_item_code]).map((x:any)=>this.text(x).toUpperCase()).filter(Boolean)));const{data:itemRows,error:itemError}=await this.db.from('items').select('id,code').eq('tenant_id',tenantId).in('code',codes);if(itemError)throw new BadRequestException(itemError.message);const itemMap=new Map((itemRows||[]).map((x:any)=>[this.text(x.code).toUpperCase(),x.id]));
        for(const[parent,components]of groups){const parentId=itemMap.get(parent);if(!parentId)throw new BadRequestException(`BOM parent item ${parent} was not found.`);const record=await this.boms.create(tenantId,{itemId:parentId,version:Number(components[0].version||1),notes:`Onboarding batch ${id}`,items:components.map((x:any)=>({componentType:'ITEM',itemId:itemMap.get(this.text(x.component_item_code).toUpperCase()),quantity:Number(x.quantity),scrapPercentage:Number(x.scrap_percentage||0)}))});for(const x of components)created.push({row_id:x.row_id,native_id:record.id,native_type:'BOM'});}
      }else if(batch.dataset_type==='OPENING_BALANCES'){
        const codes=rows.map((row:any)=>this.text(normalized(row).account_code).toUpperCase()),{data:accounts,error}=await this.db.from('accounting_accounts').select('id,account_code').eq('tenant_id',tenantId).in('account_code',codes);if(error)throw new BadRequestException(error.message);const accountMap=new Map((accounts||[]).map((x:any)=>[this.text(x.account_code).toUpperCase(),x.id]));const first=normalized(rows[0]);const record=await this.accounting.createOpeningBalanceBatch(tenantId,user,{batch_number:`OB-ONB-${String(id).slice(0,8).toUpperCase()}`,as_of_date:first.as_of_date,source_reference:`Mizantra onboarding ${id}`,lines:rows.map((row:any)=>{const x=normalized(row);return{account_id:accountMap.get(this.text(x.account_code).toUpperCase()),description:x.description,debit:Number(x.debit||0),credit:Number(x.credit||0)}})});for(const row of rows)created.push({row_id:row.id,native_id:record.id,native_type:'OPENING_BALANCE_BATCH'});
      }else if(batch.dataset_type==='INVENTORY'){
        const itemCodes=rows.map((row:any)=>this.text(normalized(row).item_code).toUpperCase()),warehouseCodes=rows.map((row:any)=>this.text(normalized(row).warehouse_code).toUpperCase());const[{data:itemRows,error:itemError},{data:warehouseRows,error:warehouseError}]=await Promise.all([this.db.from('items').select('id,code,category').eq('tenant_id',tenantId).in('code',itemCodes),this.db.from('warehouses').select('*').eq('tenant_id',tenantId)]);if(itemError||warehouseError)throw new BadRequestException(itemError?.message||warehouseError?.message);const itemMap=new Map((itemRows||[]).map((x:any)=>[this.text(x.code).toUpperCase(),x])),warehouseMap=new Map((warehouseRows||[]).flatMap((x:any)=>[[this.text(x.code).toUpperCase(),x.id],[this.text(x.warehouse_code).toUpperCase(),x.id]]).filter(([key]:any)=>key));for(const row of rows){const x=normalized(row),item=itemMap.get(this.text(x.item_code).toUpperCase()),warehouse=warehouseMap.get(this.text(x.warehouse_code).toUpperCase());if(!item||!warehouse)throw new BadRequestException(`Opening stock row ${row.row_number} has an unmapped item or warehouse.`);const record=await this.inventory.createStockMovement(req,{movement_type:'ADJUSTMENT',item_id:item.id,to_warehouse_id:warehouse,quantity:Number(x.quantity),category:item.category,reference_type:'ONBOARDING_OPENING_STOCK',reference_number:`ONB-${String(id).slice(0,8)}-${row.row_number}`,notes:`Approved onboarding batch ${id}`});created.push({row_id:row.id,native_id:record.id,native_type:'STOCK_MOVEMENT'});}
      }else if(['PURCHASE_HISTORY','SALES_HISTORY'].includes(batch.dataset_type)){
        const direction=batch.dataset_type==='PURCHASE_HISTORY'?'PURCHASE':'SALE',payload=rows.map((row:any)=>{const x=normalized(row);return{tenant_id:tenantId,onboarding_batch_id:id,direction,document_number:x.document_number,party_code:x.vendor_code||x.customer_code,document_date:x.document_date,amount:Number(x.amount),currency_code:x.currency_code||'AED',source_data:row.source_data,imported_by:userId}});const{data,error}=await this.db.from('mizantra_historical_transactions').upsert(payload,{onConflict:'tenant_id,direction,document_number',ignoreDuplicates:true}).select();if(error)throw new BadRequestException(error.message);for(const row of data||[])created.push({native_id:row.id,native_type:'HISTORICAL_EVIDENCE'});
      }else throw new BadRequestException('No native onboarding executor is registered for this dataset.');
      if(created.length){await this.db.from('mizantra_onboarding_rows').update({disposition:'APPLIED'}).eq('tenant_id',tenantId).eq('batch_id',id).eq('disposition','AUTO_ACCEPTED');}
      const result={dataset_type:batch.dataset_type,applied_count:created.length,native_records:created};const{data,error}=await this.db.from('mizantra_onboarding_batches').update({status:'APPLIED',application_result:result,applied_by:userId,applied_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id).eq('status','APPROVED').select().single();if(error)throw new BadRequestException(error.message);return{batch:data,reused:false,result,control:'Native masters remain subject to their normal verification controls. Opening balances remain DRAFT. Historical evidence does not post operational or financial transactions.'};
    }catch(error:any){
      const partial={dataset_type:batch.dataset_type,applied_count:created.length,native_records:created,error:this.text(error?.message||error),stopped_at:new Date().toISOString()};
      if(created.length){const appliedRowIds=created.map((record:any)=>record.row_id).filter(Boolean);if(appliedRowIds.length)await this.db.from('mizantra_onboarding_rows').update({disposition:'APPLIED'}).eq('tenant_id',tenantId).eq('batch_id',id).in('id',appliedRowIds);await this.db.from('mizantra_onboarding_batches').update({application_result:partial,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id);}
      throw new BadRequestException(`Onboarding application stopped after ${created.length} row(s): ${error?.message||error}. Applied native records are preserved in the batch audit and are excluded from retry.`)
    }
  }
}
