import { ProactiveOperationsService, localBriefClock } from './proactive-operations.service';
import { candidate } from './proactive-operations.registry';

const tenant = '11111111-1111-4111-8111-111111111111', owner = '22222222-2222-4222-8222-222222222222', id = '33333333-3333-4333-8333-333333333333';
let mockItems: any[] = [], mockEvents: any[] = [], mockRpcResult: any = {}, mockTimezone = 'UTC';
const mockRpc = jest.fn(async (_name: string, _payload: any) => ({ data: mockRpcResult }));
const mockMutation = jest.fn(async (_table: string, _payload: any) => ({ data: null }));
const mockTraces: any[] = [];
const mockDb = { rpc: mockRpc, from: (table: string) => {
  const trace = { table, filters: [] as any[], mutation: null as any }; mockTraces.push(trace);
  const query: any = { select: () => query, eq: (key: string, value: any) => { trace.filters.push([key, value]); return query; }, order: () => query, limit: () => query, is: () => query, gte: () => query, maybeSingle: () => query, upsert: (value: any) => { trace.mutation = value; return query; }, update: (value: any) => { trace.mutation = value; return query; }, then: (resolve: any, reject: any) => { if (trace.mutation) mockMutation(table, trace.mutation); const data = table === 'mizantra_attention_items' ? trace.filters.some(([key]) => key === 'id') ? mockItems.find(item => trace.filters.every(([key, value]) => item[key] === value)) || null : mockItems : table === 'mizantra_attention_events' ? mockEvents : table === 'mizantra_attention_preferences' ? { timezone: mockTimezone } : table === 'mizantra_attention_notifications' ? [] : null; return Promise.resolve({ data }).then(resolve, reject); } }; return query;
} };
jest.mock('@supabase/supabase-js', () => ({ createClient: () => mockDb }));
describe('Scoped briefing orchestration', () => {
  const user = { id: owner, tenantId: tenant, role: { name: 'USER' }, permissions: ['items:read', 'inventory:read'] };
  let operations: ProactiveOperationsService, sources: any, operator: any;
  const stored = (extra: any = {}) => ({ id, tenant_id: tenant, profile: 'MIZANTRA', owner_id: owner, attention_key: 'ITEM_BELOW_REORDER:' + id, category: 'ITEM_BELOW_REORDER', entity_id: id, entity_type: 'ITEM', module: 'Inventory', severity: 'MEDIUM', status: 'ACTIVE', required_permission: 'inventory:read', title: 'Item below reorder', explanation: 'Recorded evidence only', evidence: { current_stock: 3, reorder_level: 10, required_read: 'items:read' }, ...extra });
  beforeEach(() => { process.env.ERP_TENANT_PROFILE = 'MIZANTRA'; process.env.MIZANTRA_PROACTIVE_OPERATIONS_ENABLED = 'true'; process.env.MIZANTRA_DAILY_BRIEF_ENABLED = 'true'; process.env.MIZANTRA_PROACTIVE_NOTIFICATIONS_ENABLED = 'true'; mockItems = [stored()]; mockEvents = []; mockTimezone = 'UTC'; mockRpcResult = {}; mockRpc.mockClear(); mockMutation.mockClear(); mockTraces.length = 0; sources = { scan: jest.fn(async () => ({ items: [], complete_rules: [], errors: [] })) }; operator = { interpret: jest.fn(async () => ({ action_operator_plan: { status: 'NEEDS_INPUT' } })), execute: jest.fn(), approve: jest.fn() }; operations = new ProactiveOperationsService(sources, operator); });
  afterEach(() => { expect(operator.execute).not.toHaveBeenCalled(); expect(operator.approve).not.toHaveBeenCalled(); expect(mockTraces.filter(trace => trace.mutation).every(trace => ['mizantra_attention_preferences', 'mizantra_attention_notifications'].includes(trace.table))).toBe(true); });
  it('filters both native permissions on every metadata read', async () => { expect((await operations.list({ ...user, permissions: ['items:read'] })).items).toEqual([]); });
  it('derives Diagnose target only from owned attention metadata', async () => {
    mockItems = [stored({ category: 'OVERDUE_OPEN_PO', entity_type: 'PO', entity_reference: 'PO-2026-05-023', required_permission: 'purchase_orders:read', evidence: {}, available_actions: [{ label: 'Diagnose', kind: 'ASK' }] })];
    const result = await operations.handoff({ ...user, permissions: ['purchase_orders:read'] }, id, { action: 'DATA_DOCTOR' });
    expect(result).toMatchObject({ source: 'PROACTIVE_OPERATIONS', action: 'DATA_DOCTOR', attention_id: id, entity_id: id, entity_type: 'purchase_order', entity_reference: 'PO-2026-05-023', tenant, profile: 'MIZANTRA', owner_id: owner, executable: false });
    expect(mockRpc).not.toHaveBeenCalled();
  });
  it('issues an exact read-only GRN review handoff only to an authorized approver', async () => {
    mockItems = [stored({ category: 'GRN_REJECTION_REQUIRES_ATTENTION', entity_type: 'GRN', entity_reference: 'GRN-2026-07-169', required_permission: 'grns:read', evidence: { rejected_qty: 10 }, available_actions: [{ label: 'Review', kind: 'VIEW' }] })];
    const authorized = { ...user, permissions: ['grns:read', 'grns:approve'] };
    const handoff = await operations.handoff(authorized, id, { action: 'SMART_APPROVAL_REVIEW' });
    expect(handoff).toMatchObject({ source: 'PROACTIVE_OPERATIONS', action: 'SMART_APPROVAL_REVIEW', attention_id: id, entity_type: 'grn', entity_id: id, entity_reference: 'GRN-2026-07-169', tenant, profile: 'MIZANTRA', executable: false });
    expect(mockRpc).not.toHaveBeenCalled();
    await expect(operations.handoff({ ...user, permissions: ['grns:read'] }, id, { action: 'SMART_APPROVAL_REVIEW' })).rejects.toThrow('not available');
    mockItems[0].tenant_id = 'foreign';
    await expect(operations.handoff(authorized, id, { action: 'SMART_APPROVAL_REVIEW' })).rejects.toThrow('not available');
  });
  it.each([{ tenant_id: 'foreign' }, { profile: 'ARWA' }, { owner_id: 'foreign' }])('rejects foreign attention handoff %j', async extra => {
    mockItems = [stored(extra)];
    await expect(operations.handoff(user, id, { action: 'WHY' })).rejects.toThrow('not available');
  });
  it('revalidates revoked attention permissions before handoff', async () => { await expect(operations.handoff({ ...user, permissions: [] }, id, { action: 'WHY' })).rejects.toThrow('not available'); });
  it('rejects a client target/scope override instead of merging it', async () => { await expect(operations.handoff(user, id, { action: 'WHY', tenant: 'foreign', entity_id: 'old-report' })).rejects.toThrow('Only a registered'); });
  it('rejects unregistered execution actions', async () => { await expect(operations.handoff(user, id, { action: 'EXECUTE' })).rejects.toThrow('not available'); });
  it('hides cached PO receipt evidence after GRN permission is revoked', async () => { mockItems = [stored({ category: 'OVERDUE_OPEN_PO', required_permission: 'purchase_orders:read', evidence: { required_read: 'grns:read', remaining_qty: 30 } })]; expect((await operations.list({ ...user, permissions: ['purchase_orders:read'] })).items).toEqual([]); });
  it('filters cross-tenant metadata even if a source returns it', async () => { mockItems = [stored({ tenant_id: 'foreign' })]; expect((await operations.list(user)).items).toEqual([]); });
  it('filters cross-profile metadata', async () => { mockItems = [stored({ profile: 'ARWA' })]; expect((await operations.list(user)).items).toEqual([]); });
  it('filters another audience in the same tenant', async () => { mockItems = [stored({ owner_id: 'foreign' })]; expect((await operations.list(user)).items).toEqual([]); });
  it('retains private owner-only requirements', async () => { mockItems = [stored({ required_permission: 'OWNER', evidence: { owner_id: owner } })]; expect((await operations.list(user)).items).toHaveLength(1); mockItems[0].evidence.owner_id = 'foreign'; expect((await operations.list(user)).items).toHaveLength(0); });
  it('persists only registered scoped scan data', async () => { sources.scan.mockResolvedValue({ items: [candidate('ITEM_BELOW_REORDER', { id, code: 'RAW-1' }, { module: 'Inventory', entity_type: 'ITEM', source: 'ERP', permission: 'inventory:read', severity: 'MEDIUM', title: 'Below reorder', explanation: 'Recorded', evidence: { current_stock: 3 }, due_date: null, available_actions: [] })], complete_rules: ['ITEM_BELOW_REORDER'], errors: [] }); await operations.refresh(user); expect(mockRpc).toHaveBeenCalledWith('mizantra_attention_reconcile', expect.objectContaining({ p_tenant: tenant, p_owner: owner, p_profile: 'MIZANTRA' })); });
  it('rejects unregistered rules before persistence', async () => { sources.scan.mockResolvedValue({ items: [{ category: 'OPAQUE_AI_SCORE', attention_key: 'unknown' }], complete_rules: [], errors: [] }); await expect(operations.refresh(user)).rejects.toThrow('unregistered'); expect(mockRpc).not.toHaveBeenCalled(); });
  it('rejects a foreign-owner candidate before deduplication or persistence', async () => { sources.scan.mockResolvedValue({ items: [{ category: 'SMART_IMPORT_REVIEW', permission: 'OWNER', evidence: { owner_id: 'foreign' } }], complete_rules: [], errors: [] }); await expect(operations.refresh(user)).rejects.toThrow('unauthorized'); expect(mockRpc).not.toHaveBeenCalled(); });
  it('acknowledges only the scoped item', async () => { await operations.state(user, id, 'ACKNOWLEDGED'); expect(mockRpc).toHaveBeenCalledWith('mizantra_attention_state', expect.objectContaining({ p_id: id, p_status: 'ACKNOWLEDGED', p_owner: owner })); });
  it('dismiss never mutates or resolves ERP state', async () => { await operations.state(user, id, 'DISMISSED'); expect(mockRpc.mock.calls[0][0]).toBe('mizantra_attention_state'); });
  it('does not allow user-driven resolution', async () => { await expect(operations.state(user, id, 'RESOLVED')).rejects.toThrow('acknowledge or dismiss'); });
  it('builds a deterministic daily brief', async () => { const brief = await operations.brief(user); expect(brief.categories).toEqual([{ module: 'Inventory', count: 1 }]); expect(brief.assurance).toBe('No business actions were taken.'); expect(mockRpc).toHaveBeenCalledWith('mizantra_attention_brief', expect.objectContaining({ p_ids: [id], p_timezone: 'UTC' })); });
  it('does not persist disabled daily briefs', async () => { process.env.MIZANTRA_DAILY_BRIEF_ENABLED = 'false'; await operations.brief(user); expect(mockRpc).not.toHaveBeenCalled(); });
  it('filters changed-since history by current authorization', async () => { mockEvents = [{ attention_id: id, event: 'NEW' }, { attention_id: 'foreign', event: 'RESOLVED' }]; expect((await operations.changes(user)).changes).toHaveLength(1); expect((await operations.changes({ ...user, permissions: [] })).changes).toHaveLength(0); });
  it('revalidates Why and returns deterministic evidence', async () => { sources.scan.mockResolvedValue({ items: [], complete_rules: ['ITEM_BELOW_REORDER'], errors: [] }); const why = await operations.why(user, id); expect(sources.scan).toHaveBeenCalled(); expect(why.explanation).toBe('Recorded evidence only'); expect(why.executable).toBe(false); expect(why.evidence.current_stock).toBe(3); });
  it('does not call a skipped source revalidated', async () => { const why = await operations.why(user, id); expect(why.evidence.source_freshness).toBe('NOT_REVALIDATED'); });
  it('labels retained Why evidence when source revalidation is incomplete', async () => { sources.scan.mockResolvedValue({ items: [], complete_rules: [], errors: ['ITEM_BELOW_REORDER:SOURCE_UNAVAILABLE_OR_INCOMPLETE'] }); const why = await operations.why(user, id); expect(why.evidence.source_freshness).toBe('NOT_REVALIDATED'); expect(why.explanation).toContain('last recorded evidence'); });
  it('blocks preview preparation when reorder evidence cannot be refreshed', async () => { sources.scan.mockResolvedValue({ items: [], complete_rules: [], errors: ['ITEM_BELOW_REORDER:SOURCE_UNAVAILABLE_OR_INCOMPLETE'] }); await expect(operations.preparePlan(user, id)).rejects.toThrow('No plan was prepared'); expect(operator.interpret).not.toHaveBeenCalled(); });
  it('prepares only an Operator preview without quantity or execution', async () => { const result = await operations.preparePlan(user, id); expect(result?.action_operator_plan.status).toBe('NEEDS_INPUT'); expect(operator.interpret).toHaveBeenCalledWith(user, expect.objectContaining({ message: 'Create a PR for this item', brain_context: expect.objectContaining({ entity_id: id, tenant_id: tenant }) })); expect(operator.interpret.mock.calls[0][1].inputs).toBeUndefined(); });
  it('blocks planning for resolved attention', async () => { mockItems = [stored({ status: 'RESOLVED' })]; await expect(operations.preparePlan(user, id)).rejects.toThrow('active authorized'); });
  it('routes attention but preserves other Brain intents', async () => { expect(await operations.interpret(user, { message: 'Create a PR' })).toBeNull(); const result = await operations.interpret(user, { message: 'What needs my attention today?' }); expect(result?.safety.executable).toBe(false); expect(result?.proactive_brief?.items).toHaveLength(1); });
  it('blocks forged Brain context on briefing requests', async () => { await expect(operations.interpret(user, { message: 'Give me my morning brief', brain_context: { tenant_id: 'foreign' } })).rejects.toThrow('authenticated scope'); });
  it('does not activate for Saif even if raw flags are true', async () => { process.env.ERP_TENANT_PROFILE = 'SAIFSEAS'; expect(operations.configuration(user).enabled).toBe(false); await expect(operations.list(user)).rejects.toThrow('unavailable'); });
  it('validates configured IANA timezone', async () => { mockTimezone = 'Not/AZone'; await expect(operations.timezone(user)).rejects.toThrow('valid briefing timezone'); });
  it('restricts health to native admins', async () => { await expect(operations.health(user)).rejects.toThrow('Admin'); });
  it('uses timezone-local calendar and morning clock', () => { expect(localBriefClock('Asia/Dubai', new Date('2026-10-03T04:00:00Z'))).toEqual({ date: '2026-10-03', hour: 8 }); });
});
