export type ReviewDocument = "purchase_requisition" | "purchase_order" | "grn" | "payslip";
type Row = Record<string, any>;
export type ReviewItem = { check_key: string; category: string; severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO"; title: string; business_explanation: string; evidence: Row; related_entities: Row[]; confidence: "CONFIRMED" | "LIKELY" | "POSSIBLE" | "INSUFFICIENT_EVIDENCE"; source: string; timestamp: string; outcome: "NO_ISSUE_DETECTED" | "INFORMATION" | "ATTENTION_REQUIRED" | "CRITICAL_DATA_INCONSISTENCY" };
export type ReviewSnapshot = { type: ReviewDocument; root: Row; datasets: Record<string, Row[] | undefined>; receipt?: Row; doctor?: Row[]; qa?: Row[]; related: Row[]; timestamp: string };
type Finding = { evidence: Row; explanation: string; attention?: boolean; critical?: boolean; possible?: boolean; insufficient?: boolean; severity?: ReviewItem["severity"]; confidence?: ReviewItem["confidence"] };
export type ApprovalCheck = { document_type: ReviewDocument; check_key: string; category: string; title: string; required_permissions: string[]; required_evidence: string[]; runner: (snapshot: ReviewSnapshot) => Finding[]; formatter: (finding: Finding, snapshot: ReviewSnapshot) => ReviewItem };
const number = (value: unknown): number | null => value == null || value === "" || !Number.isFinite(Number(value)) ? null : Number(value);
const normalized = (value: unknown) => String(value ?? "").trim().normalize("NFKC").toUpperCase();
const rows = (snapshot: ReviewSnapshot, key: string) => snapshot.datasets[key] || [];
const result = (evidence: Row, explanation: string, extra: Partial<Finding> = {}): Finding => ({ evidence, explanation, ...extra });
const grouped = (records: Row[], field: string) => { const groups = new Map<string, Row[]>(); for (const record of records) { const key = normalized(record[field]); if (!key) continue; groups.set(key, [...(groups.get(key) || []), record]); } return [...groups.values()].filter(group => group.length > 1); };

export function comparePurchasePrice(current: Row, previous: Row | undefined) {
  if (!previous) return { status: "INSUFFICIENT_EVIDENCE", reason: "No authorized prior purchase with a recorded date is available." };
  if (!current.tenant_id || current.tenant_id !== previous.tenant_id) return { status: "NOT_COMPARABLE", reason: "Matching authoritative tenant identity is required." };
  if (!current.item_id || current.item_id !== previous.item_id) return { status: "NOT_COMPARABLE", reason: "Item identity differs." };
  if (!normalized(current.uom) || normalized(current.uom) !== normalized(previous.uom)) return { status: "NOT_COMPARABLE", reason: "Units differ or are not explicitly recorded; no authoritative conversion was supplied." };
  if (!normalized(current.currency) || normalized(current.currency) !== normalized(previous.currency)) return { status: "NOT_COMPARABLE", reason: "Currencies differ or are not explicitly recorded; no authoritative FX conversion was supplied." };
  const currentPrice = number(current.rate), previousPrice = number(previous.rate);
  if (currentPrice === null || currentPrice < 0 || previousPrice === null || previousPrice <= 0) return { status: "NOT_COMPARABLE", reason: "A finite non-negative current price and positive previous price are required." };
  return { status: "COMPARABLE", current_price: currentPrice, previous_price: previousPrice, currency: normalized(current.currency), uom: normalized(current.uom), difference_percent: ((currentPrice - previousPrice) / previousPrice) * 100, historical_date: previous.po_date, previous_po: previous.po_number, previous_po_id: previous.po_id, supplier_id: previous.vendor_id };
}

function check(document_type: ReviewDocument, key: string, category: string, title: string, required_evidence: string[], runner: ApprovalCheck["runner"]): ApprovalCheck {
  return { document_type, check_key: `${document_type.toUpperCase()}_${key}`, category, title, required_permissions: [document_type === "grn" ? "grns:read" : document_type === "purchase_order" ? "purchase_orders:read" : "purchase_requisitions:read"], required_evidence, runner,
    formatter: (finding, snapshot) => ({ check_key: `${document_type.toUpperCase()}_${key}`, category, severity: finding.insufficient ? "INFO" : finding.severity || (finding.critical ? "CRITICAL" : finding.attention ? "MEDIUM" : "INFO"), title, business_explanation: finding.explanation, evidence: finding.evidence, related_entities: snapshot.related, confidence: finding.insufficient ? "INSUFFICIENT_EVIDENCE" : finding.confidence || (finding.possible ? "POSSIBLE" : "CONFIRMED"), source: key === "DATA_DOCTOR" ? "DATA_DOCTOR" : key === "AUTO_QA" ? "AUTO_QA" : "DETERMINISTIC_APPROVAL_CHECK", timestamp: snapshot.timestamp, outcome: finding.insufficient ? "INFORMATION" : finding.critical ? "CRITICAL_DATA_INCONSISTENCY" : finding.attention ? "ATTENTION_REQUIRED" : "NO_ISSUE_DETECTED" }) };
}
const lines = (snapshot: ReviewSnapshot) => rows(snapshot, "lines");
const identityChecks = (type: ReviewDocument) => [
  check(type, "LINES", "DOCUMENT_INTEGRITY", "Document lines", ["lines"], snapshot => [result({ line_count: lines(snapshot).length }, lines(snapshot).length ? `${lines(snapshot).length} recorded lines inspected.` : "No document lines are recorded.", { attention: !lines(snapshot).length })]),
  check(type, "ITEM_REFERENCES", "DOCUMENT_INTEGRITY", "Item references", ["lines", "items"], snapshot => { const missing = lines(snapshot).filter(line => line.item_id && !rows(snapshot, "items").some(item => item.id === line.item_id)); return [result({ unavailable_item_references: missing.map(line => ({ line_id: line.id, item_id: line.item_id })) }, missing.length ? "Some referenced items are unavailable in the authorized evidence." : "Available item references were inspected.", { insufficient: !!missing.length })]; }),
  check(type, "QUANTITIES", "DOCUMENT_INTEGRITY", "Recorded quantities", ["lines"], snapshot => { const field = type === "purchase_requisition" ? "requested_qty" : type === "purchase_order" ? "ordered_qty" : "received_qty"; const invalid = lines(snapshot).filter(line => number(line[field]) === null || Number(line[field]) <= 0); return [result({ field, invalid_line_ids: invalid.map(line => line.id) }, !lines(snapshot).length ? "There are no recorded line quantities to inspect." : invalid.length ? "Some recorded quantities are missing, non-finite or not positive." : "Recorded quantities are positive.", { attention: !!invalid.length, insufficient: !lines(snapshot).length })]; }),
];
const integrationChecks = (type: ReviewDocument) => [
  check(type, "DATA_DOCTOR", "DATA_QUALITY", "Data Doctor evidence", ["doctor"], snapshot => snapshot.doctor?.length ? snapshot.doctor.map(issue => result({ diagnosis_key: issue.diagnosis_key, facts: issue.evidence?.fact, expected: issue.expected_state, actual: issue.actual_state }, issue.explanation, { attention: issue.classification !== "NO_ISSUE", critical: issue.severity === "CRITICAL" && issue.confidence === "CONFIRMED", severity: issue.severity, confidence: issue.confidence, insufficient: issue.confidence === "INSUFFICIENT_EVIDENCE" })) : [result({ diagnostic_count: 0 }, "No Data Doctor inconsistency was detected in the inspected evidence.")]),
  check(type, "AUTO_QA", "DATA_QUALITY", "Relevant active AutoQA findings", ["qa"], snapshot => snapshot.qa?.length ? snapshot.qa.map(issue => result({ finding_id: issue.id, check_key: issue.check_key, severity: issue.severity, entity_type: issue.entity_type, entity_id: issue.entity_id }, "A relevant active Critical/High AutoQA finding is recorded; it is not an approval verdict.", { attention: true, possible: true, severity: issue.severity })) : [result({ relevant_active_findings: 0 }, "No relevant active Critical/High AutoQA finding was found in the authorized evidence.")]),
];

export const SMART_APPROVAL_CHECKS: ApprovalCheck[] = [
  ...identityChecks("purchase_requisition"),
  check("purchase_requisition", "DUPLICATE_ITEMS", "DOCUMENT_INTEGRITY", "Repeated item identities", ["lines"], snapshot => { const duplicates = grouped(lines(snapshot), "item_id"); return [result({ groups: duplicates.map(group => group.map(line => line.id)) }, duplicates.length ? "Some item identities occur on multiple lines; separate dates or requirements may be intentional." : "No repeated item identity was found.", { attention: !!duplicates.length, possible: !!duplicates.length })]; }),
  check("purchase_requisition", "REQUIRED_DATES", "DELIVERY", "Recorded required dates", ["lines"], snapshot => { const invalid = lines(snapshot).filter(line => line.required_date && !Number.isFinite(Date.parse(line.required_date))); return [result({ invalid_line_ids: invalid.map(line => line.id) }, invalid.length ? "Some supplied required dates cannot be interpreted." : "Supplied required dates are interpretable; absent dates are not assumed mandatory.", { attention: !!invalid.length })]; }),
  check("purchase_requisition", "ACTIVE_ITEMS", "ITEM", "Referenced item status", ["items"], snapshot => { const inactive = rows(snapshot, "items").filter(item => item.is_active === false); return [result({ inactive_item_ids: inactive.map(item => item.id) }, inactive.length ? "Some referenced masters are recorded as inactive." : "No recorded inactive item was found.", { attention: !!inactive.length })]; }),
  check("purchase_requisition", "LINKED_OPEN_ORDERS", "RELATIONSHIPS", "Exactly linked purchase orders", ["linkedOrders"], snapshot => [result({ po_ids: rows(snapshot, "linkedOrders").map(order => order.id), statuses: rows(snapshot, "linkedOrders").map(order => order.status) }, "These purchase orders explicitly reference this PR. Lifecycle status alone does not prove remaining receipt quantity.")]),
  ...integrationChecks("purchase_requisition"),
  ...identityChecks("purchase_order"),
  check("purchase_order", "SUPPLIER", "SUPPLIER", "Supplier relationship", ["vendors"], snapshot => [result({ vendor_id: snapshot.root.vendor_id || null, available: rows(snapshot, "vendors").some(vendor => vendor.id === snapshot.root.vendor_id) }, !snapshot.root.vendor_id ? "The PO has no recorded supplier reference." : rows(snapshot, "vendors").some(vendor => vendor.id === snapshot.root.vendor_id) ? "The supplier relationship is available." : "The supplier is unavailable in authorized evidence.", { attention: !snapshot.root.vendor_id, insufficient: !!snapshot.root.vendor_id && !rows(snapshot, "vendors").some(vendor => vendor.id === snapshot.root.vendor_id) })]),
  check("purchase_order", "DUPLICATE_NUMBER", "DOCUMENT_INTEGRITY", "Normalized PO number", ["matchingOrders"], snapshot => { const matches = rows(snapshot, "matchingOrders").filter(order => normalized(order.po_number) === normalized(snapshot.root.po_number)); return [result({ po_ids: matches.map(order => order.id) }, matches.length > 1 ? "Multiple orders share the normalized PO number." : "No duplicate normalized PO number was detected.", { attention: matches.length > 1, critical: matches.length > 1 })]; }),
  check("purchase_order", "DUPLICATE_REFERENCES", "DOCUMENT_INTEGRITY", "Repeated source PR-line references", ["lines"], snapshot => { const duplicates = grouped(lines(snapshot), "pr_item_id"); return [result({ groups: duplicates.map(group => group.map(line => line.id)) }, duplicates.length ? "Multiple PO lines reference the same PR line; review the recorded split quantities." : "No repeated source PR-line reference was detected.", { attention: !!duplicates.length })]; }),
  check("purchase_order", "PR_RELATIONSHIP", "RELATIONSHIPS", "Originating PR", ["prHeaders"], snapshot => [result({ pr_id: snapshot.root.pr_id || null, available_pr_ids: rows(snapshot, "prHeaders").map(pr => pr.id) }, !snapshot.root.pr_id ? "No originating PR is recorded; direct orders are not assumed invalid." : rows(snapshot, "prHeaders").some(pr => pr.id === snapshot.root.pr_id) ? "The originating PR relationship is found." : "The originating PR is not available in authorized evidence.", { insufficient: !!snapshot.root.pr_id && !rows(snapshot, "prHeaders").some(pr => pr.id === snapshot.root.pr_id) })]),
  check("purchase_order", "PR_QUANTITY", "RELATIONSHIPS", "Ordered versus explicitly linked requested quantity", ["lines", "prLines"], snapshot => lines(snapshot).filter(line => line.pr_item_id).map(line => { const requested = rows(snapshot, "prLines").find(prLine => prLine.id === line.pr_item_id); const linked = lines(snapshot).filter(candidate => candidate.pr_item_id === line.pr_item_id); const comparable = requested && normalized(requested.uom) && linked.every(candidate => normalized(candidate.uom) === normalized(requested.uom) && number(candidate.ordered_qty) !== null) && number(requested.requested_qty) !== null; const total = comparable ? linked.reduce((sum, candidate) => sum + Number(candidate.ordered_qty), 0) : null; return result({ po_line_id: line.id, pr_item_id: line.pr_item_id, ordered_qty: total, requested_qty: comparable ? requested.requested_qty : null }, comparable ? total! > Number(requested.requested_qty) ? "The total PO quantity linked to this PR line exceeds its recorded requested quantity. No commercial justification is inferred." : "Linked ordered quantity does not exceed recorded requested quantity." : "Comparable source PR-line quantity/UOM evidence is unavailable.", { attention: !!comparable && total! > Number(requested.requested_qty), insufficient: !comparable }); })),
  check("purchase_order", "PRICE_HISTORY", "PRICE", "Most recent comparable recorded purchase", ["pricedLines", "history"], snapshot => rows(snapshot, "pricedLines").map(line => { const historical = rows(snapshot, "history").filter(previous => previous.item_id === line.item_id && previous.po_id !== snapshot.root.id && Number.isFinite(Date.parse(previous.po_date)) && Number.isFinite(Date.parse(snapshot.root.po_date)) && Date.parse(previous.po_date) < Date.parse(snapshot.root.po_date)).sort((left, right) => Date.parse(right.po_date) - Date.parse(left.po_date)); const previous = historical.find(candidate => normalized(candidate.uom) === normalized(line.uom) && normalized(candidate.currency) === normalized(line.currency)) || historical[0]; const comparison = comparePurchasePrice(line, previous); return result({ line_id: line.id, ...comparison }, comparison.status === "COMPARABLE" ? `Current unit price is ${Math.abs(comparison.difference_percent!).toFixed(2)}% ${comparison.difference_percent! >= 0 ? "above" : "below"} the most recent comparable purchase.` : comparison.reason!, { attention: comparison.status === "COMPARABLE" && Math.abs(comparison.difference_percent!) > 0.0001, insufficient: comparison.status !== "COMPARABLE" }); })),
  check("purchase_order", "SUPPLIER_ACTIVE", "SUPPLIER", "Supplier status", ["vendors"], snapshot => { const inactive = rows(snapshot, "vendors").filter(vendor => vendor.id === snapshot.root.vendor_id && vendor.is_active === false); return [result({ inactive_supplier_ids: inactive.map(vendor => vendor.id) }, inactive.length ? "The referenced supplier is recorded as inactive." : "No recorded inactive supplier was found.", { attention: !!inactive.length })]; }),
  check("purchase_order", "SUPPLIER_ASSOCIATION", "SUPPLIER", "Recorded item-supplier associations", ["lines", "links"], snapshot => [result({ associated_item_ids: rows(snapshot, "links").filter(link => link.vendor_id === snapshot.root.vendor_id && link.is_active === true).map(link => link.item_id) }, "Recorded active item-supplier associations are shown as context. Their absence is not assumed prohibited.")]),
  check("purchase_order", "SUPPLIER_ORDER_CONTEXT", "SUPPLIER", "Other supplier open orders", ["supplierOrders", "supplierReceiptStates"], snapshot => [result({ other_order_count: rows(snapshot, "supplierReceiptStates").length, open_order_count: rows(snapshot, "supplierReceiptStates").filter(order => order.open_po === true).length, orders: rows(snapshot, "supplierReceiptStates") }, "Other supplier open orders are counted using the ERP's authoritative receipt calculation, excluding this PO. No subjective supplier grade or future prediction is made.")]),
  check("purchase_order", "DELIVERY_DATES", "DELIVERY", "Required and recorded delivery dates", ["lines", "prLines"], snapshot => lines(snapshot).flatMap(line => { const prLine = rows(snapshot, "prLines").find(candidate => candidate.id === line.pr_item_id); const required = Date.parse(prLine?.required_date), promised = Date.parse(line.delivery_date || snapshot.root.delivery_date); if (!prLine || !Number.isFinite(required) || !Number.isFinite(promised)) return [result({ line_id: line.id }, "Both recorded required and delivery dates are needed for a factual date comparison.", { insufficient: true })]; const days = (promised - required) / 86400000; return [result({ line_id: line.id, required_date: prLine.required_date, delivery_date: line.delivery_date || snapshot.root.delivery_date, difference_days: days }, days > 0 ? `The recorded delivery date is ${days} days after the required date.` : "The recorded delivery date is on or before the required date.", { attention: days > 0 })]; })),
  check("purchase_order", "RECEIPT_STATE", "RECEIPTS", "Authoritative receipt state", ["receipt"], snapshot => [result({ ...snapshot.receipt }, "Recorded receipt quantities and the existing authoritative open-order calculation are shown as facts.")]),
  ...integrationChecks("purchase_order"),
  ...identityChecks("grn"),
  check("grn", "SOURCE_PO", "RELATIONSHIPS", "Source purchase order", ["poHeaders"], snapshot => [result({ po_id: snapshot.root.po_id || null, available_po_ids: rows(snapshot, "poHeaders").map(order => order.id) }, rows(snapshot, "poHeaders").some(order => order.id === snapshot.root.po_id) ? "The source PO relationship is found." : "The source PO relationship is unavailable in authorized evidence.", { insufficient: !rows(snapshot, "poHeaders").some(order => order.id === snapshot.root.po_id) })]),
  check("grn", "PO_LINE_RELATIONSHIP", "RELATIONSHIPS", "Receipt source-line relationships", ["lines", "poLines"], snapshot => { const missing = lines(snapshot).filter(line => !rows(snapshot, "poLines").some(poLine => poLine.id === line.po_item_id && poLine.po_id === snapshot.root.po_id)); return [result({ unavailable_line_ids: missing.map(line => line.id) }, missing.length ? "Some receipt lines have no available matching line on the recorded source PO." : "Receipt lines map to available source PO lines.", { insufficient: !!missing.length })]; }),
  check("grn", "DUPLICATE_PO_ITEM", "DOCUMENT_INTEGRITY", "Repeated PO item in receipt", ["lines"], snapshot => { const duplicates = grouped(lines(snapshot), "po_item_id"); return [result({ groups: duplicates.map(group => group.map(line => line.id)), diagnosis_key: "GRN_DUPLICATE_PO_ITEM" }, duplicates.length ? "The receipt contains repeated PO item references." : "No repeated PO item reference was detected.", { attention: !!duplicates.length })]; }),
  check("grn", "ORDERED_QUANTITY", "RECEIPTS", "Received versus recorded ordered quantity", ["lines", "poLines"], snapshot => lines(snapshot).map(line => { const ordered = rows(snapshot, "poLines").find(candidate => candidate.id === line.po_item_id); return result({ line_id: line.id, received_qty: line.received_qty, ordered_qty: ordered?.ordered_qty ?? null }, ordered && Number(line.received_qty) > Number(ordered.ordered_qty) ? "Recorded receipt exceeds the original ordered quantity. Over-delivery tolerance and prior receipts must be reviewed; this alone does not establish an invalid receipt." : "Receipt and ordered quantities are shown without inferring over-delivery policy.", { attention: !!ordered && Number(line.received_qty) > Number(ordered.ordered_qty), possible: !!ordered && Number(line.received_qty) > Number(ordered.ordered_qty), insufficient: !ordered }); })),
  check("grn", "ACCEPTED_QUANTITY", "DATA_QUALITY", "Accepted versus received quantity", ["lines"], snapshot => lines(snapshot).filter(line => number(line.accepted_qty) !== null && number(line.received_qty) !== null && Number(line.accepted_qty) > Number(line.received_qty)).map(line => result({ line_id: line.id, diagnosis_key: "GRN_ACCEPTED_EXCEEDS_RECEIVED", accepted_qty: line.accepted_qty, received_qty: line.received_qty }, "Recorded accepted quantity exceeds physical received quantity.", { attention: true }))),
  check("grn", "REJECTED_QUANTITY", "DATA_QUALITY", "Rejected versus received quantity", ["lines"], snapshot => lines(snapshot).filter(line => number(line.rejected_qty) !== null && number(line.received_qty) !== null && Number(line.rejected_qty) > Number(line.received_qty)).map(line => result({ line_id: line.id, diagnosis_key: "GRN_REJECTED_EXCEEDS_RECEIVED", rejected_qty: line.rejected_qty, received_qty: line.received_qty }, "Recorded rejected quantity exceeds physical received quantity.", { attention: true }))),
  check("grn", "QC_SPLIT", "DATA_QUALITY", "Recorded QC split", ["lines"], snapshot => lines(snapshot).filter(line => [line.accepted_qty, line.rejected_qty, line.received_qty].every(value => number(value) !== null) && Number(line.accepted_qty) + Number(line.rejected_qty) > Number(line.received_qty)).map(line => result({ line_id: line.id, diagnosis_key: "GRN_QC_QUANTITY_SUM", accepted_qty: line.accepted_qty, rejected_qty: line.rejected_qty, received_qty: line.received_qty }, "Accepted plus rejected quantity exceeds the physical receipt.", { attention: true }))),
  check("grn", "QC_STATUS", "QC", "Recorded QC status", ["lines"], snapshot => [result({ statuses: lines(snapshot).map(line => ({ line_id: line.id, qc_status: line.qc_status })) }, "Recorded QC states are shown without changing the QC or stock workflow.")]),
  ...integrationChecks("grn"),
];

export function evaluateApproval(snapshot: ReviewSnapshot) {
  const items: ReviewItem[] = [], checks: string[] = [];
  for (const check of SMART_APPROVAL_CHECKS.filter(candidate => candidate.document_type === snapshot.type)) {
    checks.push(check.check_key);
    const missing = check.required_evidence.filter(key => snapshot.datasets[key] === undefined);
    const findings = missing.length ? [result({ missing_evidence: missing }, "Complete authorized evidence is unavailable for this check.", { insufficient: true })] : check.runner(snapshot);
    for (const finding of findings) items.push(check.formatter(finding, snapshot));
  }
  const doctorKeys = new Set(items.filter(item => item.check_key.endsWith("_DATA_DOCTOR") && item.outcome !== "NO_ISSUE_DETECTED").map(item => item.evidence.diagnosis_key).filter(key => typeof key === "string" && key.length > 0));
  const doctorAliases: Record<string, string> = { PURCHASE_ORDER_LINES: "PO_ZERO_LINES", PURCHASE_ORDER_SUPPLIER: "PO_SUPPLIER_REFERENCE", PURCHASE_ORDER_DUPLICATE_NUMBER: "PO_DUPLICATE_NUMBER", PURCHASE_ORDER_PR_RELATIONSHIP: "PO_ORIGIN_REFERENCE", PURCHASE_ORDER_ITEM_REFERENCES: "PO_LINE_ITEM_REFERENCE", GRN_ORDERED_QUANTITY: "GRN_PO_QUANTITY", GRN_PO_LINE_RELATIONSHIP: "GRN_ORPHAN_PO_ITEM" };
  const seen = new Set<string>();
  const deduplicated = items.filter(item => { if (item.source !== "DATA_DOCTOR" && doctorKeys.has(item.evidence.diagnosis_key || item.evidence.check_key || doctorAliases[item.check_key])) return false; const identity = item.source === "AUTO_QA" && item.evidence.check_key ? [item.evidence.check_key, item.evidence.entity_type, item.evidence.entity_id] : item.evidence; const key = JSON.stringify([item.check_key, identity]); if (seen.has(key)) return false; seen.add(key); return true; });
  return { items: deduplicated, checks_executed: checks };
}
