"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { BarChart3, CalendarClock, GitBranch, Loader2, Mail, MapPinned, Megaphone, Plus, RefreshCw, Settings2, X } from "lucide-react";
import { apiClient } from "../../../../lib/api-client";

type User = { id: string; name: string; email?: string };
type Lead = { id: string; lead_number: string; company_name: string };
type Mode = "forecast" | "cadences" | "campaigns" | "territories" | "templates" | "automation" | "communications";
type Workspace = { month: string; territories: any[]; targets: any[]; scorecards: any[]; items: any[]; campaigns: any[]; cadences: any[]; templates: any[]; workflows: any[]; opportunities: any[]; communications: any[]; analytics: any };
const empty: Workspace = { month: new Date().toISOString().slice(0,7), territories: [], targets: [], scorecards: [], items: [], campaigns: [], cadences: [], templates: [], workflows: [], opportunities: [], communications: [], analytics: {} };
const input = "w-full rounded-xl border border-[#D9C9AC] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#8B6F47] focus:ring-2 focus:ring-[#EADCC4]";
const money = (value: any, currency = "INR") => { try { return new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value || 0)); } catch { return `${currency} ${Number(value || 0).toLocaleString("en-IN")}`; } };

export default function RevenueOperationsWorkspace({ users, leads, canCreate, canEdit }: { users: User[]; leads: Lead[]; canCreate: boolean; canEdit: boolean }) {
  const [data,setData]=useState<Workspace>(empty), [mode,setMode]=useState<Mode>("forecast"), [busy,setBusy]=useState(true), [form,setForm]=useState(false), [error,setError]=useState(""), [message,setMessage]=useState(""), [month,setMonth]=useState(new Date().toISOString().slice(0,7));
  const load=useCallback(async()=>{setBusy(true);setError("");try{setData(await apiClient.get<Workspace>(`/crm/revenue-operations?month=${month}`));}catch(e:any){setError(e?.message||"Unable to load CRM revenue operations.");}finally{setBusy(false);}},[month]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{setForm(false);setError("");setMessage("");},[mode]);
  const userName=(id?:string)=>users.find(u=>u.id===id)?.name||"Unassigned";
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const formElement=event.currentTarget;const raw:any=Object.fromEntries(new FormData(formElement));setBusy(true);setError("");try{
    if(mode==="territories") await apiClient.post("/crm/territories",raw);
    else if(mode==="forecast") await apiClient.post("/crm/targets",{...raw,month,target_amount:Number(raw.target_amount||0),target_wins:Number(raw.target_wins||0),target_new_leads:Number(raw.target_new_leads||0),target_calls:Number(raw.target_calls||0),target_visits:Number(raw.target_visits||0),target_quotations:Number(raw.target_quotations||0),target_collections:Number(raw.target_collections||0),product_targets:JSON.parse(raw.product_targets||"[]")});
    else if(mode==="campaigns") await apiClient.post("/crm/campaigns",{...raw,budget:Number(raw.budget||0),expected_revenue:Number(raw.expected_revenue||0)});
    else if(mode==="templates") await apiClient.post("/crm/message-templates",raw);
    else if(mode==="automation") await apiClient.post("/crm/workflow-rules",{...raw,conditions:{field:raw.condition_field||null,operator:raw.condition_operator||"EQUALS",value:raw.condition_value||null},actions:[{type:raw.action_type||"CREATE_TASK",instructions:raw.action_instructions||""}]});
    else if(mode==="communications") await apiClient.post("/crm/communications/email",{...raw,confirm:"SEND"});
    formElement.reset();setForm(false);setMessage(mode==="communications"?"Email sent and recorded in the CRM timeline.":"CRM configuration saved.");await load();
  }catch(e:any){setError(e?.message||"Unable to save the CRM configuration.");}finally{setBusy(false);}};
  const approve=async(kind:"template"|"workflow",id:string,approved:boolean)=>{setBusy(true);setError("");try{await apiClient.patch(kind==="template"?`/crm/message-templates/${id}/approval`:`/crm/workflow-rules/${id}/approval`,{approved});await load();}catch(e:any){setError(e?.message||"Unable to update approval.");}finally{setBusy(false);}};
  const tabs:Array<[Mode,string,any]>=[["forecast","Forecast & targets",BarChart3],["cadences","Cadences",CalendarClock],["campaigns","Campaigns",Megaphone],["territories","Territories",MapPinned],["templates","Templates",Mail],["automation","Workflow control",Settings2],["communications","Communication ledger",GitBranch]];
  return <section className="space-y-4">
    <header className="rounded-2xl border border-[#E7DBC5] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#8B6F47]">Revenue operations</p><h2 className="text-2xl font-black">Sales execution and intelligence</h2><p className="text-sm text-[#6F5A49]">Targets, follow-up cadences, campaigns, governed communication and auditable automation.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2"><RefreshCw className={`h-4 w-4 ${busy?"animate-spin":""}`}/>Refresh</button></div></header>
    {error&&<p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><K label="Target" value={money(data.analytics.target)}/><K label="Won" value={money(data.analytics.won)}/><K label="Attainment" value={`${data.analytics.attainment||0}%`}/><K label="Weighted pipeline" value={money(data.analytics.weighted_pipeline)}/><K label="Attention" value={`${data.analytics.stale_deals||0} stale / ${data.analytics.overdue_next_actions||0} overdue`}/></div>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border bg-white p-1.5">{tabs.map(([key,label,Icon])=><button key={key} onClick={()=>setMode(key)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold ${mode===key?"bg-[#3E2A1F] text-white":"text-[#6F5A49] hover:bg-[#F7F3EA]"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>
    <div className="flex justify-between"><div>{mode==="forecast"&&<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className={input}/>}</div>{canCreate&&mode!=="cadences"&&<button onClick={()=>setForm(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#8B6F47] px-4 py-2 font-bold text-white"><Plus className="h-4 w-4"/>{mode==="communications"?"Compose email":mode==="forecast"?"New target":mode==="campaigns"?"New campaign":mode==="territories"?"New territory":mode==="templates"?"New template":"New workflow"}</button>}</div>
    {mode==="forecast"&&<Scorecards rows={data.scorecards} userName={userName}/>} 
    {mode==="cadences"&&<Cadences data={data} leads={leads} canCreate={canCreate} reload={load} setError={setError}/>} 
    {mode==="campaigns"&&<Campaigns campaigns={data.campaigns} leads={leads} reload={load} setError={setError}/>} 
    {mode==="territories"&&<Cards rows={data.territories} render={(row:any)=><><b>{row.territory_name}</b><small>{row.territory_code} · Manager: {userName(row.manager_user_id)}</small><p>{[row.country_filter,row.state_filter,row.city_filter,row.industry_filter].filter(Boolean).join(" / ")||"No routing filters"}</p></>}/>} 
    {mode==="templates"&&<Cards rows={data.templates} render={(row:any)=><><div className="flex justify-between"><b>{row.template_name}</b><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.approved_external_use?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{row.approved_external_use?"APPROVED":"DRAFT"}</span></div><small>{row.channel} · {row.category||"General"}</small><p>{row.subject||row.body.slice(0,120)}</p>{canEdit&&<button onClick={()=>approve("template",row.id,!row.approved_external_use)} className="mt-2 rounded-lg border px-3 py-1 text-xs font-bold">{row.approved_external_use?"Withdraw approval":"Approve for use"}</button>}</>}/>} 
    {mode==="automation"&&<Cards rows={data.workflows} render={(row:any)=><><div className="flex justify-between"><b>{row.rule_name}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{row.approval_status}</span></div><small>{row.entity_type} · {row.trigger_event}</small><p>{row.is_active?"Active governed workflow":"Inactive until approved"}</p>{canEdit&&row.approval_status==="DRAFT"&&<button onClick={()=>approve("workflow",row.id,true)} className="mt-2 rounded-lg border px-3 py-1 text-xs font-bold">Approve and activate</button>}</>}/>} 
    {mode==="communications"&&<div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-sm"><Head cells={["Channel","Recipient","Subject","Status","Date"]}/><tbody>{data.communications.map((row:any)=><tr key={row.id} className="border-b"><Td strong>{row.channel}</Td><Td>{row.recipient}</Td><Td>{row.subject||row.message_preview}</Td><Td>{row.delivery_status}</Td><Td>{new Date(row.created_at).toLocaleString()}</Td></tr>)}{!data.communications.length&&<Empty/>}</tbody></table></div>}
    {form&&<Modal title={mode==="communications"?"Compose governed email":`New ${mode}`} close={()=>setForm(false)} submit={submit} busy={busy}>{mode==="forecast"?<TargetForm users={users} territories={data.territories} items={data.items}/>:mode==="campaigns"?<CampaignForm users={users}/>:mode==="territories"?<TerritoryForm users={users}/>:mode==="templates"?<TemplateForm/>:mode==="automation"?<WorkflowForm/>:<EmailForm templates={data.templates}/>}</Modal>}
  </section>;
}

function Cadences({data,leads,canCreate,reload,setError}:{data:Workspace;leads:Lead[];canCreate:boolean;reload:()=>Promise<void>;setError:(v:string)=>void}) {
  const [show,setShow]=useState(false);
  const [enrollCadenceId,setEnrollCadenceId]=useState("");
  const [leadId,setLeadId]=useState("");
  const [steps,setSteps]=useState([{wait_days:0,action_type:"CALL",instructions:"Initial qualification call"}]);
  const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const raw:any=Object.fromEntries(new FormData(e.currentTarget));try{await apiClient.post("/crm/cadences",{cadence_name:raw.cadence_name,description:raw.description,is_active:true,steps});setShow(false);await reload();}catch(x:any){setError(x?.message||"Unable to create cadence.");}};
  const enroll=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!leadId)return;try{await apiClient.post(`/crm/cadences/${enrollCadenceId}/enroll`,{lead_id:leadId});setEnrollCadenceId("");setLeadId("");await reload();}catch(x:any){setError(x?.message||"Unable to enroll lead.");}};
  return <>
    <div className="flex justify-end">{canCreate&&<button onClick={()=>setShow(true)} className="rounded-xl bg-[#8B6F47] px-4 py-2 font-bold text-white">New cadence</button>}</div>
    <Cards rows={data.cadences} render={(row:any)=><><b>{row.cadence_name}</b><small>{row.is_active?"ACTIVE":"INACTIVE"} · {row.steps?.length||0} steps · {row.enrollments?.[0]?.count||0} enrollments</small>{row.steps?.map((s:any)=><p key={s.id}>{s.step_order}. Wait {s.wait_days} day(s) → {s.action_type}: {s.instructions}</p>)}<button onClick={()=>setEnrollCadenceId(row.id)} className="mt-2 rounded-lg border px-3 py-1 text-xs font-bold">Enroll lead</button></>}/>
    {show&&<Modal title="New follow-up cadence" close={()=>setShow(false)} submit={save} busy={false}><input required name="cadence_name" className={input} placeholder="Cadence name"/><textarea name="description" className={input} placeholder="Purpose"/>{steps.map((s,i)=><div key={i} className="grid gap-2 sm:grid-cols-[100px_140px_1fr]"><input aria-label="Wait days" type="number" min="0" value={s.wait_days} onChange={e=>setSteps(v=>v.map((x,n)=>n===i?{...x,wait_days:Number(e.target.value)}:x))} className={input}/><select aria-label="Action type" value={s.action_type} onChange={e=>setSteps(v=>v.map((x,n)=>n===i?{...x,action_type:e.target.value}:x))} className={input}><option>CALL</option><option>TASK</option><option>EMAIL</option><option>WHATSAPP</option></select><input aria-label="Instructions" value={s.instructions} onChange={e=>setSteps(v=>v.map((x,n)=>n===i?{...x,instructions:e.target.value}:x))} className={input}/></div>)}<button type="button" onClick={()=>setSteps(v=>[...v,{wait_days:2,action_type:"TASK",instructions:"Follow up"}])} className="rounded-lg border px-3 py-2">Add step</button></Modal>}
    {enrollCadenceId&&<Modal title="Enroll lead in cadence" close={()=>setEnrollCadenceId("")} submit={enroll} busy={false}><select required value={leadId} onChange={e=>setLeadId(e.target.value)} className={input}><option value="">Select lead</option>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.lead_number} — {lead.company_name}</option>)}</select><p className="text-xs text-[#6F5A49]">Cadence steps become assigned follow-up activities. Email and WhatsApp steps still require approved content and explicit send confirmation.</p></Modal>}
  </>;
}
function Campaigns({campaigns,leads,reload,setError}:{campaigns:any[];leads:Lead[];reload:()=>Promise<void>;setError:(v:string)=>void}) {
  const [campaignId,setCampaignId]=useState("");
  const [leadIds,setLeadIds]=useState<string[]>([]);
  const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();try{await apiClient.post(`/crm/campaigns/${campaignId}/members`,{lead_ids:leadIds});setCampaignId("");setLeadIds([]);await reload();}catch(x:any){setError(x?.message||"Unable to add campaign members.");}};
  return <><Cards rows={campaigns} render={(row:any)=><><b>{row.campaign_name}</b><small>{row.campaign_code} · {row.campaign_type} · {row.status}</small><p>Budget {money(row.budget,row.currency_code)} · Expected {money(row.expected_revenue,row.currency_code)}</p><button onClick={()=>setCampaignId(row.id)} className="mt-2 rounded-lg border px-3 py-1 text-xs font-bold">Select leads</button></>}/>{campaignId&&<Modal title="Select campaign leads" close={()=>setCampaignId("")} submit={add} busy={false}><div className="max-h-80 space-y-2 overflow-y-auto rounded-xl border p-3">{leads.map(lead=><label key={lead.id} className="flex items-center gap-2 rounded-lg bg-[#F7F3EA] px-3 py-2 text-sm"><input type="checkbox" checked={leadIds.includes(lead.id)} onChange={e=>setLeadIds(e.target.checked?[...leadIds,lead.id]:leadIds.filter(id=>id!==lead.id))}/><span><b>{lead.company_name}</b><small className="block">{lead.lead_number}</small></span></label>)}{!leads.length&&<p className="text-sm text-slate-500">No active leads are available.</p>}</div></Modal>}</>;
}
function TargetForm({users,territories,items}:{users:User[];territories:any[];items:any[]}){
  const [products,setProducts]=useState<Array<{item_id:string;target_quantity:number;target_value:number;uom:string}>>([]);
  const addProduct=()=>setProducts(rows=>[...rows,{item_id:"",target_quantity:0,target_value:0,uom:""}]);
  const updateProduct=(index:number,patch:Partial<(typeof products)[number]>)=>setProducts(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
  return <div className="space-y-5">
    <section><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#8B6F47]">Ownership</p><div className="grid gap-3 sm:grid-cols-2"><select name="user_id" className={input}><option value="">Salesperson target</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="territory_id" className={input}><option value="">Or territory target</option>{territories.map(t=><option key={t.id} value={t.id}>{t.territory_name}</option>)}</select><select name="currency_code" className={input}><option>INR</option><option>AED</option><option>USD</option></select></div></section>
    <section><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#8B6F47]">Commercial targets</p><div className="grid gap-3 sm:grid-cols-2"><input required name="target_amount" type="number" min="0" className={input} placeholder="Won revenue target"/><input name="target_collections" type="number" min="0" className={input} placeholder="Customer collections target"/><input name="target_wins" type="number" min="0" className={input} placeholder="Won deals target"/><input name="target_quotations" type="number" min="0" className={input} placeholder="Quotations target"/></div></section>
    <section><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#8B6F47]">Activity and pipeline targets</p><div className="grid gap-3 sm:grid-cols-3"><input name="target_new_leads" type="number" min="0" className={input} placeholder="New leads"/><input name="target_calls" type="number" min="0" className={input} placeholder="Completed calls"/><input name="target_visits" type="number" min="0" className={input} placeholder="Visits / meetings"/></div></section>
    <section><div className="mb-2 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#8B6F47]">Product targets</p><p className="text-xs text-slate-500">Actual quantity and value come from posted sales invoices.</p></div><button type="button" onClick={addProduct} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Add product</button></div><input type="hidden" name="product_targets" value={JSON.stringify(products)}/><div className="space-y-2">{products.map((row,index)=><div key={index} className="grid gap-2 rounded-xl bg-[#F7F3EA] p-3 sm:grid-cols-[1fr_120px_140px_36px]"><select aria-label="Product" required value={row.item_id} onChange={e=>{const selected=items.find(item=>item.id===e.target.value);updateProduct(index,{item_id:e.target.value,uom:selected?.uom||""});}} className={input}><option value="">Select product</option>{items.map(item=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select><input aria-label="Quantity target" type="number" min="0" step="0.001" value={row.target_quantity||""} onChange={e=>updateProduct(index,{target_quantity:Number(e.target.value)})} className={input} placeholder={`Qty${row.uom?` (${row.uom})`:""}`}/><input aria-label="Value target" type="number" min="0" step="0.01" value={row.target_value||""} onChange={e=>updateProduct(index,{target_value:Number(e.target.value)})} className={input} placeholder="Value target"/><button type="button" aria-label="Remove product" onClick={()=>setProducts(rows=>rows.filter((_,i)=>i!==index))} className="text-red-600">×</button></div>)}</div></section>
  </div>
}
function Scorecards({rows,userName}:{rows:any[];userName:(id?:string)=>string}){return <div className="space-y-3">{rows.map(row=>{const a=row.actual||{};const owner=row.user_id?userName(row.user_id):(row.territory?.territory_name||"Territory");return <article key={row.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-black">{owner}</h3><p className="text-xs text-slate-500">Monthly salesperson scorecard · {row.currency_code}</p></div><span className={`rounded-full px-3 py-1 text-sm font-black ${row.overall_attainment>=100?"bg-emerald-100 text-emerald-800":row.overall_attainment>=70?"bg-amber-100 text-amber-800":"bg-red-50 text-red-700"}`}>{row.overall_attainment||0}% overall</span></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Won revenue" actual={money(a.revenue,row.currency_code)} target={money(row.target_amount,row.currency_code)}/><Metric label="Collections" actual={money(a.collections,row.currency_code)} target={money(row.target_collections,row.currency_code)}/><Metric label="Won deals" actual={a.wins||0} target={row.target_wins||0}/><Metric label="New leads" actual={a.new_leads||0} target={row.target_new_leads||0}/><Metric label="Calls" actual={a.calls||0} target={row.target_calls||0}/><Metric label="Visits / meetings" actual={a.visits||0} target={row.target_visits||0}/><Metric label="Quotations" actual={a.quotations||0} target={row.target_quotations||0}/><Metric label="Weighted pipeline" actual={money(a.weighted_pipeline,row.currency_code)} target="Live forecast"/></div>{row.product_targets?.length>0&&<div className="mt-4 overflow-x-auto"><table className="min-w-full text-xs"><Head cells={["Product","Quantity actual / target","Value actual / target"]}/><tbody>{row.product_targets.map((product:any)=><tr key={product.id} className="border-b"><Td strong>{product.item?.code} — {product.item?.name}</Td><Td>{Number(product.actual?.quantity||0).toLocaleString("en-IN")} / {Number(product.target_quantity||0).toLocaleString("en-IN")} {product.uom||product.item?.uom||""}</Td><Td>{money(product.actual?.value,row.currency_code)} / {money(product.target_value,row.currency_code)}</Td></tr>)}</tbody></table></div>}</article>})}{!rows.length&&<p className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">No target is configured for this month. Create a target to activate the salesperson scorecard.</p>}</div>}
function Metric({label,actual,target}:{label:string;actual:any;target:any}){return <div className="rounded-xl bg-[#F7F3EA] p-3"><p className="text-xs font-bold uppercase text-[#806D5C]">{label}</p><p className="mt-1 font-black">{actual}</p><p className="text-xs text-slate-500">Target: {target}</p></div>}
function CampaignForm({users}:{users:User[]}){return <div className="grid gap-3 sm:grid-cols-2"><input required name="campaign_name" className={input} placeholder="Campaign name"/><select name="campaign_type" className={input}><option>EMAIL</option><option>WHATSAPP</option><option>EVENT</option><option>WEB</option><option>REFERRAL</option><option>PARTNER</option><option>OTHER</option></select><select name="owner_user_id" className={input}><option value="">Owner</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select name="status" className={input}><option>PLANNED</option><option>ACTIVE</option><option>PAUSED</option><option>COMPLETED</option></select><input name="start_date" type="date" className={input}/><input name="end_date" type="date" className={input}/><input name="budget" type="number" min="0" className={input} placeholder="Budget"/><input name="expected_revenue" type="number" min="0" className={input} placeholder="Expected revenue"/><textarea name="description" className={`${input} sm:col-span-2`} placeholder="Campaign objective"/></div>}
function TerritoryForm({users}:{users:User[]}){return <div className="grid gap-3 sm:grid-cols-2"><input required name="territory_name" className={input} placeholder="Territory name"/><select name="manager_user_id" className={input}><option value="">Manager</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input name="country_filter" className={input} placeholder="Country"/><input name="state_filter" className={input} placeholder="State / region"/><input name="city_filter" className={input} placeholder="City"/><input name="industry_filter" className={input} placeholder="Industry"/></div>}
function TemplateForm(){return <div className="grid gap-3"><input required name="template_name" className={input} placeholder="Template name"/><select name="channel" className={input}><option>EMAIL</option><option>WHATSAPP</option></select><input name="category" className={input} placeholder="Category"/><input name="subject" className={input} placeholder="Email subject"/><textarea required name="body" rows={7} className={input} placeholder="Message body"/><p className="text-xs text-amber-700">A manager must approve the template before external use.</p></div>}
function WorkflowForm(){return <div className="grid gap-3 sm:grid-cols-2"><input required name="rule_name" className={input} placeholder="Workflow name"/><select name="entity_type" className={input}><option>LEAD</option><option>OPPORTUNITY</option><option>ACCOUNT</option><option>CONTACT</option><option>ACTIVITY</option></select><select name="trigger_event" className={input}><option>CREATED</option><option>STAGE_CHANGED</option><option>OWNER_CHANGED</option><option>OVERDUE</option><option>WON</option><option>LOST</option></select><input name="condition_field" className={input} placeholder="Condition field (optional)"/><input name="condition_value" className={input} placeholder="Condition value"/><select name="action_type" className={input}><option>CREATE_TASK</option><option>NOTIFY_OWNER</option><option>REQUEST_APPROVAL</option><option>ENROLL_CADENCE</option></select><textarea name="action_instructions" className={`${input} sm:col-span-2`} placeholder="Action instructions"/><p className="text-xs text-amber-700 sm:col-span-2">The workflow remains inactive until explicitly approved.</p></div>}
function EmailForm({templates}:{templates:any[]}){return <div className="grid gap-3"><select name="template_id" className={input}><option value="">Write manually</option>{templates.filter(t=>t.channel==="EMAIL"&&t.approved_external_use).map(t=><option key={t.id} value={t.id}>{t.template_name}</option>)}</select><input required name="to" type="email" className={input} placeholder="Recipient email"/><input name="subject" className={input} placeholder="Subject (filled by template when blank)"/><textarea name="body" rows={8} className={input} placeholder="Message (filled by template when blank)"/><p className="text-xs text-amber-700">Sending is intentional, tenant-branded and written to the CRM communication ledger.</p></div>}
function Modal({title,close,submit,busy,children}:{title:string;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean;children:any}){return <div className="fixed inset-0 z-[1300] flex items-center justify-center bg-black/50 p-4"><button className="absolute inset-0" onClick={close}/><form onSubmit={submit} className="relative max-h-[90vh] w-full max-w-3xl space-y-4 overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><h3 className="text-xl font-black">{title}</h3><button type="button" onClick={close}><X/></button></div>{children}<button disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-[#3E2A1F] px-5 py-2.5 font-bold text-white disabled:opacity-50">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}Save</button></form></div>}
function Cards({rows,render}:{rows:any[];render:(row:any)=>any}){return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(row=><article key={row.id} className="space-y-2 rounded-2xl border bg-white p-4 shadow-sm">{render(row)}</article>)}{!rows.length&&<p className="col-span-full rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">No records yet.</p>}</div>}
function K({label,value}:{label:string;value:any}){return <div className="rounded-2xl border bg-white p-4"><small className="font-bold uppercase text-[#806D5C]">{label}</small><p className="mt-1 text-xl font-black">{value}</p></div>}
function Head({cells}:{cells:string[]}){return <thead className="border-b bg-[#F7F3EA] text-left text-xs uppercase text-[#6F5A49]"><tr>{cells.map(c=><th key={c} className="p-3">{c}</th>)}</tr></thead>}
function Td({children,strong}:{children:any;strong?:boolean}){return <td className={`p-3 ${strong?"font-bold":""}`}>{children}</td>}
function Empty(){return <tr><td colSpan={8} className="p-8 text-center text-slate-500">No records for this view.</td></tr>}
