'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Clock3, Factory, PackageSearch, RefreshCw, Wrench } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

const field='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
const number=(value:any,digits=0)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:digits}).format(Number(value||0));
const hours=(minutes:any)=>`${number(Number(minutes||0)/60,1)} h`;

export default function CapacityPlanningPage(){
  const[data,setData]=useState<any>({summary:{},stations:[],wip:[],exceptions:[]}),[stations,setStations]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showSetup,setShowSetup]=useState(false);
  const load=useCallback(async()=>{setBusy(true);try{const[board,masters]=await Promise.all([apiClient.get('/enterprise-edge/capacity-wip'),apiClient.get('/production/work-stations')]);setData(board);setStations(masters||[]);setMessage('')}catch(error:any){setMessage(error?.message||'Unable to load capacity and WIP control.')}finally{setBusy(false)}},[]);
  useEffect(()=>{load()},[load]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);try{await apiClient.post('/enterprise-edge/capacity-slots',Object.fromEntries(new FormData(event.currentTarget)));event.currentTarget.reset();setMessage('Daily capacity saved.');await load()}catch(error:any){setMessage(error?.message||'Unable to save daily capacity.');setBusy(false)}};
  const critical=useMemo(()=>(data.exceptions||[]).slice(0,12),[data.exceptions]);
  return <main className="mx-auto max-w-[1500px] space-y-5 p-3 sm:p-5">
    <header className="rounded-2xl bg-gradient-to-r from-[#3F2D22] to-[#795638] p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-amber-100">Production execution intelligence</p><h1 className="mt-1 text-2xl font-bold">Capacity & WIP Control</h1><p className="mt-2 max-w-4xl text-sm text-amber-50">One view of work-centre load, active production, material blocks, overdue operations and delivery risk. This workbench is advisory and does not release or complete job orders.</p></div><div className="flex gap-2"><button onClick={()=>setShowSetup(x=>!x)} className="rounded-lg border border-white/40 px-3 py-2 text-sm">{showSetup?'Hide':'Set'} capacity</button><button onClick={load} className="rounded-lg border border-white/40 p-2" aria-label="Refresh"><RefreshCw className={`h-5 w-5 ${busy?'animate-spin':''}`}/></button></div></div></header>
    {message&&<div className={`rounded-lg border p-3 text-sm ${message.includes('saved')?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}>{message}</div>}
    {showSetup&&<form onSubmit={submit} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-[2fr_1fr_1fr_auto]"><select required name="work_station_id" className={field}><option value="">Select work station</option>{stations.map(x=><option key={x.id} value={x.id}>{x.station_code||x.code} · {x.station_name||x.name}</option>)}</select><input required name="work_date" type="date" className={field}/><input required name="available_minutes" type="number" min="0" placeholder="Available minutes" className={field}/><button disabled={busy} className="rounded-lg bg-[#4A3526] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Save</button></form>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><K icon={<Factory/>} label="Active jobs" value={number(data.summary.active_job_orders)}/><K icon={<AlertTriangle/>} label="Jobs at risk" value={number(data.summary.at_risk_jobs)} risk={data.summary.at_risk_jobs>0}/><K icon={<PackageSearch/>} label="WIP quantity" value={number(data.summary.wip_quantity,2)}/><K icon={<PackageSearch/>} label="Material blocked" value={number(data.summary.material_blocked_jobs)} risk={data.summary.material_blocked_jobs>0}/><K icon={<Clock3/>} label="Overdue operations" value={number(data.summary.overdue_operations)} risk={data.summary.overdue_operations>0}/><K icon={<Wrench/>} label="Capacity utilization" value={`${number(data.summary.capacity_utilization_percent,1)}%`} risk={data.summary.capacity_utilization_percent>100}/></section>
    <section className="rounded-xl border bg-white p-4"><div className="flex items-end justify-between gap-3"><div><h2 className="font-semibold">Work-centre load</h2><p className="text-xs text-slate-500">Uses configured daily capacity, finite schedules and the latest APS stage requirement.</p></div><span className="text-xs text-slate-500">Updated {data.generated_at?new Date(data.generated_at).toLocaleString():'—'}</span></div><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Work centre</th><th className="p-2">Available</th><th className="p-2">Required</th><th className="p-2">Remaining / overload</th><th className="p-2">Load</th><th className="p-2">Status</th></tr></thead><tbody>{(data.stations||[]).map((x:any)=><tr key={x.id} className="border-b"><td className="p-2"><b>{x.station_code}</b><small className="block text-slate-500">{x.station_name}</small></td><td className="p-2">{hours(x.available_minutes)}</td><td className="p-2">{hours(x.required_minutes)}<small className="block text-slate-500">APS {hours(x.aps_required_minutes)}</small></td><td className={`p-2 ${x.overload_minutes>0?'font-semibold text-red-700':''}`}>{x.overload_minutes>0?`${hours(x.overload_minutes)} overload`:`${hours(x.remaining_minutes)} free`}</td><td className="min-w-44 p-2"><div className="h-2 overflow-hidden rounded bg-slate-100"><div className={`h-full ${x.load_percent>100?'bg-red-500':x.load_percent>=85?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${Math.min(100,x.load_percent)}%`}}/></div><small>{number(x.load_percent,1)}%</small></td><td className="p-2"><Badge value={x.status}/></td></tr>)}</tbody></table>{!data.stations?.length&&!busy&&<p className="py-6 text-sm text-slate-500">No active work centres or planning loads found.</p>}</div></section>
    <div className="grid gap-5 xl:grid-cols-[2fr_1fr]"><section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Active WIP and delivery risk</h2><p className="text-xs text-slate-500">Remaining quantity is order quantity less completed and rejected quantity.</p><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Job order</th><th className="p-2">Progress</th><th className="p-2">Current operation</th><th className="p-2">Material</th><th className="p-2">Due</th><th className="p-2">Risk</th></tr></thead><tbody>{(data.wip||[]).map((x:any)=><tr key={x.id} className={x.risk==='AT_RISK'?'border-b bg-red-50/50':'border-b'}><td className="p-2"><b>{x.job_order_number}</b><small className="block max-w-64 text-slate-500">{x.item_code} · {x.item_name}</small></td><td className="p-2"><b>{number(x.completed_quantity,2)} / {number(x.quantity,2)}</b><small className="block text-slate-500">{number(x.remaining_quantity,2)} remaining · {number(x.rejected_quantity,2)} rejected</small></td><td className="p-2">{x.active_operation?.operation_name||'Not assigned'}<small className="block text-slate-500">{x.operation_count} operations · {x.overdue_operation_count} overdue</small></td><td className="p-2"><span className={x.material_shortage_count?'font-semibold text-red-700':''}>{x.material_shortage_count?`${x.material_shortage_count} shortages`:'Ready'}</span></td><td className="p-2">{x.due_date||'Not set'}</td><td className="p-2"><Badge value={x.risk}/><small className="mt-1 block max-w-52 text-red-700">{(x.exceptions||[]).join(' · ')}</small></td></tr>)}</tbody></table>{!data.wip?.length&&!busy&&<p className="py-6 text-sm text-slate-500">No active production WIP.</p>}</div></section><aside className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Priority exceptions</h2><p className="text-xs text-slate-500">Resolve from top to bottom; no automatic operational action is taken.</p><div className="mt-3 space-y-2">{critical.map((x:any,index:number)=><div key={`${x.code}-${x.job_order_id||x.work_station_id}-${index}`} className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><b>{String(x.code).replaceAll('_',' ')}</b><p className="mt-1 text-xs text-slate-600">{x.job_order_number?`${x.job_order_number} · ${x.item_code||''} · due ${x.due_date||'not set'}`:`${x.work_station} · ${number(x.load_percent,1)}% load · ${hours(x.overload_minutes)} overload`}</p></div>)}{!critical.length&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">No current capacity or WIP exception.</p>}</div></aside></div>
  </main>;
}

function K({icon,label,value,risk=false}:{icon:any;label:string;value:string;risk?:boolean}){return <div className={`rounded-xl border p-4 ${risk?'border-red-200 bg-red-50':'bg-white'}`}><div className="flex items-center justify-between text-xs text-slate-500"><span>{label}</span><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span></div><p className="mt-2 text-xl font-bold">{value}</p></div>}
function Badge({value}:{value:string}){const risk=['AT_RISK','OVERLOADED','NO_CAPACITY'].includes(value);return <span className={`inline-flex rounded-full px-2 py-1 text-xs font-semibold ${risk?'bg-red-100 text-red-800':value==='AVAILABLE'||value==='ON_TRACK'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{String(value||'UNKNOWN').replaceAll('_',' ')}</span>}
