'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Loader2, RefreshCw } from 'lucide-react';
import { apiClient } from '../../../../../lib/api-client';

type Ncr = { id: string; ncr_number?: string; status?: string; nonconformance_type?: string; item_name?: string; quantity_affected?: number; cost_impact?: number; ncr_date?: string };
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const openStatuses = new Set(['OPEN', 'UNDER_REVIEW', 'ACTION_PLANNED', 'IN_PROGRESS', 'RESOLVED']);

export default function CostOfQualityPage() {
  const [ncrs, setNcrs] = useState<Ncr[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setNcrs(await apiClient.get<Ncr[]>('/quality/ncr')); } catch (e: any) { setError(e?.message || 'Unable to load NCR cost data.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const summary = useMemo(() => { const open = ncrs.filter(n => openStatuses.has(String(n.status || '').toUpperCase())); const total = ncrs.reduce((s, n) => s + Number(n.cost_impact || 0), 0); const openCost = open.reduce((s, n) => s + Number(n.cost_impact || 0), 0); return { open, total, openCost }; }, [ncrs]);
  return <div className="mx-auto max-w-7xl space-y-5 p-2 sm:p-4"><section className="rounded-2xl bg-gradient-to-r from-[#713C31] to-[#A46044] p-5 text-white shadow-lg sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm text-orange-100"><AlertTriangle size={18} /> Finance-visible operational leakage</div><h1 className="text-2xl font-bold sm:text-3xl">Cost of Poor Quality</h1><p className="mt-2 max-w-2xl text-sm text-orange-50">Actual cost impacts declared on NCRs. This is a management-control view, not an accounting posting.</p></div><button onClick={load} disabled={loading} className="rounded-lg bg-white/15 p-2 hover:bg-white/25 disabled:opacity-60">{loading ? <Loader2 className="animate-spin" size={18} /> : <RefreshCw size={18} />}</button></div></section>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<section className="grid gap-3 sm:grid-cols-3"><Metric label="Declared NCR impact" value={money(summary.total)} /><Metric label="Open exposure" value={money(summary.openCost)} /><Metric label="Open NCRs" value={String(summary.open.length)} /></section><div className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Only NCRs with a declared cost impact are monetised. Populate and review this field during the NCR workflow before using it for ROI decisions.</div><section className="rounded-xl border bg-white p-4 shadow-sm"><h2 className="font-semibold">NCR cost register</h2>{loading ? <div className="flex items-center gap-2 py-8 text-sm text-slate-500"><Loader2 size={16} className="animate-spin" /> Loading NCRs…</div> : ncrs.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-2">NCR</th><th className="p-2">Type</th><th className="p-2">Item</th><th className="p-2">Status</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Declared impact</th></tr></thead><tbody>{ncrs.slice(0, 100).map(n => <tr key={n.id} className="border-b border-slate-100"><td className="p-2 font-medium">{n.ncr_number || 'NCR'}</td><td className="p-2">{n.nonconformance_type || '—'}</td><td className="p-2">{n.item_name || '—'}</td><td className="p-2">{n.status || '—'}</td><td className="p-2 text-right">{n.quantity_affected || 0}</td><td className="p-2 text-right font-semibold">{money(Number(n.cost_impact || 0))}</td></tr>)}</tbody></table></div> : <div className="mt-4 rounded bg-slate-50 p-6 text-sm text-slate-500">No NCRs are recorded for this tenant yet.</div>}</section></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-white p-4 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold text-slate-900">{value}</div></div>; }
