"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, Check, Loader2, RefreshCw, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "../../../../../../lib/api-client";
import { hasSuperAdminRole, isAdminLike } from "../../../../../lib/rbac";

type Finding={id:string;check_key:string;module:string;severity:string;title:string;summary:string;evidence:Record<string,unknown>;entity_type?:string;entity_id?:string;entity_code?:string;status:string;first_seen_at:string;last_seen_at:string;occurrence_count:number;linked_support_incident_id?:string|null};
type Snapshot={profile:string;tenant_id?:string|null;configuration:{enabled:boolean;mode:string;scheduleEnabled:boolean;intervalMinutes:number;checks:{checkKey:string;module:string;severity:string}[]};findings:Finding[];bySeverity:Record<string,number>;lastRun:any};
const severities=["CRITICAL","HIGH","MEDIUM","LOW","INFO"];

export default function AutoQaSystemHealthPage(){
  const router=useRouter();const[authorized,setAuthorized]=useState(false);const[superAdmin,setSuperAdmin]=useState(false);const[profileWide,setProfileWide]=useState(false);const[snapshot,setSnapshot]=useState<Snapshot|null>(null);const[status,setStatus]=useState("OPEN");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[activeRun,setActiveRun]=useState<any>(null);
  const refresh=useCallback(async()=>{try{const value=await apiClient.get<Snapshot>(`/autoqa/admin?profileWide=${profileWide}&status=${status}&limit=300`);setSnapshot(value);setError("");}catch(e:any){setError(e?.message||"Auto QA findings could not be loaded.");}},[profileWide,status]);
  useEffect(()=>{let cancelled=false;void apiClient.getCurrentUser().then(user=>{if(cancelled)return;if(!isAdminLike(user??null)){router.replace("/dashboard");return;}const central=hasSuperAdminRole(user??null);setSuperAdmin(central);setProfileWide(central);setAuthorized(true);}).catch(()=>{if(!cancelled)router.replace("/login");});return()=>{cancelled=true;};},[router]);
  useEffect(()=>{if(authorized)void refresh();},[authorized,refresh]);
  useEffect(()=>{if(!activeRun?.id)return;let cancelled=false;const poll=async()=>{try{const run=await apiClient.get<any>(`/autoqa/admin/runs/${activeRun.id}`);if(cancelled)return;setActiveRun(run);if(run.status==="RUNNING")setTimeout(poll,2000);else{setBusy(false);await refresh();toast.success(`Auto QA completed: ${run.checks_run} checks, ${run.findings_created} new findings.`);}}catch(e:any){if(!cancelled){setBusy(false);setError(e?.message||"Run status could not be loaded.");}}};const timer=setTimeout(poll,1500);return()=>{cancelled=true;clearTimeout(timer);};},[activeRun?.id,activeRun?.status,refresh]);
  const start=async()=>{setBusy(true);setError("");try{const response=await apiClient.post<any>("/autoqa/admin/run",{profileWide});setActiveRun(response.run);toast.message("Auto QA started. Results are read-only.");}catch(e:any){setBusy(false);setError(e?.message||"Auto QA could not start.");}};
  const acknowledge=async(id:string)=>{try{await apiClient.patch(`/autoqa/admin/findings/${id}/acknowledge`,{});toast.success("Finding acknowledged.");await refresh();}catch(e:any){toast.error(e?.message||"Finding could not be acknowledged.");}};
  if(!authorized)return null;
  const findings=(snapshot?.findings||[]).filter(row=>row.status===status);
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-700">System Health / Auto QA</p><h1 className="mt-2 text-3xl font-semibold text-slate-900">Read-only ERP checks</h1><p className="mt-2 text-sm text-slate-600">Findings are evidence for review. Auto QA does not repair ERP records.</p></div><div className="flex gap-2"><button onClick={()=>void refresh()} className="rounded-lg border px-3 py-2 text-sm"><RefreshCw className="mr-2 inline h-4 w-4"/>Refresh</button><button disabled={busy||!snapshot?.configuration.enabled||snapshot.configuration.mode==="OFF"} onClick={()=>void start()} className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?<><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Running</>:"Run Auto QA Now"}</button></div></header>
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ShieldAlert className="mr-2 inline h-4 w-4"/>{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Profile / mode</div><strong>{snapshot?.profile||"—"} / {snapshot?.configuration.mode||"OFF"}</strong></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Last run</div><strong>{snapshot?.lastRun?.started_at?new Date(snapshot.lastRun.started_at).toLocaleString():"Not run"}</strong></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Checks run</div><strong>{snapshot?.lastRun?.checks_run??0}</strong></div>{severities.map(sev=><div key={sev} className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{sev}</div><strong>{snapshot?.bySeverity?.[sev]||0}</strong></div>)}</section>
    {activeRun?.status==="RUNNING"&&<div role="status" className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-900"><Activity className="mr-2 inline h-4 w-4"/>Run {activeRun.id} is processing. {activeRun.checks_run||0} / {snapshot?.configuration.checks.length||0} checks completed.</div>}
    <div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg border bg-white p-1">{["OPEN","ACKNOWLEDGED","RESOLVED"].map(tab=><button key={tab} onClick={()=>setStatus(tab)} className={`rounded-md px-3 py-2 text-sm ${status===tab?"bg-slate-900 text-white":"text-slate-600"}`}>{tab}</button>)}</div>{superAdmin&&<label className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><input type="checkbox" checked={profileWide} onChange={e=>setProfileWide(e.target.checked)}/>Profile-wide findings</label>}{snapshot?.configuration.mode==="OBSERVE"&&<span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800">OBSERVE · no AutoEngineer incidents</span>}</div>
    <section className="space-y-3">{findings.map(row=><article key={row.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{row.severity}</span><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs">{row.module}</span><span className="text-xs text-slate-500">{row.check_key}</span></div><h2 className="mt-2 font-semibold text-slate-900">{row.title}</h2><p className="mt-1 text-sm text-slate-700">{row.summary}</p></div>{row.status==="OPEN"&&<button onClick={()=>void acknowledge(row.id)} className="rounded-lg border px-3 py-2 text-sm"><Check className="mr-1 inline h-4 w-4"/>Acknowledge</button>}</div><dl className="mt-4 grid gap-3 text-xs text-slate-600 sm:grid-cols-4"><div><dt>Reference</dt><dd className="font-medium">{row.entity_code||row.entity_id||"—"}</dd></div><div><dt>First seen</dt><dd>{new Date(row.first_seen_at).toLocaleString()}</dd></div><div><dt>Last seen / occurrences</dt><dd>{new Date(row.last_seen_at).toLocaleString()} · {row.occurrence_count}</dd></div><div><dt>AutoEngineer</dt><dd>{row.linked_support_incident_id?`Incident ${row.linked_support_incident_id}`:"Eligible only in INCIDENT mode"}</dd></div></dl><details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Evidence</summary><pre className="mt-2 overflow-auto rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(row.evidence,null,2)}</pre></details></article>)}{!findings.length&&<div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-500">No {status.toLowerCase()} findings for this scope.</div>}</section>
    <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Registered checks ({snapshot?.configuration.checks.length||0})</summary><ul className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{snapshot?.configuration.checks.map(check=><li key={check.checkKey} className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{check.checkKey}</strong><div className="text-xs text-slate-500">{check.module} · {check.severity}</div></li>)}</ul></details>
  </main>;
}
